### ISSUE TITLE
"Runtime exception: Some exception during recording fields" when expected text/html

### ISSUE THREAD

**Issue by stalexmr** [serenity-bdd/serenity-core#700] opened 2017-02-23 12:02 UTC
I try to send the request like this:

rest().
                given().log().all().
                contentType("application/x-www-form-urlencoded").
                param("Param", param).
                when().
                post(baseUrl + "/some");

and expected text response like this:

Hello World.

Content-Encoding →gzip
Content-Length →46
Content-Type →text/html; charset=utf-8

Application sent request successsfully, but I get an exception on string  post(baseUrl + "/some"):

```
org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:888)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
	at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
	at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
	at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
	at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
	at net.serenitybdd.rest.filters.FieldsRecordingFilter.filter(FieldsRecordingFilter.java:40)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.execute(RequestSpecificationDecorated.java:222)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:72)
	at net.serenitybdd.rest.decorators.request.RequestSpecificationDecorated.post(RequestSpecificationDecorated.java:25)
	at com.payture.interfaces.utils.Direct.sendReestrRequest(Direct.java:146)
	at com.payture.interfaces.steps.DirectSteps.sendReestr(DirectSteps.java:411)
	at com.payture.api.tests.SeparatePayAndFullRefundForAllSellers.separatePayAndFullRefundForAllSellers(SeparatePayAndFullRefundForAllSellers.java:44)

```
And "Runtime exception: Some exception during recording fields" in my serenity report.

pom.xml:
<serenity.version>1.2.2</serenity.version>

**Comment by wakaleo** [comment] 2017-02-28 11:20
Serenity is just passing the URL through to RestAssured, so this would be more likely to be an issue with RestAssured (or something about the URL) than Serenity. I suggest putting a breakpoint in FieldsRecordingFilter and seeing what URL it is passing to RestAssured.

**Comment by haroonismailbasha** [comment] 2017-05-30 18:55
Im not sure whether leave a comment in here. Suggestion is .. Please feel free to remove me If I should not. check java version. and whether it is https or http it took more time for me to find out https issue.

**Comment by wakaleo** [comment] 2017-07-18 11:12
I'll close this for now, as it seems to be a non-Serenity issue. Please reopen if you have reason to believe otherwise.

**Closed by wakaleo** 2017-07-18 11:12 UTC

**Comment by AnushaMadduru** [comment] 2017-08-16 10:12
Hi stalexmr,

Hope you have got the solution,

If not you can try the below code 
given().relaxedHTTPSValidation().when().get("https://some_server.com"). ..

**Comment by chronicideas** [comment] 2019-06-17 12:34
Hi stalexmr, I think John is right. I ran into this same error and put a breakpoint on my api call and realised my URL wasn't including the base path as I forgot to include my request specification.

**Comment by Majestry** [comment] 2020-07-02 14:38
I have such problem with next versions:
net.serenity-bdd:serenity-core:2.2.5
net.serenity-bdd:serenity-cucumber5:2.2.5
net.serenity-bdd:serenity-rest-assured:2.2.5

When server responses with 302 status and RestAssured is configured to follow the redirects - then "Some exception during recording fields" appears.
If in RestAssured i specify .redirects().follow(false) - then everything's fine, 302 with all request and response data is in report

**Comment by wakaleo** [comment] 2020-07-02 14:39
Do you have a reason to suspect that this is an issue with the Serenity code?

**Comment by Majestry** [comment] 2020-07-02 14:51
Not exactly.

The root of the issue is wrong host name, specified in Location header in 302 response (http://localhist, for example.)

If RestAssured, not SerenityRest, is used in such case - next exception is thrown
**java.net.UnknownHostException: localhist: nodename nor servname provided, or not known**
with the full stacktrace.

However, when SerenityRest is used, this exception is suppressed and the only shown is "Some exception during recording fields." without any details or stacktrace. 

If it is possible and, of course, if it makes sense from your point of view, it can be useful to have such original errors from RestAssured in test report.

**Comment by wakaleo** [comment] 2020-07-02 14:53
In that case the best would be to dig into the SerenityRest code to see where the exception is being suppressed and to propose a PR to provide more info.

**Comment by jacob-wieland-gematik** [comment] 2025-01-29 11:56
Added a possible solution to this in https://github.com/serenity-bdd/serenity-core/pull/3609
