### ISSUE TITLE
 switchToPage is deprecated

### ISSUE THREAD

**Issue by ahmed-al-sadoon** [serenity-bdd/serenity-core#2142] opened 2020-06-30 07:55 UTC
Hi everyone,
i have updated to serenity 2.2.10 then i have seen that the switchToPage function is deprecated
could you help me please to solve this?

Best regeards
Ahmed

**Comment by wakaleo** [comment] 2020-06-30 07:59
Duplicate of  #2131

**Closed by wakaleo** 2020-06-30 07:59 UTC
Labels: duplicate
