### ISSUE TITLE
One browser for all tests?

### ISSUE THREAD

**Issue by witoldsz** [serenity-bdd/serenity-core#451] opened 2016-06-14 10:19 UTC
There is an option:
`serenity.use.unique.browser = true`
so it does not spawn a new browser for each test within a single JUnit class.

How could I make all the tests to use a single browser? Can I, for example, create my own WebDriver instance, attach it to some static field and distribute along all the tests, manually? Or something…

**Comment by wakaleo** [comment] 2016-06-14 12:18
The problem is knowing when to close the browser, as there is no way to know when you have finished running the last test.

**Comment by witoldsz** [comment] 2016-06-14 22:44
As far as I can see, the maven archetype, used to generate my project, the one you demonstrated in "Serenity BDD Tutorial Part 1", is using "Maven Failsafe Plugin". I'm reading it's documentation just now, take a look at this:

> The Maven lifecycle has four phases for running integration tests:
> - pre-integration-test for setting up the integration test environment.
> - integration-test for running the integration tests.
> - post-integration-test for tearing down the integration test environment.
> - verify for checking the results of the integration tests.

So, it looks like the `post-integration-test` could shut down the browser(s). It's been ages since I was writing and maintaining end-to-end tests in Java, I am not even sure I ever used that Maven plugin, so cannot tell if that would actually work, though… What do you think?

**Comment by YamStranger** [comment] 2016-07-05 19:23
@witoldsz all phased exists "separately", so it's quite hard to manage state between phases (I am talking about WebDriver instance). When WebDriver works with some browser it keep some connection with instance, and it is not possible connect new WebDriver to already opened browser, and close it.

That is why we have implementation that keep Browser "Reusable" during test cases, but not tests (One test case can contains some steps that will appear in report as tests), but close them between test cases.

Thanks for this question!

**Closed by YamStranger** 2016-07-05 19:23 UTC
Labels: question
