### ISSUE TITLE
Cucumber Aggregate Report Error Jenkins

### ISSUE THREAD

**Issue by jayzsuarez** [serenity-bdd/serenity-core#2065] opened 2020-05-01 09:25 UTC
@wakaleo 

Failed to aggregate report when running in Jenkins. 

Note: Able to run properly in Jenkins

`[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.0:aggregate (serenity-reports) on project ph-auto-serenity-cucumber: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.0:aggregate failed: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error in custom provider, com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path 'PATH+CHROMEDRIVER': Token not allowed in path expression: 'C' ('+' not followed by =, 'C' not allowed after '+') (you can double-quote this token if you really want it here)
[ERROR] at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
[ERROR] while locating net.thucydides.core.util.EnvironmentVariables`

Serenity-maven
` <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

**Comment by wakaleo** [comment] 2020-05-01 09:27
Can you provide any more details?

**Comment by jayzsuarez** [comment] 2020-05-01 09:30
Details:

`    
        <serenity.maven.version>2.2.0</serenity.maven.version>
        <serenity.version>2.2.1</serenity.version>`

`   
        <serenity.cucumber.version>2.2.0</serenity.cucumber.version>
        <cucumber.version>5.5.0</cucumber.version>`


`  <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

**Comment by wakaleo** [comment] 2020-05-01 09:31
It’s something to do with the chromedriver configuration and your serenity.conf file.

**Comment by globalworming** [comment] 2020-05-01 09:31
just to make sure: it works when running locally?

**Comment by jayzsuarez** [comment] 2020-05-01 09:34
@globalworming  and @wakaleo  yes it works fine locally, I was able to generate correct html report

**Comment by wakaleo** [comment] 2020-05-01 09:34
Could you post your serenity.conf file

**Comment by jayzsuarez** [comment] 2020-05-01 09:36
`webdriver {
  driver = chrome
}
headless.mode = false

#
# Chrome options can be defined using the chrome.switches property
#
chrome.switches="""--start-maximized;--test-type;--no-sandbox;--ignore-certificate-errors;
                   --disable-popup-blocking;--disable-default-apps;--disable-extensions-file-access-check;
                   --incognito;--disable-infobars,--disable-gpu"""
#
# Define drivers for different platforms. Serenity will automatically pick the correct driver for the current platform
#
drivers {
  windows {
    webdriver.chrome.driver = "src/test/resources/webdrivers/windows/chromedriver.exe"
    webdriver.gecko.driver = "src/test/resources/webdrivers/windows/geckodriver.exe"
  }
  linux {
    webdriver.chrome.driver = "src/test/resources/webdrivers/linux/chromedriver"
    webdriver.gecko.driver = "src/test/resources/webdrivers/linux/geckodriver"
  }
}
`

And also, I have a separate serenity.properties file. Is it conflict?

**Comment by jayzsuarez** [comment] 2020-05-01 09:38
@globalworming 

I have the same build config in CI and local

![image](https://user-images.githubusercontent.com/41811725/80796754-9c4e6d80-8bd2-11ea-9bce-e8f89c1a7fdc.png)

**Comment by wakaleo** [comment] 2020-05-01 09:39
Is there any more to the stackteace? It could be related to the environment variables on the Jenkins machine

**Comment by jayzsuarez** [comment] 2020-05-01 09:40
> Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.0:aggregate (serenity-reports) on project ph-auto-serenity-cucumber: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.0:aggregate failed: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error in custom provider, com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path 'PATH+CHROMEDRIVER': Token not allowed in path expression: 'C' ('+' not followed by =, 'C' not allowed after '+') (you can double-quote this token if you really want it here)
[ERROR] at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
[ERROR] while locating net.thucydides.core.util.EnvironmentVariables
[ERROR] 
[ERROR] 1 error
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by jayzsuarez** [comment] 2020-05-01 09:55
@wakaleo I think I solve the problem, I removed the serenity.conf file and move details inside my serenity.properties file.

![image](https://user-images.githubusercontent.com/41811725/80797665-00723100-8bd5-11ea-89ba-d3446d587b74.png)


Jenkins machine configured in environment variables in C.

**Comment by wakaleo** [comment] 2020-05-03 21:07
Would you mind listing the environment variables on Jenkins so that I can see if there is anything I can do about the serenity.conf processing? I suspect an issue with the TypeSafe Config parsing.

**Comment by jakimcho** [comment] 2020-05-05 13:45
Hi I got similar problem using Serenity version 2.2.2:

```
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.2:aggregate (serenity-reports) on project CSGOEmpire-automation: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.2:aggregate failed: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error in custom provider, com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path 'PATH+MAVEN': Token not allowed in path expression: 'M' ('+' not followed by =, 'M' not allowed after '+') (you can double-quote this token if you really want it here)
[ERROR] at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
[ERROR] while locating net.thucydides.core.util.EnvironmentVariables
[ERROR] 
[ERROR] 1 error
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```
This reproduces on Jenkins instances. Local runs generate reports.

Jenkins build the job with:
```
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /var/lib/jenkins/workspace/UI Automation/pom.xml clean verify -Dwebdriver.remote.url=[my_remote_driver]/wd/hub -Dcucumber.options=--tags '@regression or @performance or @endurance'  -Denvironment=default
```

**Comment by jayzsuarez** [comment] 2020-05-06 02:31
@wakaleo 

`C:\Program Files\EMC NetWorker\nsr\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Gradle\bin;D:\DevMachine\Jenkins_jayz\tools\hudson.model.JDK\JDK8\bin;D:\DevMachine\Python\Python38-32\Python38-32;D:\DevMachine\Python\Python38-32\Python38-32\Scripts;C:\chromedriver\;`

That was the content of env variables in the CI. I remove this 'C:\chromedriver\' when I'm running in the new configuration set up that chromedriver is defined and located in the project workspace.

Is that you are looking for?

**Comment by jayzsuarez** [comment] 2020-05-07 08:51
@wakaleo I move details from serenity.conf to serenity.properties file.

`#chromedriver
drivers.windows.webdriver.chrome.driver = src/test/resources/webdriver/windows/chromedriver.exe
drivers.linux.webdriver.chrome.driver = src/test/resources/webdriver/linux/chromedriver

#firefoxdriver
drivers.windows.webdriver.gecko.driver = src/test/resources/webdriver/windows/geckodriver.exe
drivers.linux.webdriver.gecko.driver = src/test/resources/webdriver/linux/geckodriver`


it worked for me for both linux and windows machine. And also I have some difficulty in the Linux, needed to add chmod 755 to web driver binaries to execute test.

**Comment by jakimcho** [comment] 2020-05-08 15:36
Hi again.
I checked the Jenkins instances versions, on which the error is reproducing, currently, those versions are: v2.53 and v2.195.
I have my own Jenkins instance where this exception does not reproduce. Its version is v2.229. There I have a maven job with simple serenity project v2.2.2 and serenity.conf set. There everything is fine.

**Comment by wakaleo** [comment] 2020-05-08 15:37
I think it’s something to do with the environment variables, but I would need to see the system environment variables for the Jenkins server to understand further.

**Comment by jayzsuarez** [comment] 2020-05-09 06:09
@wakaleo 

See the environment variables of Jenkins
Linux:
![image](https://user-images.githubusercontent.com/41811725/81465622-dc7aa500-91fd-11ea-9dec-4b9fc9f2244a.png)


windows:
![image](https://user-images.githubusercontent.com/41811725/81465731-a689f080-91fe-11ea-9fed-43d404aca9c5.png)

**Comment by jayzsuarez** [comment] 2020-05-09 08:32
@wakaleo 

Also reproducible in my local instance version: 2.204.5

![image](https://user-images.githubusercontent.com/41811725/81468521-a267ce00-9212-11ea-9592-4d17e2becfd1.png)

**Comment by wakaleo** [comment] 2020-05-09 08:36
It's something to do with adding Windows environment variables to the TypeSafe config properties. If you can reproduce it locally, have a look in the `net.thucydides.core.util.PropertiesFileLocalPreferences` class, and see if you can isolate the problem and propose a PR.

**Comment by wakaleo** [comment] 2020-05-10 11:58
Can you share your serenity.conf file?

**Comment by jakimcho** [comment] 2020-05-10 16:36
Hello, Here are my environments from failing Jenkins job:
```
Environments
+ env
BUILD_URL=https://jenkins.uat.gan:443/job/Automation%20Testing/job/Borgata%20Sanity/16/
POM_GROUPID=com.gameaccount.testing
HUDSON_SERVER_COOKIE=e0edeb448b1df0f8
SHELL=/bin/bash
SSH_CLIENT=127.0.0.1 59422 22
BUILD_TAG=jenkins-Automation Testing-Borgata Sanity-16
POM_DISPLAYNAME=borgata
environment=alpha
ROOT_BUILD_CAUSE=MANUALTRIGGER
WORKSPACE=/gan/usb/slaves/jenkins/workspace/Automation Testing/Common Casino System Testing
JOB_URL=https://jenkins.uat.gan:443/job/Automation%20Testing/job/Borgata%20Sanity/
RUN_CHANGES_DISPLAY_URL=https://jenkins.uat.gan:443/job/Automation%20Testing/job/Borgata%20Sanity/16/display/redirect?page=changes
USER=build
POM_ARTIFACTID=borgata
SELENIUM_GRID_HUB_URL=http://192.168.31.145:4444/wd/hub
MAVEN_OPTS=-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
JENKINS_HOME=/usr/local/jenkins
MAIL=/var/mail/build
MAVEN_HOME=/gan/usb/slaves/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven3
PATH=/gan/usb/slaves/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven3/bin:/usr/local/java/java8/bin:/usr/local/bin:/bin:/usr/bin
EUREKA_SERVICE_URI=[some_url]
RUN_DISPLAY_URL=https://jenkins.uat.gan:443/job/Automation%20Testing/job/Borgata%20Sanity/16/display/redirect
BUILD_CAUSE_MANUALTRIGGER=true
PWD=/gan/usb/slaves/jenkins/workspace/Automation Testing/Common Casino System Testing
JAVA_HOME=/usr/local/java/java8
HUDSON_URL=https://jenkins.uat.gan:443/
LANG=en_US.UTF-8
JOB_NAME=Automation Testing/Borgata Sanity
POM_VERSION=1.0.0-SNAPSHOT
CONFIG_SERVER_URI=[some_url]
BUILD_DISPLAY_NAME=#16
BUILD_CAUSE=MANUALTRIGGER
BUILD_ID=16
JENKINS_URL=https://jenkins.uat.gan:443/
JOB_BASE_NAME=Borgata Sanity
POM_PACKAGING=jar
HOME=/home/build
SHLVL=2
M2_HOME=/gan/usb/slaves/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven3
EXECUTOR_NUMBER=3
JENKINS_SERVER_COOKIE=e0edeb448b1df0f8
NODE_LABELS=Build MavBuild Maven
LOGNAME=build
CVS_RSH=ssh
SSH_CONNECTION=127.0.0.1 59422 127.0.0.1 22
HUDSON_HOME=/usr/local/jenkins
NODE_NAME=Build
LESSOPEN=||/usr/bin/lesspipe.sh %s
BUILD_NUMBER=16
JOB_DISPLAY_URL=https://jenkins.uat.gan:443/job/Automation%20Testing/job/Borgata%20Sanity/display/redirect
ROOT_BUILD_CAUSE_MANUALTRIGGER=true
HUDSON_COOKIE=fd6ba9e8-c206-4266-949a-3de8ed5b01ca
G_BROKEN_FILENAMES=1
_=/bin/env
```

And this is my serenity.conf:
```
environments {
    all {
        home.page = "#{webdriver.base.url}/"
        locators_path = "locators/locators.properties"
        kyc.partner.name = "gadgadhsfjsf"

        player{
              existing = "{ 'username': 'dasdas', 'password': 'gfdgfdgdf', 'email': 'test-fdsfdsfsd+sdfsdfdf@ofds.com'}"
              password = "{ 'username': 'fdfsdf', 'password': 'sdfsdfsd', 'email': 'test-automation+fsdfsdfs@ofds.com'}"
              paypal = "{ 'username': 'gfdgd', 'password': 'fsdfsdfs', 'email': 'test-automation+sdfsdfs@ofds.com'}"
              personalized = "{ 'username': 'fdsfsdf', 'password': 'gfdgdfgfgd', 'email': 'test-automation+fdsfdfsd@ofds.com'}"
              incorrect = "{ 'username': 'sdfsdf', 'password': 'fdsfsdfsd', 'email': 'incorrectuser@test'}"
             }

        games.integration {
            site.name = "Goran SOM"
            url.parameters = "partner=gogon&wiki=true"
            report.destination.dir = "target/games_integration"

            user1 {
                name = "Dogon"
                pass = "pahgbdm"
            }

            user2 {
                name = "Gogo"
                pass = "pahgbdm!"
            }
        }
    }

    default {
        webdriver.base.url = "https://obladiblada.defacto.gat.com"
        rest.base.uri = "https://obladiblada.defacto.gat.com"
    }

    qa {
        webdriver.base.url = "https://obladiblada.qatro.gat.com"
        rest.base.uri = "https://obladiblada.qatro.gat.com"
    }

    alpha {
        webdriver.base.url = "https://obladiblada.alp.gat.com"
        rest.base.uri = "https://obladiblada.alp.gat.com"
    }
}
```

**Comment by jakimcho** [comment] 2020-05-10 18:31
Okay, I finally know how to reproduce it. If `serenity.conf` is under test resources it fails on Jenkins. When it is under main resources it does not.

**Comment by wakaleo** [comment] 2020-05-10 18:36
That should make no difference unless there is something odd about your maven config.

**Comment by jakimcho** [comment] 2020-05-10 19:07
After upgrade to `2.2.5` and `serenity.conf` is in `src/test/resources` :
```
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/maven/plugins/serenity-maven-plugin/2.2.5/serenity-maven-plugin-2.2.5.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/maven/plugins/serenity-maven-plugin/2.2.5/serenity-maven-plugin-2.2.5.pom (8.5 kB at 5.1 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/maven/plugins/serenity-maven-plugin/2.2.5/serenity-maven-plugin-2.2.5.jar
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/maven/plugins/serenity-maven-plugin/2.2.5/serenity-maven-plugin-2.2.5.jar (31 kB at 45 kB/s)
[INFO] 
[INFO] ------------------< net.jakim.testing:SerentyStatup >-------------------
[INFO] Building Sample Serenity project using Cucumber 5 and WebDriver 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-core/2.2.5/serenity-core-2.2.5.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-core/2.2.5/serenity-core-2.2.5.pom (28 kB at 206 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-report-resources/2.2.5/serenity-report-resources-2.2.5.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-report-resources/2.2.5/serenity-report-resources-2.2.5.pom (5.9 kB at 44 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-model/2.2.5/serenity-model-2.2.5.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-model/2.2.5/serenity-model-2.2.5.pom (11 kB at 117 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/org/reflections/reflections/0.9.11/reflections-0.9.11.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/org/reflections/reflections/0.9.11/reflections-0.9.11.pom (9.1 kB at 103 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.pom (9.8 kB at 112 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-reports/2.2.5/serenity-reports-2.2.5.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-reports/2.2.5/serenity-reports-2.2.5.pom (6.2 kB at 69 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-stats/2.2.5/serenity-stats-2.2.5.pom
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-stats/2.2.5/serenity-stats-2.2.5.pom (6.2 kB at 68 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-core/2.2.5/serenity-core-2.2.5.jar
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-report-resources/2.2.5/serenity-report-resources-2.2.5.jar
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-model/2.2.5/serenity-model-2.2.5.jar
[INFO] Downloading from central: https://jcenter.bintray.com/org/reflections/reflections/0.9.11/reflections-0.9.11.jar
[INFO] Downloading from central: https://jcenter.bintray.com/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar
[INFO] Downloaded from central: https://jcenter.bintray.com/org/reflections/reflections/0.9.11/reflections-0.9.11.jar (134 kB at 343 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-reports/2.2.5/serenity-reports-2.2.5.jar
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-reports/2.2.5/serenity-reports-2.2.5.jar (130 kB at 250 kB/s)
[INFO] Downloading from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-stats/2.2.5/serenity-stats-2.2.5.jar
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-stats/2.2.5/serenity-stats-2.2.5.jar (94 kB at 145 kB/s)
[INFO] Downloaded from central: https://jcenter.bintray.com/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar (735 kB at 1.1 MB/s)
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-model/2.2.5/serenity-model-2.2.5.jar (884 kB at 427 kB/s)
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-core/2.2.5/serenity-core-2.2.5.jar (2.9 MB at 1.1 MB/s)
[INFO] Downloaded from central: https://jcenter.bintray.com/net/serenity-bdd/serenity-report-resources/2.2.5/serenity-report-resources-2.2.5.jar (3.6 MB at 1.3 MB/s)
[INFO] 
[INFO] --- serenity-maven-plugin:2.2.5:aggregate (default-cli) @ SerentyStatup ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.975 s
[INFO] Finished at: 2020-05-10T21:59:30+03:00
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.5:aggregate (default-cli) on project SerentyStatup: Execution default-cli of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.2.5:aggregate failed: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error in custom provider, com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path 'PATH+MAVEN': Token not allowed in path expression: 'M' ('+' not followed by =, 'M' not allowed after '+') (you can double-quote this token if you really want it here)
[ERROR] at net.thucydides.core.guice.ThucydidesModule.provideEnvironmentVariables(ThucydidesModule.java:78)
[ERROR] while locating net.thucydides.core.util.EnvironmentVariables
[ERROR] 
[ERROR] 1 error
[ERROR] -> [Help 1]
[ERROR] 
[JENKINS] Archiving /usr/local/jenkins/workspace/Serenity Tests/pom.xml to net.jakim.testing/SerentyStatup/1.0-SNAPSHOT/SerentyStatup-1.0-SNAPSHOT.pom
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
channel stopped
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /usr/local/jenkins/workspace/Serenity Tests/target/site/serenity to /usr/local/jenkins/jobs/Serenity Tests/htmlreports/HTML_20Report
Finished: FAILURE
```

Moving back `serenity.conf` to `src/main/resources`: 
```
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /usr/local/jenkins/workspace/Serenity Tests/pom.xml serenity:aggregate
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for net.jakim.testing:SerentyStatup:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 101, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------< net.jakim.testing:SerentyStatup >-------------------
[INFO] Building Sample Serenity project using Cucumber 5 and WebDriver 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- serenity-maven-plugin:2.2.5:aggregate (default-cli) @ SerentyStatup ---
[INFO] Test results for 9 tests generated in 1.3 secs in directory: file:/usr/local/jenkins/workspace/Serenity%20Tests/target/site/serenity/
[INFO] [1m[37m-----------------------------------------[0m
[INFO] [1m[37m SERENITY TESTS : [0m[1m[33mERROR[0m
[INFO] [1m[37m-----------------------------------------[0m
[INFO] | [1m[37mTests executed         [0m| [1m[37m9[0m
[INFO] | [1m[32mTests passed           [0m| [1m[32m7[0m
[INFO] | [1m[31mTests failed           [0m| [1m[31m0[0m
[INFO] | [1m[33mTests with errors      [0m| [1m[33m2[0m
[INFO] | [1m[35mTests compromised      [0m| [1m[35m0[0m
[INFO] | [1m[36mTests pending          [0m| [1m[36m0[0m
[INFO] | [1m[90mTests ignored/skipped  [0m| [1m[90m0[0m
[INFO] ------------------------ | --------------
[INFO] | Total Duration         | 2s 570ms
[INFO] | Fastest test took      | 008ms
[INFO] | Slowest test took      | 959ms
[INFO] -----------------------------------------
[INFO] 
[INFO] [1m[37mSERENITY REPORTS[0m
[INFO]   - Full Report: file:///usr/local/jenkins/workspace/Serenity%20Tests/target/site/serenity/index.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.586 s
[INFO] Finished at: 2020-05-10T22:03:57+03:00
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[JENKINS] Archiving /usr/local/jenkins/workspace/Serenity Tests/pom.xml to net.jakim.testing/SerentyStatup/1.0-SNAPSHOT/SerentyStatup-1.0-SNAPSHOT.pom
channel stopped
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /usr/local/jenkins/workspace/Serenity Tests/target/site/serenity to /usr/local/jenkins/jobs/Serenity Tests/htmlreports/HTML_20Report
Finished: SUCCESS
```

My test project is `https://github.com/jakimcho/SerenityStatup` branch `cucumber-5`. Please don't pay attention to the mess there. It was created trying to find a way to reproduce the problem on my Jenkins.

**Comment by wakaleo** [comment] 2020-05-10 19:22
Sorry I can't reproduce this at all.

**Comment by jakimcho** [comment] 2020-05-10 19:27
Ok I'll keep digging and if I find out what is cousing this problem, will write back.
Thank you to be so responsive.

**Comment by zuzeac** [comment] 2020-05-14 20:31
Hi, 
Facing the same issue, I've updated the libraries to the lastest versions. I tried different configurations but still, issue occurs while building on Jenkins machine. On local everything works.
I'm suspecting the Jenkins maven version, I have maven/3.5.4 on Jenkins. 
Any help would be great.

` <serenity.version>2.2.5</serenity.version>
        <serenity.maven.version>2.2.5</serenity.maven.version>
        <serenity.cucumber.version>2.2.2</serenity.cucumber.version>
        <cucumber.version>5.6.0</cucumber.version>
`

**Comment by wakaleo** [comment] 2020-05-14 20:43
It’s probably something to do with TypesafeConfig loading environment variables and getting confused, but I have not been able to reproduce it at all.

**Comment by zuzeac** [comment] 2020-05-15 09:44
I just tried to user the exact configs and libraries version from here https://github.com/serenity-bdd/serenity-cucumber5-starter/blob/master/pom.xml in my project, but nothing.

**Comment by wakaleo** [comment] 2020-05-15 09:49
If the problem is happening with https://github.com/serenity-bdd/serenity-cucumber-starter then it is some kind of environment-related issue. Without being able to reproduce, it will be extremely hard to fix.

**Comment by jakimcho** [comment] 2020-05-28 06:41
Hello, just a little update here. I have Upgraded to serenity v2.2.8 and the problem stopped reproducing.

**Comment by zuzeac** [comment] 2020-05-28 07:17
Hi @jakimcho , @wakaleo , I can confirm that it's working for e as well after updating the libraries to 2.2.8.
Current config:
 ` <serenity.version>2.2.8</serenity.version>
        <serenity.maven.version>2.2.8</serenity.maven.version>
        <serenity.cucumber.version>2.2.5</serenity.cucumber.version>
        <cucumber.version>5.6.0</cucumber.version>`

**Comment by wakaleo** [comment] 2020-05-28 07:32
Thanks for the feedback, I'll close this issue then.

**Closed by wakaleo** 2020-05-28 07:32 UTC
Labels: can't-fix
