### ISSUE TITLE
Cannot navigate to failure test from summary page 

### ISSUE THREAD

**Issue by saminam** [serenity-bdd/serenity-core#2024] opened 2020-04-09 15:02 UTC
Hi Team,
I am using junit started project , when a test case is failed and when tried to click the hyperlink in summary report I get page not found for only failed or unsucessful hyperlink.
Can you please assist me with this.

I have tried with latest version of serenity 2.2.1.
![image](https://user-images.githubusercontent.com/63410021/78909423-673f7700-7a7b-11ea-8c5f-b4463472bcfd.png)
![image](https://user-images.githubusercontent.com/63410021/78909463-76bec000-7a7b-11ea-9517-d4616edd6b65.png)

Also I wanted to know if we can run both serenity junit test and cucumber test  in parallel , Will serenity aggregate both test results from cucumber and junit, appreciate your response please  on this please

**Comment by wakaleo** [comment] 2020-04-09 15:07
I can't reproduce this - can you provide a sample project? See https://github.com/serenity-bdd/screenplay-pattern-todomvc for an example of reporting on both Cucumber and JUnit tests.

**Comment by saminam** [comment] 2020-04-09 15:24
Thanks for the information will try that,
please find attached sample project 
[serenity-junit-starter.zip](https://github.com/serenity-bdd/serenity-core/files/4457054/serenity-junit-starter.zip)

Below observations:

1. Cannot navigate from summary page to failed results (onclick on unsuccesful and failed hyperlink)
2. Coverage in requirements, features and story is not capturing the failed tests

**Comment by wakaleo** [comment] 2020-04-09 15:49
OK, I can reproduce it now - it looks like an issue with parameterised tests. Thanks for the sample project.

**Comment by shoheb90** [comment] 2020-07-31 11:55
Hi @wakaleo  
I am also facing the same issue, Can you please let me if its fixed in any version? Eagerly waiting to get this fixed please.

**Comment by wakaleo** [comment] 2020-07-31 11:56
Try with 2.1.12

**Comment by shoheb90** [comment] 2020-07-31 12:00
> Try with 2.1.12
@wakaleo 
Its the same issue with 2.1.12 and with latest version as well 2.2.12.

**Comment by shoheb90** [comment] 2020-08-04 14:50
@wakaleo  any help on this please.

**Comment by wakaleo** [comment] 2020-08-04 14:53
It's on the backlog, and will be picked up when I or a member of the community has some time. If it is important to you then a commercial support ticket is the quickest option to get someone to work on it sooner.

**Closed** 2022-02-12 15:10 UTC
Labels: bug
