### ISSUE TITLE
@After not executing the lines of code provided in it

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-core#2175] opened 2020-07-17 17:27 UTC
Hello , 

I am using below method after each scenario , however the code within it is not getting executed except the report.Info line. 
Please suggest. I need to login again if a scenario is failed.

@After
	public void afterScenario(Scenario scenario) throws InterruptedException, IOException {
		String status = scenario.getStatus().toString();
		  if (!status.equals("PASSED")) {
		  report.Info("Scenario failed , logging in again");
		  domainPage.loginCheck("MediaEE");
		  }

**Comment by wakaleo** [comment] 2020-07-28 11:47
Duplicate of #2176

**Closed by wakaleo** 2020-07-28 11:47 UTC
