### ISSUE TITLE
Tests are marked as Pending instead of Passed when using @Test(timeout=x)

### ISSUE THREAD

**Issue by mihaiserdeanixxus** [serenity-bdd/serenity-core#45] opened 2015-04-06 12:01 UTC
Original issue:
01:45:41 687015 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: saveButtonClick
09:40:52 29197772 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: saveButtonClick

as you can see the tests hanged between 01:45 am and 09:40, so about 8 hours. there were no errors on the environment, OS, drivers, browsers, logs etc

So I looked for a way to resolve this, by adding the test timeout from junit 4.12.
added @Test(timeout = x) and thucydides is marking the passed tests as skipped/pending

Test timeout (junit 4.12)
1. @Test(timeout = Constants.TEST_TIMEOUT_MILLISECONDS) applies only to @Test and not to @Before and @After
2. @Rule public Timeout globalTimeout = new Timeout(Long.parseLong(System.getProperty("customTestTimeoutInSeconds")), TimeUnit.SECONDS);

if test timeout is reached then it works
but in case of test pass, thucydides (0.9.275)/serenity(1.0.45) marks the test as skipped/pending, because it runs in another thread and doesn't reach the expected code.

I did not find other test timeouts options in thucydides. is there a workaround until this is fixed?

**Comment by wakaleo** [comment] 2015-04-13 03:04
I haven't been able to reproduce this issue, could you create a demo project that illustrates the problem?

**Comment by mihaiserdean** [comment] 2015-04-23 12:31
====== Example for using test timeout inlcuding @Before and @After ====== 

Test01.java:

@Story(Application.Test01.class)
@RunWith(SerenityParameterizedRunner.class)
@UseTestDataFrom(value = Constants.CSV_FILES_PATH + "Test01.csv", separator = Constants.CSV_SEPARATOR)
public class Test01 extends AbstractTest {

    @Steps
    private CustomSteps customSteps;

    @Test
    @Title("Test01")
    public void test01() {
        customSteps.doSomething();
    }
}

AbstractTest.java:

@RunWith(SerenityParameterizedRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public abstract class AbstractTest {

    @Managed(uniqueSession = false)
    public WebDriver driver;
    @ManagedPages(defaultUrl = Constants.URL)
    public Pages pages;

     @Rule    
     public Timeout globalTimeout = new Timeout(Long.parseLong(System.getProperty("customTestTimeoutInSeconds")), TimeUnit.SECONDS);

    @Before
    public void setup() {
        pages.currentPageAt(CustomPage.class).doSomething();
    }

    @After
    public void tearDown() {
        StepEventBus.getEventBus().clearStepFailures();
        pages.currentPageAt(CustomPage2.class).doSomething();
    }
}


====== Example for using test timeout in @Test (without @Before or @After) ====== 

Test01.java: 

@Story(Application.Test01.class)
@RunWith(SerenityParameterizedRunner.class)
@UseTestDataFrom(value = Constants.CSV_FILES_PATH + "Test01.csv", separator = Constants.CSV_SEPARATOR)
public class Test01 extends TestCase {

    @Steps
    private CustomSteps customSteps;

    @Test(timeout = Constants.TEST_TIMEOUT_MILLISECONDS) 
    @Title("Test01")
    public void test01() {
        customSteps.doSomething();
    }
}

**Comment by mihaiserdeanixxus** [comment] 2015-04-24 08:10
Please let me know if you need more information.

**Comment by wakaleo** [comment] 2015-04-29 10:39
I couldn't reproduce this exact behavior, but timeouts are a world of pain because they seem to bypass the normal exception catching in the instrumented code. If you think you can implement a patch, I'm open to pull requests.

**Comment by mihaiserdean** [comment] 2015-04-29 11:51
Can you tell me how to avoid the hanging behaviour from Thucydides/Serenity, which is in fact the root cause?

Original issue:
01:45:41 687015 [main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: saveButtonClick
09:40:52 29197772 [main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: saveButtonClick

as you can see the tests hanged between 01:45 am and 09:40, so about 8 hours. there were no errors on the environment, OS, drivers, browsers, logs etc

**Comment by wakaleo** [comment] 2015-04-29 12:07
Could you provide a stack trace of the threads when it is hanging? I have fixed some issues in this area which will be included in the next release (should be out by the end of the week), but I would like to see if you are having a different issue.

**Comment by dbratucu** [comment] 2015-04-29 12:58
As you mention, tests with timeouts are a pain, as they run on a different stack (as seen in debugger), rather than being initiated by the Serenity runner. I haven't dug into the internals of why this is, just helped Mihai investigate the issue. So no code to contribute.
In terms of the hanging issue, this behavior is quite sporadic. Do you have any recommendations/preferences on how to help you identify the problem? I.e. tooling we can easily set up to catch relevant information.

**Comment by wakaleo** [comment] 2015-05-05 20:59
Hanging tests with Serenity are most often the Selenium driver waiting for things for too long - I haven't been able to isolate any actual deadlocks, though that is always a possiblity too. In Serenity 1.0.47 there are a few optimizations to reduce the number of WebDriver calls that need to be made, so it would be woth trying the old tests with this version to see if they work better.

**Comment by mihaiserdean** [comment] 2015-05-06 10:58
thank  you. will update to 1.0.47 and let you know

**Comment by YamStranger** [comment] 2015-11-11 11:16
Hi @mihaiserdean,@mihaiserdeanixxus

Do you have any updates for this issue. Can it be already closed?

**Closed** 2015-11-18 19:42 UTC

**Comment by Moustakas42** [comment] 2016-06-08 16:56
Serenity 1.1.31: Tests that pass are reported as SKIPPED. What could be missing?

**Comment by wakaleo** [comment] 2016-06-08 17:00
Could you try with 1.1.36 and provide a sample project that reproduces the issue?

**Comment by Moustakas42** [comment] 2016-06-08 17:07
Actually, 1.1.36 does not seem to work with the AppiumDriver :S

**Comment by wakaleo** [comment] 2016-06-08 17:08
What error are you getting?

**Comment by Moustakas42** [comment] 2016-06-08 17:09
No error. Tests start and fail, nothing passes to Appium. Trying resetting the Appium server also.

**Comment by Moustakas42** [comment] 2016-06-08 17:12
[pom.zip](https://github.com/serenity-bdd/serenity-core/files/305320/pom.zip)
Attaching POM + props

**Comment by wakaleo** [comment] 2016-06-08 17:13
Have you changed versions of Appium?

**Comment by Moustakas42** [comment] 2016-06-08 17:16
When I was trying to make it work... I noticed the one generated is out of date. Removed the dependency and tried again with 1.1.36, but no luck.

**Comment by wakaleo** [comment] 2016-06-08 17:22
Your pom file only has the serenity-maven-plugin dependency at 1.1.36, serenity-core is still at 1.1.31

**Comment by Moustakas42** [comment] 2016-06-09 07:16
Yup, because 1.1.36 wouldn't start Appium tests

**Comment by wakaleo** [comment] 2016-06-09 07:34
Could you raise a separate issue for Appium/1.1.36? It might help if you put a breakpoint in the newAppiumDriver() method in WebdriverInstanceFactory to see what is going on.

**Comment by Moustakas42** [comment] 2016-06-09 07:59
Done. Should I raise the reporting issue separately also?

**Comment by wakaleo** [comment] 2016-06-09 08:30
If you are still seeing it, then yes

**Comment by TrishaChetani** [comment] 2019-12-02 17:16
I am seeing this issueç
Feature: Refactor and deploy the new data-structure

      @REQ_DCE2EDCHO-1364 @TEST_DCE2EDCHO-1925 @TESTSET_DCE2EDCHO-1944
      Scenario: POST    /api/presentations [90m# src/test/resources/features/jenkins/0.feature:11[0m

com.adidas.testrunner.TestRunner > Refactor and deploy the new data-structure.POST    /api/presentations STANDARD_ERROR
    [Test worker] INFO net.thucydides.core.steps.ConsoleLoggingListener -
