### ISSUE TITLE
Serenity report contains wrong result when child of AssertionError thrown

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-core#834] opened 2017-07-05 16:02 UTC
Serenity report displays ERROR(orange) result instead of FAILURE(red), when test throws some error, extended from `java.lang.AssertionError` (e.g. [`SoftAssertionError`](/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/SoftAssertionError.java) from [assertj-core](/joel-costigliola/assertj-core)). Please have a look at attached screenshot - it contains some self-explained details in the bottom section.
![screen](https://user-images.githubusercontent.com/6312221/27873175-c9560c9e-61b3-11e7-918b-993213cfc9cd.png)

After investigation I've found out that issue started to reproduce on serenity-core version **1.2.3-rc.10+** (up to latest version **1.5.0-rc.1**). Works as expected on **1.2.3-rc.9**

P.S. Archive with simple maven project: 
[serenity_exceptions.zip](https://github.com/serenity-bdd/serenity-core/files/1152608/serenity_exceptions.zip)

**Comment by wakaleo** [comment] 2017-07-16 11:22
I'm unable to reproduce this; could you provide a sample project?

**Comment by scormaq** [comment] 2017-07-17 12:49
Hi @wakaleo , thanks for response. I've updated original post with archived maven project. It already contains generated Serenity report.

**Comment by wakaleo** [comment] 2017-07-17 22:45
This should be fixed in the next release.
The problem is due to the exception classes not being on the plugin classpath. A work-around is to add the project itself as a dependency of the maven-serenity-plugin, but this should happen automatically in version 1.5.1-rc.5.

**Comment by wakaleo** [comment] 2017-07-17 23:26
Fixed in 1.5.1-rc.5

**Closed by wakaleo** 2017-07-17 23:26 UTC
Labels: waiting for feedback
