### ISSUE TITLE
CucumberWithSerenity.class is not working 

### ISSUE THREAD

**Issue by lilyhoang** [serenity-bdd/serenity-core#1872] opened 2019-11-19 02:28 UTC
I working with Serenity BDD and Appium. 
When I run scenarios by TestSuite and run with CucumberWithSerenity.class, It will be fail at first scenario. From second one, scenarios pass normally (although scenarios have the same content).
I run from IDE (IntellJ), scenarios run normally
I'm using serenity version 2.0.80, and had tried to using lower version (1.70) but it doesnt help.

I had tried using @RunWith(Cucumber.class) then issue is disappeared. 

Please help to resolve
![Selection_999(153)](https://user-images.githubusercontent.com/20644391/69111045-f2a97300-0aae-11ea-8e55-1400042a3aaf.png)

**Comment by wakaleo** [comment] 2019-11-21 06:58
I would need to see a sample project that reproduces this issue to understand.

**Comment by thanhvc** [comment] 2019-11-21 07:48
Hi,

After run debugging. The class: CapabilityEnhancer invoked the code as below:

> AddCustomDriverCapabilities.from(environmentVariables)
                                       .withTestDetails(driver, outcome)
                                       .to(capabilities);

then, net.serenitybdd.screenplay.Tasks will be initialized.
and next, the Object of Pages will be created with empty constructor. That's the reason the driver is NULL.

> private static Pages pages = new Pages();
private static StepFactory stepFactory = StepFactory.getFactory().usingPages(pages);

**Solution**
Excluded  **serenity-screenplay** and **serenity-screenplay**  from serenity-core and serenity-cucumber. It's working well on our side.

**Comment by wakaleo** [comment] 2019-11-21 08:02
@thanhvc Do you have a project that reproduces this issue?

**Comment by wakaleo** [comment] 2019-11-21 09:04
I have a potential fix for this but I can't verify as I cannot reproduce the issue.

**Comment by thanhvc** [comment] 2019-11-22 01:08
I have checked your fixing and This on is really perfect.
Thanks you so much to support!

**Closed** 2020-01-15 07:38 UTC
Labels: waiting for feedback
