### ISSUE TITLE
Report Generation takes lot of time

### ISSUE THREAD

**Issue by nshiveg** [serenity-bdd/serenity-core#1336] opened 2018-08-09 05:39 UTC
Hi John,

We are using serenity for continuous automation for over 2.5 years in NOKIA for our IOT projects.
We have 2 queries which in our run and results.

Query 1. The automation duration mentioned in the report and the console logs are different. 
For example: Report shows 4 hours and console shows 12 hours. 

In regard to this we have 2 questions.
a. Why there is a mismatch between console and report time.

b. How to reduce the time taken for run? 
During API automation(using Serenity Rest Assured) we had the parallel execution taking place where we had the multiple runner class and we were modifying the <forkCount>11</forkCount> value and all. However in the UI automation we cannot have the multiple runner class, since UI session will go away when another runner class executes the same login scenario. So we also need your insight on how to have parallel execution for UI automation.

Query 2. Report generation takes around 2 hours for our 1500 test cases. In that pending cases are 750 and it takes almost 45 minutes. Overall automated+manual+pending takes 2 hours for report generation. 

Question is: Is there any way to reduce the time for report generation.

![image](https://user-images.githubusercontent.com/20845350/43879987-30436ba4-9bc4-11e8-8def-5d7eb0cea0bc.png)

**Comment by wakaleo** [comment] 2018-08-09 06:10
Test duration is the sum of the time taken by each test, which may not be the same as the total time of the test suite (it doesn't include report generation for example). 

Report generation should not take that long. What test framework are you using? For example we have seen JBehave take a very long time to process large test reports, because of the way it loads the stories into memory before processing (which is one reason why I recommend Cucumber over JBehave).

For UI testing, it sound's like your application does not allow the same user to be connected simultaneously in different sessions? If this is not a deliberate functionality, I would ask for this to be fixed. Otherwise, you can create multiple users and set up a system of pools of users rather than running the tests with a specific user.

For more project-specific support (for example I'd be happy to review your test suite to look for specific strategies to improve the test performance), have you looked at our Enterprise support options (https://johnfergusonsmart.com/serenity-bdd-mentoring/#support)?

**Comment by nshiveg** [comment] 2018-08-09 06:36
Hi John,

We are using cucumber framework for automation. 
Our requirement does not allow for same user to login. The other logged-in user session will be timed out.  


Regards
Nithin H S

**Comment by wakaleo** [comment] 2018-08-09 06:42
In that case you should be able to run your UI scenarios in parallel by writing runner classes for each batch or group you want to run, and using the standard Maven support for parallel tests. For more leverage you can set up a Selenium grid (very easy to do with Docker for example)

**Comment by nshiveg** [comment] 2018-08-09 07:08
Hi John,

You mean to say we need to group our features and create a runner class for each group so that each login will not interfere with each other. 

And for report generation do you think we are doing something wrong? because our code will not be having any connection with the report right?. So is there any way to reduce the time taken?

**Comment by wakaleo** [comment] 2018-08-09 07:11
Yes, for the grouping that is correct. Regarding the report generation, I would need to see the project structure and the report generation running to understand what is happening.

**Comment by nshiveg** [comment] 2018-08-09 10:14
Hi John,

We will discuss with the management about Enterprise support we need and update you. Because we are thinking about the same, since we have few more questions regarding the XPATH problems. 

Before closing this issue(about report time and parallel execution) we will again discuss with team and come back with few more questions regarding the same topic before 10th Aug COB IST. So please don't close the issue.

**Comment by wakaleo** [comment] 2018-08-09 10:51
@nshiveg Understood

**Comment by immidisrikanth** [comment] 2018-10-01 06:44
Hi ,

I am using Serenity in my Automation project, While implementing Grid I initiated Remote driver but Inbuilt method of BDD getDriver() method is used in scripts. Remote Driver initiated in Hooks is getting overridden by getDriver() method in Pages.class (inbuilt method from serenity).

Due to this tests are not running on Node.

Hooks.java:

Remotedriver = new RemoteWebDriver(new URL("http://10.128.32.43:4444/wd/hub"), ieOptions);
In scripts :

getDriver().findElement(By.xpath("//input[contains(@data-bind,'closingReferenceId')]")).click();

Thanks for help

Thanks,
Srikanth

**Comment by wakaleo** [comment] 2018-10-01 10:08
@immidisrikanth this question is unrelated to this issue, so it isn't really the right place to raise it. Serenity manages the drivers for you, so this is intentional. If you want to use a remote driver, see http://thucydides.info/docs/serenity-staging/#_running_remote_tests.

**Comment by MichaelVovk** [comment] 2021-08-13 07:30
We faced the same issue with Cucumber API tests. Tests are running 25min. And report generation taken more than 45 min. Is there a way to optimize it? Report generation not even using all CPU resources.

**Comment by wakaleo** [comment] 2021-08-13 07:34
Report generation should take a couple of minutes, max, especially for API tests. I have a test suite with over 2000 API tests that takes only a few minutes to generate. If report generation is slow, it may be an operating system issue. Do you have anti-virus software running on the machine?

**Comment by MichaelVovk** [comment] 2021-08-13 11:07
This happens in any environment. Local or Gitlab CI as well. No Anti-virus. 400 API test only. Logging level="INFO"

**Comment by wakaleo** [comment] 2021-08-13 11:18
@MichaelVovk can you provide a sample project that reproduces the issue?

**Comment by MichaelVovk** [comment] 2021-08-13 13:07
I'm not sure about it. My report is 3 Gb size is it ok for 400 tests?

**Comment by wakaleo** [comment] 2021-08-13 14:28
@MichaelVovk it's not the report that would help, it's the project that generates it and takes time to do so. I've never seen this behaviour so have no idea what it could be due to.

**Comment by globalworming** [comment] 2021-08-18 19:38
> I'm not sure about it. My report is 3 Gb size is it ok for 400 tests?

are you sure this is correct? 3Gb? a small report is like 10mb because of heavy dependencies.. so 2.99Gb for 400 tests sounds impossible

**Comment by MichaelVovk** [comment] 2021-08-19 08:02
@globalworming yes, size is about 3Gb every time. We use different users and relogin for each FF. It might be connected to that. But I'm not sure. 3Gb and 10Mb is a huge difference .

**Comment by wakaleo** [comment] 2021-08-19 08:20
Maybe have a look at the contents of the report directory. API tests produce no screenshots, just JSON and HTML, so that size does seem impossible from the Serenity report files alone.

**Comment by MichaelVovk** [comment] 2021-08-19 10:11
![image](https://user-images.githubusercontent.com/8253679/130050856-e213cc84-cea6-420f-9890-778b874d0686.png)
Yes only JSON and HTML but 28k files 
![image](https://user-images.githubusercontent.com/8253679/130051148-605a0b6b-554e-4bbe-9e24-c4a49ac96572.png)

**Comment by wakaleo** [comment] 2021-08-20 14:59
Can you share the report directory contents?

**Comment by globalworming** [comment] 2021-08-21 22:49
my very small examle report has like `360 files` which are all static dependencies,  with the tests json/html being `16 KiB` to `32 KiB` in siz . I am a bit befuddled how you get `29k files` from 400 tests :)

**Comment by MichaelVovk** [comment] 2021-08-23 09:22
@wakaleo I will try 

![image](https://user-images.githubusercontent.com/8253679/130423067-f9ee4b2f-1454-4b1f-9782-37dc62741db0.png)

**next  will go 29k ok csv and html files**

![image](https://user-images.githubusercontent.com/8253679/130423309-cf7c5264-3900-4acc-a414-9cdec43c990d.png)

**Comment by wakaleo** [comment] 2021-08-23 09:25
Feels like a combinatorial explosion. Could you set serenity.compressed.filenames=false in your config file and see what gets generated? Also, what version of Serenity are you running?

**Comment by MichaelVovk** [comment] 2021-08-23 09:28
@wakaleo sure will try now. We are using 2.4.34 for Gradle

**Comment by xjc90s** [comment] 2021-08-23 09:36
Junit5 report + fluent assertion test load pad runner plaided or open
collective or Test Load 4k 4m te#t stress Park,lel, test Stress cnf.js test
load Jload or assertion junit5

**Comment by xjc90s** [comment] 2021-08-23 09:43
Assertion threads load test run ber 400j test suite packet. One"t

**Comment by xjc90s** [comment] 2021-08-23 09:45
Concept load testing inhertial verbose I'd,C's message value key pair, dict
grid paral'ledagre#ssive remote web drive= hub 4r4rr key assertion values
usual warp types

**Comment by xjc90s** [comment] 2021-08-23 09:50
Postman woman or Newman timestamp message verbose Postman agent web service
400 testsuit or 2020 testsuite balanced na r|response quiet silence
reporting to html test grahp QL

**Comment by wakaleo** [comment] 2021-08-23 09:56
@xjc90s I think you are posting to the wrong place.

**Comment by MichaelVovk** [comment] 2021-08-23 11:00
@wakaleo same result with serenity.compressed.filenames=false

**Comment by wakaleo** [comment] 2021-08-23 11:03
But the filenames should be different, so it might give an indication of what reports it is generating.

**Comment by MichaelVovk** [comment] 2021-08-23 12:14
![image](https://user-images.githubusercontent.com/8253679/130438099-bb6a6401-e5b3-4a35-a7e5-79a61a7c87fa.png)
Probably not working,

**Comment by globalworming** [comment] 2021-08-23 12:45
Just to make sure: please run `mvn clean verify` and check if it makes a difference

**Comment by MichaelVovk** [comment] 2021-08-24 10:17
@globalworming tried several times on different env. Names are still the same

**Comment by wakaleo** [comment] 2022-02-12 15:19
Presuming resolved in more recent Serenity versions. If you are still having this issue with version 3.2.0, please reopen this - if you can produce a sample project that reproduces the issues we can take a look.

**Closed by wakaleo** 2022-02-12 15:19 UTC
Labels: question

**Comment by aostad** [comment] 2024-01-16 22:07
Hi everyone,
Although this is an old question and probably you may found a workaround, I like to mention that I have encountered the same issue and posted my question/solution in the Serenity BDD group. I hope that the group is still active.

Anyhow here is my post in that group and hope it can help:

I just want to bring up an issue that I'm facing and share with you the workaround I'm using.

My project includes the above configuration. I have a test scenario with about 400 lines of test data in a table under "Examples:" section in the feature fille as depicted below:

Scenario Outline: Initiate payment with invalid data
Given all necessary variables are initialized
When Arya sends a request without "<missingFieldd>" in the payload
Then the error response has the expected "<errorCode>" and "<errorMsg>"
Examples:
| testCaseNumber | missingField | errrorCode | errorMsg |
| 001                         | firstName      | 400             | mandatory field first_name is required |
| 002                         | lastName      | 400             | mandatory field last_name is required |
....
| 400                          | amount         | 400             | mandatory field amount is required |


the execution time is reasonable and is done fast. After executing the last row (400), some processes started to generate reports. This step takes forever.

When the number of rows is a few the delay is not noticeable, however, when we have hundreds of them it takes hours. Sometimes the PC looks hung up due to the extreme delay in generating the report.

After debugging, I noticed Serenity goes through a long process after the last execution to retrieve data and generate files and links.

This issue makes the important feature of cucumber useless as you cannot have one test case with a considerable amount of rows of data in the table.

My Workaround:
for each row, simply repeat the steps by creating a new test case for each row. In other words, you may have a table of data with one row.

This simple change helps to generate the reports in a couple of minutes and saves you hours.

If you have experienced this issue please let me know. If you have a better solution, I'll be happy to hear it.

BTW, I have tried to update the project using a newer version of Serenity but encountered many compiling and dependency issues, so I gave up..

Cheers.
