### ISSUE TITLE
HTML Source button opens source as a text file rather than HTML

### ISSUE THREAD

**Issue by JamesYeoman** [serenity-bdd/serenity-core#1469] opened 2018-11-29 10:30 UTC
This is the HTML Source button that I'm talking about
![image](https://user-images.githubusercontent.com/21042602/49215420-ab6b3380-f3c0-11e8-9f0a-39c91f729ac4.png)

When I click on it, I expect a HTML file to open but instead, this happens.
![image](https://user-images.githubusercontent.com/21042602/49215442-b45c0500-f3c0-11e8-8cc0-57ee1baa250a.png)

This means that (essensially) have to download from myself, in order to rename the file to remove the txt extension, and then open the file.

**Comment by wakaleo** [comment] 2018-12-04 20:03
Which version of Serenity are you using?

**Comment by JamesYeoman** [comment] 2018-12-10 13:40
1.8.21

**Comment by wakaleo** [comment] 2018-12-10 13:42
Have you tried upgrading to 2.0.x? The reports have been redone, so the issue is probably no longer applicable.

**Comment by wakaleo** [comment] 2019-04-04 11:38
Presuming fixed in 2.0.x

**Closed by wakaleo** 2019-04-04 11:38 UTC
Labels: waiting for feedback
