### ISSUE TITLE
When i am creating an serenity maven project using mvn archetype: generate -dfilter=serernity its not able to configure POM.xml correctly 

### ISSUE THREAD

**Issue by vaseemhussain** [serenity-bdd/serenity-core#1917] opened 2020-01-15 02:26 UTC
The problem is it is downloading maven-fail-safe-plugin dependency from http://jcenter.bintray.com/org/apache/maven/plugins/maven-failsafe-plugin/2.22.1/maven-failsafe-plugin-2.22.1.pom.

As in the POM.xml the site address is given is http://jcenter.bintray.com which is getting me an error 
like this 
Authorization failed for http://jcenter.bintray.com/org/apache/maven/plugins/maven-failsafe-plugin/2.22.1/maven-failsafe-plugin-2.22.1.pom 403 Forbidden

I try to change the address by updating it to Https, it works as it downloads all the necessary dependencies but it breaks the Maven project.

Please help.

**Comment by wakaleo** [comment] 2020-01-15 06:33
403 forbidden sounds like a local network issue of some kind

**Comment by wakaleo** [comment] 2020-01-15 07:20
I can confirm this is not a Serenity issue - you need to make sure maven can access the public repos (or your local artifactory or nexus).

**Comment by ricardorlg-aval** [comment] 2020-01-15 15:01
the problem is that Jcenter is https only since Jan 13, make sure that u change Jcenter repository to use Https.

**Comment by phamhiepst** [comment] 2020-01-22 03:59
same here

**Comment by wakaleo** [comment] 2020-01-22 06:19
Change the bintray urls in the pom.xml to https. This will be fixed in the next release.

**Comment by vaseem78652** [comment] 2020-02-03 12:09
I have tried but updating bintray url to https in pom.xml is not helping as the pom.xml file would still show error

**Closed** 2022-02-12 15:10 UTC
Labels: works-as-intended
