### ISSUE TITLE
Serenity Rest Assured getting -1 value when measuring response time using getTime() or getTimeIn()

### ISSUE THREAD

**Issue by Hendrione** [serenity-bdd/serenity-core#1315] opened 2018-07-19 09:50 UTC
On rest assured version 2.8.0 or higher, it support us to measure response time by using method time() or timeIn() (please check: https://github.com/rest-assured/rest-assured/wiki/ReleaseNotes28). When I use given() method in net.serenitybdd.rest.SerenityRest.given or net.serenitybdd.rest.RestRequests.given, it always giving the response time -1. But when I use the given() method provided by rest assured (io.restassured.RestAssured.given), it gives me correct response time.

Here is my code:

```
long time = net.serenitybdd.rest.RestRequests.given()
.log().all().queryParam("page", 0)
.queryParam("size", 100)
.get("https://myproject.com/api/master/projects").timeIn(TimeUnit.MILLISECONDS);

long time2 = io.restassured.RestAssured.given()
.log().all().queryParam("page", 0)
.queryParam("size", 100)
.get("https:/myproject.com/api/master/projects").timeIn(TimeUnit.MILLISECONDS);

System.out.println("Using serenity given:"+time);
System.out.println("Using rest assured given:"+time2);
```
Here is my response:

```
Using serenity given:-1
Using rest assured given:985
```
I am getting struggle because without using given() on serenity library, the serenity report doesn't give the api report.

**Comment by wakaleo** [comment] 2018-07-19 09:52
Duplicate of #1309

**Comment by Hendrione** [comment] 2018-07-19 09:55
Why #1309 is closed. it needs to be fixed, right? is there any reason for this?

**Comment by wakaleo** [comment] 2018-07-19 09:55
It has been fixed in https://github.com/serenity-bdd/serenity-core/commit/26cf362d901f5ca74582c004aaae0511a9b13ae7.

**Comment by Hendrione** [comment] 2018-07-19 10:00
ok thanks @wakaleo

**Closed** 2018-07-20 06:30 UTC
