### ISSUE TITLE
Report cannot be filtered by Features and Stories

### ISSUE THREAD

**Issue by awallat** [serenity-bdd/serenity-core#102] opened 2015-08-05 08:27 UTC
When a report is generated, on the Overall Test Results Page, I can filter the results by Capabilities, but if I want to filter by Features or Stories then a 404-error is shown. The links to each single test case work however.

OS: Windows
Serenit-BDD-Version: 1.1.2

**Comment by wakaleo** [comment] 2015-08-05 08:59
Can you produce a sample project that reproduces this?

On 5 August 2015 at 09:27, André Wallat <notifications@github.com> wrote:

> When a report is generated, I can filter the results by Capabilities, but
> if I want to filter by Features or Stories then a 404-error is shown. The
> links to each single test case work however.
>
> OS: Windows
> Serenit-BDD-Version: 1.1.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/102>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by awallat** [comment] 2015-08-05 16:15
I found the problem. Because of an old "Story"-file, back when I was using jBehave, the report isn't generated correctly. Somehow this file seems to create a conflict. After removing the file, the report is generated correctly.

I created a sample project for this: https://github.com/awallat/serenity-bugs/tree/102-reportJBehave

**Comment by wakaleo** [comment] 2015-10-24 10:40
Does this happen if you use mvn clean verify to run the tests and generate the reports?

**Comment by awallat** [comment] 2015-10-27 13:12
We use "mvn clean test serenity:aggregate" to run the tests and create the reports afterwards.

**Comment by YamStranger** [comment] 2015-12-15 08:17
Hello @awallat, thanks for this issue!

I have just checked it. It works fine. 

There are some screenshots before and after sorting:

![image](https://cloud.githubusercontent.com/assets/1667699/11805455/5dbc7202-a314-11e5-81f9-827c141f95e0.png)

![image](https://cloud.githubusercontent.com/assets/1667699/11805463/6ab110ee-a314-11e5-879a-160a48448991.png)

![image](https://cloud.githubusercontent.com/assets/1667699/11805468/7558f336-a314-11e5-979c-7a11a21c2264.png)

![image](https://cloud.githubusercontent.com/assets/1667699/11805469/7ea691e6-a314-11e5-9f29-7bc2d9c05970.png)

Also when I filtering I see correct results:
![image](https://cloud.githubusercontent.com/assets/1667699/11805483/afa2a1fe-a314-11e5-941d-511389df90be.png)
![image](https://cloud.githubusercontent.com/assets/1667699/11805490/ba98d8a8-a314-11e5-8a6c-40b29a358c60.png)

It seems that all works fine.

I used last version of serenity, and [demo project](https://github.com/serenity-bdd/serenity-demos)

Please close this issue, because it seems that it was already fixed. 

Thanks a lot!

**Comment by awallat** [comment] 2015-12-15 15:30
Hello @YamStranger ,

the bug is still present in version 1.1.21. Please check out my sample project which reproduces this error. As described, the problem is on the "Overall Test Result"-page, when clicking on a feature. In the example project the feature "Search" leads to a 404-error.

Here's the link again: https://github.com/awallat/serenity-bugs/tree/102-reportJBehave

**Comment by wakaleo** [comment] 2015-12-15 16:55
Hi Andre,

Could you check with the latest 1.1.22 RC version?

Thanks

John

On 15 December 2015 at 16:30, André Wallat <notifications@github.com> wrote:

> Hello @YamStranger <https://github.com/YamStranger> ,
>
> the bug is still present in version 1.1.21. Please check out my sample
> project which reproduces this error. As described, the problem is on the
> "Overall Test Result"-page, when clicking on a feature. In the example
> project the feature "Search" leads to a 404-error.
>
> Here's the link again:
> https://github.com/awallat/serenity-bugs/tree/102-reportJBehave
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/102#issuecomment-164798794>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by YamStranger** [comment] 2015-12-16 06:32
Hi @awallat. 

I download your test, and updated version of serenity to last [1.1.22-rc.11](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.22-rc.11)

run command 
```
mvn clean verify
```
Here is screenshots before and after filtering: 
Overall test results - Test Count:
![image](https://cloud.githubusercontent.com/assets/1667699/11833781/d6d865c8-a3ce-11e5-98bc-f7a5fa7a1dfb.png)
![image](https://cloud.githubusercontent.com/assets/1667699/11833786/ddc475fc-a3ce-11e5-868e-9380f6f2e5dc.png)

Overall test results - weighted by test :
![image](https://cloud.githubusercontent.com/assets/1667699/11833802/179dd336-a3cf-11e5-8ba4-4ac6d7790fc2.png)

![image](https://cloud.githubusercontent.com/assets/1667699/11833807/2137aab6-a3cf-11e5-9ea2-61fc1cccc1b5.png)


Features:
![image](https://cloud.githubusercontent.com/assets/1667699/11833813/3521b134-a3cf-11e5-95f0-f61a3bd75747.png)
![image](https://cloud.githubusercontent.com/assets/1667699/11833818/3e77135a-a3cf-11e5-810d-91072fafe925.png)

Stories: 
![image](https://cloud.githubusercontent.com/assets/1667699/11833826/486e5274-a3cf-11e5-993f-1cacd76ca938.png)
![image](https://cloud.githubusercontent.com/assets/1667699/11833835/5655ff0e-a3cf-11e5-9691-c10338bfaf41.png)

@awallat all works fine. 

If you fill that this issue can not be reproduced with last version [1.1.22-rc.11](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.22-rc.11) and already fixed - please close this issue. 

If you have any questions, please be free to ask. 

Thanks a lot!

**Comment by awallat** [comment] 2015-12-16 11:17
I think we are talking about different things here. I attached a screenshot showing, which link leads to an error-page. The error still occurs under version 1.1.22-rc.11.
When clicking on that "Search"-link, the linked html page could not be found.

![serenity-errorlink](https://cloud.githubusercontent.com/assets/5612346/11839454/281ee3c0-a3ee-11e5-8e25-4b3af1e58d1f.PNG)

**Comment by YamStranger** [comment] 2015-12-16 11:24
@awallat Ok, now I see. 

Stories can be opened, and link under Search not exists. 

Thanks for this screenshot

**Comment by wakaleo** [comment] 2016-05-15 21:35
@awallat : your analysis of the problem is correct - the *.story file confuses Serenity as it looks for a JBehave requirements structure. For now, the simplest workaround is to stick to one type of test (JUnit or JBehave) for a given project.

**Comment by wakaleo** [comment] 2017-01-03 19:33
Fixed in 1.2.1-x

**Closed by wakaleo** 2017-01-03 19:33 UTC
Labels: bug
