### ISSUE TITLE
java.lang.NoSuchMethodError: org.openqa.selenium.json.JsonOutput.write(Ljava/lang/Object;Ljava/lang/reflect/Type;)

### ISSUE THREAD

**Issue by pankaj-sukale** [serenity-bdd/serenity-core#1328] opened 2018-08-06 18:58 UTC
Getting above error with Serenity latest version while launching browser.

https://stackoverflow.com/questions/51084484/java-lang-nosuchmethoderror-org-openqa-selenium-json-jsonoutput-writeljava-lan

The possible reason can be one of the following:

Presence of multiple Selenium related jars through selenium-server-standalone-3.13.0.jar and selenium-java-3.13.0 client jars.
Presence of multiple Selenium related jars through JARs and Maven and/or Gradle.
Presence of gson-2.8.2.jar as the Release Notes od Selenium v3.13.0 clearly mentions:
https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

 **Introduced our own JSON parser and outputter, allowing GSON to be removed from our dependencies.**

We have workaround in gradle to point selenium-server and selenium-java jar to selenium version 3.11.0
and gson version to latest.

Can we please add a fix in Serenity

**Comment by wakaleo** [comment] 2018-08-06 19:06
Help is welcome. I don’t have a fix at this stage. I have observed this issue but hasn’t isolated the cause (it doesn’t appear related to the gson version though as Serenity uses gson 2.8.5). The Selenium notes merely say that they don’t need gson, not that it needs to be removed from other projects. Downgrading selenium doesn’t seem a good option though (APIs change and updates are needed to support the latest browsers)

**Comment by pankaj-sukale** [comment] 2018-08-07 06:57
Thanks @wakaleo, can you please elaborate more on "APIs change and updates are needed to support the latest browsers" by API change you mean to say from Selenium side or some fix is required from Serenity.

If on selenium side then we need to wait for new selenium version with fix.

If on Serenity side then is there any ETA for this?

**Comment by wakaleo** [comment] 2018-08-07 07:05
I am looking into this, but at this stage no one has been able to isolate the cause of the issue, but it does seem to be selenium-related. Any help on your side isolating exactly what dependency changes trigger the issue would be very useful.

**Comment by pankaj-sukale** [comment] 2018-08-07 07:30
Thanks @wakaleo, as off now we have workaround. 
We will check on our end if any breakthrough will comment here.

**Comment by wakaleo** [comment] 2018-08-07 16:03
Fixed in 1.9.35

**Closed by wakaleo** 2018-08-07 16:03 UTC
Labels: help wanted

**Comment by pankaj-sukale** [comment] 2018-08-08 03:49
Thanks @wakaleo

**Comment by arthivigneshwari** [comment] 2019-07-22 08:20
> Help is welcome. I don’t have a fix at this stage. I have observed this issue but hasn’t isolated the cause (it doesn’t appear related to the gson version though as Serenity uses gson 2.8.4). The Selenium notes merely say that they don’t need gson, not that it needs to be removed from other projects. Downgrading selenium doesn’t seem a good option though (APIs change and updates are needed to support the latest browsers)

Am seeing this error in my project "java.lang.NoSuchMethodError: org.openqa.selenium.json.Json.toType(Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;"
Used selenium version: 3.11.0
testng version: 6.8.7
firefox version: 60.0
gecko version:0.20.0
Used jars:
testCompile 'org.seleniumhq.selenium:selenium-java:3.11.0' 
 testCompile 'org.seleniumhq.selenium:selenium-leg-rc:3.11.0'
can you please help me to resolve it?

**Comment by wakaleo** [comment] 2019-07-22 09:03
Are you using Serenity?

**Comment by arthivigneshwari** [comment] 2019-07-23 05:55
> Are you using Serenity?

Am not using serenity dependencies in my build.gradle file. 
Still hitting the issue and dint get fix. Any help is appreciated!

**Comment by wakaleo** [comment] 2019-07-23 08:18
It’s a dependency conflict; see https://docs.gradle.org/current/userguide/inspecting_dependencies.html
