### ISSUE TITLE
Multiple Jobs are created while running serenity acceptance tests in Sauce Labs

### ISSUE THREAD

**Issue by rajesht81** [serenity-bdd/serenity-core#209] opened 2015-11-26 19:02 UTC
This is a duplicate of issue #105  Since the original issue was closed (and hopefully the fix is not yet committed to trunk) I'm opening this

We recently faced a similar issue while running our serenity tests in Sauce Labs. Multiple jobs / SauceLabs VMs are created while running AcceptanceTestSuite in SauceLabs . As a result, the test gets executed in one saucelabs vm and the screenshot are taken from the duplicate VM which results in empty screenshot being shown in the final report

**Comment by YamStranger** [comment] 2015-11-27 08:20
Hello @rajesht81, thanks for this issue

form #105:
> I started with the serenity jbehave archetype, so I'm using my AcceptatnceTestSuite which extends SerenityStories to start my selenium tests.
The maven command I'm calling executing is : mvn clean verify -Dsaucelabs.url=http://xxxxx:xxxx-xxx-xxx-xxx@ondemand.saucelabs.com:80/wd/hub -Dsaucelabs.access.key=xxxx-xxxx-xxxx-xxxx -Dsaucelabs.user.idxxxxxx -Dwebdriver.base.url=https://www.xxxxxx.com -Dcapability.combination="{browserName:chrome, platform:Windows 8, version:44.0, build:${bamboo.branch.name}_${bamboo.buildNumber}}" -Dmaven.failsafe.debug=true
Whenever a screenshot will be made with the Photographer a new Driver is created which also triggers a new test/job in SauceLabs. So the end result is a Job which goes through my selenium scenario and another job which has taken empty screenshots ...
This only occurs in combination with a RemoteWebDriver, because when using my local chrome I do not have this behavior and screenshots are working correctly.

>We added our own EventListener and added
```
ThucydidesWebdriverManager.inThisTestThread().registerDriverCalled("remote").forDriver(driver);
```
This resulted into the same driver for executing tests and taking screenshots

**Comment by YamStranger** [comment] 2015-11-27 09:02
To reproduce this issue I used our demo project [junit-webtests](https://github.com/serenity-bdd/serenity-demos/tree/master/junit-webtests).
After I cloned it I replaced code (and it can be merged already) on this [line](https://github.com/serenity-bdd/serenity-demos/blob/master/junit-webtests/src/test/java/net/thucydides/showcase/junit/pages/ListingPage.java#L49) to
```
        double listingPrice = Double.parseDouble(price.getText().replaceAll("[^0-9.,]+",""));
``` 
Also I updated gradle build file to propagate system variables, I inserted [here](https://github.com/serenity-bdd/serenity-demos/blob/master/junit-webtests/build.gradle#L36) (and it should be merged already) next lines:
```
test {
    testLogging {
        showStandardStreams = true
    }
    /* Pass all system properties: */
    systemProperties System.getProperties()
}
```

Also I updated version of serenity bdd in this file to [v1.1.22-rc.10](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.22-rc.10) (and it should be merged already).

To take screenshots I updated DisplayProductDetailsTest class - replace one function:
```
    public void display_product_details_from_the_search_list() throws IOException, InterruptedException {
        Path path = Paths.get("/my/folder");
        Files.createDirectories(path);
        List<ScreenshotPhoto> photos = new ArrayList<>(3);

        Photographer photographer = new Photographer();
        buyer.opens_home_page();
        photos.add(photographer.takesAScreenshot()
            .with(driver)
            .andSaveToDirectory(path));

        buyer.searches_by_keyword("Docking station");
        photos.add(photographer.takesAScreenshot()
            .with(driver)
            .andSaveToDirectory(path));


        ListingItem selectedListingItem = buyer.selects_listing(1);

        buyer.should_see_product_details_for(selectedListingItem);
        photos.add(photographer.takesAScreenshot()
            .with(driver)
            .andSaveToDirectory(path));

        Thread.currentThread().sleep(5000); //screenshots are saved in different thread
        Assert.assertEquals(photos.size(), 3);
        for (ScreenshotPhoto photo : photos) {
            Assert.assertTrue(Files.exists(photo.getPathToScreenshot()));
        }
    }
```
now it should take 3 screenshots. 


After that I do next:

To run build only with one test next command was used (according manual [running_tests_on_saucelabs](http://thucydides.info/docs/serenity-staging/#_running_tests_on_saucelabs)):

```
gradle clean test -Dsaucelabs.target.platform=XP -Dwebdriver.driver=chrome -Dsaucelabs.driver.version=44 
-Dsaucelabs.url=http://MyUser:myKey @ondemand.saucelabs.com:80/wd/hub  
-Dsaucelabs.access.key=/MyUser:myKey -Dsaucelabs.user.id=MyUser 
-Dtest.single=DisplayProductDetailsTest --stacktrace aggregate 
```

On saucelabs I see only one job (I tried several times):
![image](https://cloud.githubusercontent.com/assets/1667699/11437346/c0a64a78-94f5-11e5-95ea-103af30ec6c5.png)

in my dir I see images: 
![image](https://cloud.githubusercontent.com/assets/1667699/11437362/dc2adb88-94f5-11e5-9134-e17c1304652c.png)

And serenity report: 
![image](https://cloud.githubusercontent.com/assets/1667699/11437391/025561c0-94f6-11e5-85fb-71bc2647219c.png)


@rajesht81 I can not reproduce your issue... 
Please check what version of serenity do you use. Also be sure that all system variables propagated to junit.

Please provide some examples, and we will help you ) 

Otherwise, if you feel that your issue fixed - please close this issue. 

Thanks a lot!

**Comment by rajesht81** [comment] 2015-11-29 23:03
Thanks very much for your response. I'm using the serenity v1.1.22-rc.9

The issue is that all the screenshot calls are going to the duplicate VM , while the tests gets executed properly in the first VM 

While I was debugging, I saw that the driverMap for remote driver has "null" value for proxieddriver and hence resulting in duplicate vm launch in sauce labs. 

Also If I don't use WebElementFacade in my page object , then i don't see this issue.

**Comment by YamStranger** [comment] 2015-11-29 23:38
Hello @rajesht81. 

I will try to reproduce it, for now I don't understand how (I posted my last try before). 

If you will provide your example - it will much faster. 

Thanks a lot!

**Comment by rajesht81** [comment] 2015-11-30 06:03
I was able to get the sauce labs working properly if I set the below params while running the tests

1. webdriver.driver=REMOTE
2. serenity.driver.capabilities = "browserName:chrome" (whatever browser that needs to be run on sauce labs)

Is this correct?

**Comment by YamStranger** [comment] 2015-11-30 08:36
According (manual)[http://thucydides.info/docs/serenity-staging/#_running_tests_on_saucelabs]  @rajesht81 It should work properly when you use @Managed driver as here [example](https://github.com/serenity-bdd/serenity-demos/blob/master/junit-webtests/src/test/java/net/thucydides/showcase/junit/features/display_product/DisplayProductDetailsTest.java) and provide such parameters: 
 - saucelabs.target.platform 
 - webdriver.driver
 - saucelabs.driver.version 
 - saucelabs.url=http://MyUser:myKey@ondemand.saucelabs.com:80/wd/hub  
 - saucelabs.access.key=/MyUser:myKey -Dsaucelabs.user.id=MyUser 

This way I tried in provided example in previous comment... I don't use there webdriver.driver=REMOTE, but it works correctly. In what place those example differ from your code?

**Comment by wakaleo** [comment] 2016-05-17 08:38
Hi @rajesht81, could you confirm if @YamStranger's suggestions work for you?

**Comment by YamStranger** [comment] 2016-06-06 19:59
it seem that problem already solved and this ticket can be closed.

**Closed by YamStranger** 2016-06-06 19:59 UTC
Labels: bug, waiting for feedback
