### ISSUE TITLE
Serenity Report empty; even the test case is passed

### ISSUE THREAD

**Issue by javvajiamani** [serenity-bdd/serenity-core#516] opened 2016-09-01 22:56 UTC
Hi,
Can someone help me in fixing this 

![serenity](https://cloud.githubusercontent.com/assets/21696038/18187209/f0f0a98a-7064-11e6-8f65-6d0585c93104.PNG)

**Comment by wakaleo** [comment] 2016-09-06 13:55
Duplicate of https://github.com/serenity-bdd/serenity-maven-plugin/issues/50

**Closed by wakaleo** 2016-09-06 13:55 UTC

**Comment by isolderea** [comment] 2018-03-13 07:18
This is closed but neither this or the duplicate have a solution to it.

Could you please provide a solution

**Comment by wakaleo** [comment] 2018-03-13 07:44
What version are you using?

**Comment by isolderea** [comment] 2018-03-13 07:54
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.8.3</serenity.version> 
        <serenity.maven.version>1.8.3</serenity.maven.version>
        <tags></tags>
    </properties>

**Comment by wakaleo** [comment] 2018-03-13 07:56
No idea, impossible to say from this little information. Possibly an incorrect directory structure, or no cases are actually executed. Try looking at he sample projects to see how yours is different.

**Comment by isolderea** [comment] 2018-03-13 07:58
I can post the whole pom here if needed.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>noa.tests</groupId>
    <artifactId>bookingprocesses</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Serenity project with JUnit and WebDriver</name>

     <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.8.3</serenity.version> 
        <serenity.maven.version>1.8.3</serenity.maven.version>
        <tags></tags>
    </properties>

    
    <repositories>
        <repository>
            <id>serenity</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>serenity</id>
            <name>bintray-plugins</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.12</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.3</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.1.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <parallel>classes</parallel>
                    <threadCount>5</threadCount>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                    <parallel>methods</parallel>     
                    <threadCount>2</threadCount>
                    <reuseForks>true</reuseForks>
                    <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                    <systemPropertyVariables>
                        <tags>${tags}</tags>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>1.1.25-rc.3</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by wakaleo** [comment] 2018-03-13 08:07
Try removing the dependency on serenity-core in the serenity plugin

**Comment by isolderea** [comment] 2018-03-13 08:12
Now the report is not empty anymore but the index html was not generated.

**Comment by wakaleo** [comment] 2018-03-13 08:19
This sounds like a basic usage issue, it would be a better question for the broader community on https://serenity-bdd.rocket.chat

**Comment by isolderea** [comment] 2018-03-13 08:21
Thank you for your help will create a user and ask there. All the best
