### ISSUE TITLE
Getting two output directories when trying to customize outputDirectory

### ISSUE THREAD

**Issue by c-mu** [serenity-bdd/serenity-core#130] opened 2015-09-23 09:07 UTC
I see the same issue as described in #63 when using the gradle plugin provided by Serenity. I can pass in the outputDirectory setting and Serenity picks it up, but it creates some of the output in the directory specified and some in the default (target/site/serenity).
I'm using 1.1.13 by the way.

**Comment by RobWin** [comment] 2015-10-22 08:08
+1

**Comment by klokovas** [comment] 2015-10-30 11:31
+ 1
The same problem here: https://github.com/serenity-bdd/serenity-maven-plugin/issues/11

**Comment by YamStranger** [comment] 2015-11-05 08:44
Hello @c-mu, @RobWin. Thanks for this issue. 

Please try last updates provided by #167 and #161 pulls (they should be available in [1.1.19](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.19)). It should work with configuration in selenium.properties, and other from official [manual](http://thucydides.info/docs/serenity-staging/#_serenity_system_properties_and_configuration). 

You can use as example of such configurations this [test resources](https://github.com/serenity-bdd/serenity-core/tree/master/serenity-gradle-plugin/src), this can be moved but you can try this [search](https://github.com/serenity-bdd/serenity-core/search?utf8=%E2%9C%93&q=serenity.outputDirectory%3D%22custom%2Fdirectory%22&type=Code). 

Thanks

**Comment by c-mu** [comment] 2015-11-13 10:32
Hi @YamStranger, I just retested with Serenity 1.1.22-rc.3. It is now better in so far that everything is generated in one location when using the serenity.outputDirectory property. Unfortunately it is not using the folder specified in the properties file, but the default (target/site/serenity).

**Comment by YamStranger** [comment] 2015-11-13 13:21
@c-mu thanks. For now it can be tested only manually, and I missed it. I will provide fix during next several hours, and will write you when it will be available in release.

**Comment by YamStranger** [comment] 2015-11-19 07:28
Hello @c-mu. 

Please try it under 1.1.22-rc.5. 
To get aggregated reports only under custom directory you should add to serenity.properites line 
````
serenity.outputDirectory=custom/directory
````
it will work, after 
```
gradle test .... aggregate
```

**Comment by c-mu** [comment] 2015-11-19 17:43
Hi @YamStranger ,
just retestet with 1.1.22-rc.7. I still get the results in target/site/serenity. :( Something changed though. In Gradle's build output I see the line
    Generating Serenity Reports for picocanyon to directory C:\Users\...\target\site\serenity
That used to be the directory specified as serenity.outputDirectory. After that however, I get a bunch of NoSuchFileExceptions (I think due to the fact that we are using just one runner class that covers all cucumber feature files) and these used to list the target/site/serenity folder, but now show build/reports/serenity, which is what I configured in serenity.properties.

One last thing, we intend to run Serenity tests in a delivery pipeline as functional validation. So the tests are invoked using binaries that were built in a previous job/stage. I wrote a separate gradle task of type Test to invoke the serenity test run. Any specifics I need to consider there?

**Comment by YamStranger** [comment] 2015-11-19 21:14
Hi @c-mu, I not sure what wrong. Lets make step by step, to be sure that we a talking about same things... 

Please help me investigate problem, because I can't reproduce it (or may be I am doing something different than you, or vice versa ).

We have demos projects, can you try run build with it please. 

1) Please checkout it: [git@github.com:serenity-bdd/serenity-demos.git](git@github.com:serenity-bdd/serenity-demos.git)
2) navigate to  junit-batch-configuration-example directory. Check that there is no "target" dir or custom dir.
3) update version of serenity in gradle.build in this directory:
```
repositories {
    mavenLocal()
    jcenter()
}

ext{
    serenity_version = "1.1.22-rc.7"
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.22-rc.7")
    }
}

apply plugin: "java"
apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "net.serenity-bdd.aggregator"

dependencies {
    compile localGroovy()
    compile "net.serenity-bdd:serenity-core:$serenity_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_version"
    compile("net.serenity-bdd:serenity-rest-assured:$serenity_version")
    compile 'org.slf4j:slf4j-simple:1.7.12'
    compile 'org.codehaus.groovy:groovy-all:2.3.10'
    compile 'junit:junit:4.12'
    compile 'com.googlecode.lambdaj:lambdaj:2.3.3'
    compile 'org.assertj:assertj-core:3.1.0'
}

test {
    testLogging {
        showStandardStreams = true
    }
    /* Pass all system properties: */
    systemProperties System.getProperties()
}

task copyDeps(type: Copy) {
    from configurations.runtime
    into project.projectDir.path+"/lib"
}

gradle.startParameter.continueOnFailure = true
```
so now we use same build
4)  this current dir update serenity.properties. Add line:
```
serenity.outputDirectory=custom/directory
```
 5) run in this dir next command
gradle clean test aggregate

After this build executed, all reports should be under custom/directory, and target directory should be absent.

**Comment by YamStranger** [comment] 2015-11-30 12:12
@c-mu It seems that I did not answered to your question
>One last thing, we intend to run Serenity tests in a delivery pipeline as functional validation. So the tests are invoked using binaries that were built in a previous job/stage. I wrote a separate gradle task of type Test to invoke the serenity test run. Any specifics I need to consider there?

Just be sure that all system variables propagated in test, if you use empty serenity.property file. 

For example, if you don't provide any values in serenity.property file, you should set them by providing them as system variables.

In demos project situation these lines are used:

```
test {
    /* Pass all system properties: */
    systemProperties System.getProperties()
}
```

And for run - just execute:
'''
gradle clean test aggregate -Dserenity.outputDirectory=custom/directory
'''
so it will run test and aggregate jobs and propagate to it system variable "serenity.outputDirectory" - all will work. 


@c-mu if you fill that this issue already fixed, and works properly (you can check it using demo projects) - please close this issue. 

Thanks a lot!

**Comment by c-mu** [comment] 2015-11-30 12:42
Hi YamStanger, sorry I have let this slide a little. I have just retested in my project using the systemProperties assignment as you laid out above. The results are almost poetic. It fixes the issue I still had with configuring PhantomJs (#136), but regarding the output dir it puts everything in the default dir. Just to be sure I will also use the demo project to retest as you suggested.

**Comment by YamStranger** [comment] 2015-12-03 09:17
Hello @c-mu. 

What about behaving for demo project?

**Comment by johndeverall** [comment] 2015-12-05 21:31
I'm also having this issue so if there is anything I can do to help please let me know :+1:

**Comment by YamStranger** [comment] 2015-12-06 01:16
Sure, @johndeverall 
Please try to build demo project as described in comment with phrase "e have demos projects, can you try run build with it plea". 

It should work, if all properties propagated to jUnit and serenity.properties contains correct values. 

Locally I receive correct output dir, but it seems that sometime something gone wrong - we should investigate this problem )

**Comment by johndeverall** [comment] 2015-12-06 11:38
@YamStranger I followed your instructions as you describe, and got the following results after executing `gradle clean test aggregate -Dserenity.outputDirectory=custom/directory`. 

1. All report files were included in /custom/directory
2. No target folder was created

So, it seems this is working. I'm curious why I can't get similar functionality working in my local project, but my local usage is slightly different so I'll play around a little more and if I can't see what's going on, raise another issue.

**Comment by YamStranger** [comment] 2015-12-06 14:27
Thanks a lot @johndeverall!!

**Comment by YamStranger** [comment] 2015-12-14 08:40
It seems that this issue can be closed. @johndeverall tested how it works, and it works as expected.

now reports can be configured with serenity.outputDirectory in gradle and all should be fine. 

Thanks.

**Closed by YamStranger** 2015-12-14 08:40 UTC

**Comment by themathmagician** [comment] 2016-12-20 16:31
Hey, solved it:
I had also `serenity.home` set in my serenity.properites file.
After removing the serenity.home property, the value of `serenity.outputDirectory`is picked up correctly.

There is still a bug though: 
if both serenity.home and serenity.outputDirectory is set with a non default value, then 2 report directories get created.

Best
Agata

**Comment by RemonSinnema** [comment] 2017-05-27 09:46
With version 1.2.4, `serenity.outputDirectory` is picked up by the `test` task, but not by `clearReports`, `aggregate`, and `checkOutcomes`.

I'm using this workaround in my `build.gradle`:
```
file('serenity.properties').withInputStream { input ->
  Injectors.getInjector().getProvider(EnvironmentVariables).get().getProperties().load(input)
}
```
