### ISSUE TITLE
With Serenity-core 4.0.11 and afterward versions supported Webdriver is failing 

### ISSUE THREAD

**Issue by RemyaAnoop** [serenity-bdd/serenity-core#3333] opened 2023-11-21 16:20 UTC
### What happened?

I am working on appium 2 upgrade for mobile test and as part of it, I wanted to update to serenity 4 version which has java client version 8 and above. 

When updated from 3.7.1 to 4.0.11, apply abstract method failed along with BeforeAWebdriverScenario . I updated import of BeforeAWebdriverScenario and it worked. But supported Webdriver argument in apply() method is still failing.

Analysis: 

under external libraries, I can see Supported WedDriver under net.Thucydides.core.Webdriver. SupportedWebDriver but it is not type enum. It is showing as SupporterWebDriver.class type. 

Attaching screenshots.

### What did you expect to happen?

Mobile test successfully run with serenity core 4.0.11 or after version.

### Serenity BDD version

4.0.11 or after

### JDK version

17

### How to reproduce the bug.

Update serenity-core to 4.0.11 or any version after and implement BeforeAWebdriverScenario. 
you will see SupportedWebDriver as red. 
in external library you can see as class file 

![IMG_0034](https://github.com/serenity-bdd/serenity-core/assets/123604127/bdd60c23-0b99-4b19-bda8-e51a3b394a66)

![IMG_0033](https://github.com/serenity-bdd/serenity-core/assets/123604127/8bd94e24-ab0c-494b-b1b1-3befa35f479d)
![IMG_0031](https://github.com/serenity-bdd/serenity-core/assets/123604127/9562752a-ae08-4a4e-a5c8-2e22e74cd1b7)

with 3.7.1 

![IMG_0032](https://github.com/serenity-bdd/serenity-core/assets/123604127/f646b886-cce9-43fd-bb49-326fc4448893)

### How can we make it happen?

Add it to the Serenity BDD backlog and wait for a volunteer to pick it up

**Comment by wakaleo** [comment] 2023-11-21 17:01
The SupportedWebDriver enum and BeforeAWebDriverScenario interface have not changed (an enum is a type of class). This looks like a Maven index or IDE issue, or a dependency conflict in your project.  If you need specific help updating your project we can do that as part of the commercial support packages (https://www.serenity-dojo.com/home1691753380236)

**Comment by RemyaAnoop** [comment] 2023-11-21 20:07
Let me try to run in other IDE and will confirm. Meanwhile @wakaleo  could you please provide me the path of TestOutcome. I’m trying to resolve this issue and getting couldn’t resolve TestOutcome since it is not under net.Thucydides.model.domain.TestOutcome. 

I only see Thucydides.core under package.

**Comment by wakaleo** [comment] 2023-11-21 20:21
Have a look at the 4.0.1 release notes

**Comment by RemyaAnoop** [comment] 2023-11-21 23:06
Thank you for your response @wakaleo 
When I checked with version 3.7.1 
Supported Webdriver is fine . 

![IMG_0032](https://github.com/serenity-bdd/serenity-core/assets/123604127/dc47e252-2ea5-4239-82ea-667a7f241ccb)


But with 4.0.11 it is showing as SupportedWebDriver.class under external dependencies. 

![IMG_0031](https://github.com/serenity-bdd/serenity-core/assets/123604127/feab1a6c-6ac8-4e13-b36b-3369d02f5a1c)


If it is issue with indexing, then for other versions as well we need to see .class extension right. 

Please help

**Comment by wakaleo** [comment] 2023-11-21 23:16
I'm not sure what to say, it's an enum in the source code. Try with 4.0.20 and rebuild your project.

**Comment by RemyaAnoop** [comment] 2023-11-24 15:42
I tried with Serenity 4.0.20 and I’m not seeing Serenity core under dependencies and libraries.

**Comment by wakaleo** [comment] 2023-11-24 18:14
Sorry, I meant 4.0.21

**Comment by RemyaAnoop** [comment] 2023-11-24 19:18
@wakaleo behavior is same for Serenity 4.0.22
I tried with version 4.0.8 and it is fine. From 4.0.9 this issue starts. So If someone can take a look that would be great.

**Comment by wakaleo** [comment] 2023-11-24 19:33
This is a problem with your Maven dependencies (maybe a corrupt repository), not with the Serenity libraries. If you continue having problems we can have a look at your specific project as part of one of the commercial support bundles (see http://serenity-dojo.com/corporate-support), but it is not related to the Serenity code.

(This is with version 4.0.24)
<img width="857" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/55986/246a5073-88d6-41b2-8f23-2d8cb69027d9">

<img width="369" alt="image" src="https://github.com/serenity-bdd/serenity-core/assets/55986/f89502ab-05fa-4035-bb0f-06ad614b1124">

**Comment by RemyaAnoop** [comment] 2023-11-24 19:42
@wakaleo we are using gradle. I am seeing issue for 4.0.24 as well. What should be the gradle version for Serenity core latest version? 
I will try from my end again. If not resolved, then will reach out to you.

**Comment by wakaleo** [comment] 2023-11-24 19:47
The Gradle plugin for 4.0.24 was published just now, so that should work.

**Comment by wakaleo** [comment] 2023-11-27 17:10
"java.lang.NoClassDefFoundError" is _always_ a dependency conflict.

**Comment by wakaleo** [comment] 2023-11-27 17:17
All the version numbers need to be the same, and the Configuration classes have moved (see https://github.com/serenity-bdd/serenity-core/blob/main/docs/release-notes/4.0.1.md)

**Comment by wakaleo** [comment] 2023-12-18 17:58
Closing presumed duplicate of #3340

**Closed by wakaleo** 2023-12-18 17:58 UTC
