### ISSUE TITLE
With the latest version of serenity-core, serenity reports are passing all the test cases even if they are failures. Failures are not noted in "Failing" count instead expections are recorded in Full Test Results under requirement 

### ISSUE THREAD

**Issue by nambikaas** [serenity-bdd/serenity-core#1966] opened 2020-02-20 11:26 UTC
pom.xml

<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<serenity.version>2.0.60</serenity.version>
<serenity.maven.version>2.0.60</serenity.maven.version>
<junit.version>4.12</junit.version>
<maven.failsafe.plugin.version>2.18</maven.failsafe.plugin.version>
<maven.compiler.plugin.version>3.2</maven.compiler.plugin.version>
<java.version>1.8</java.version>
Ran the test with @RunWith(SerenityParameterizedRunner.class) and have used soft assertions .How to rectify this ,pls let me know able to resolve this issue if we use <serenity.version>1.9.45</serenity.version>

**Comment by shbtechno** [comment] 2020-02-20 18:21
I am also facing the same issue #1964 with latest version 2.1.x and blocking me to prove the framework is stable and can be used further, until this is resolved can you help me with previous working version..
Team can you assist here urgently

**Comment by shbtechno** [comment] 2020-02-20 18:22
I am also getting the same issue with latest version 2.1.x #1964

**Comment by wakaleo** [comment] 2020-02-21 04:33
Duplicate of #1964

**Closed by wakaleo** 2020-02-21 04:33 UTC

**Comment by nambikaas** [comment] 2020-02-27 07:27
Able to fix this issue when used Serenity version 2.1.7... also the failing count were not part of the report because one of my steplibrary class were instantiated instead of just declaring which caused response validator library class/particular step to be not part of the serenity report ,which also made my report too look 100% passed inspite of the failures
. Eg : instead of declaring step library like below @steps
Validator validator; , i had previously instantiated it as @steps
Validator validator = new Validator(); <which is fine with some serenity versions but inlatest version this is not acceptable & class doesnt get part of serenity reports,thats why failing count was not counted> Thanks ,John
