### ISSUE TITLE
No screenshots captured upon test failure

### ISSUE THREAD

**Issue by skhandekar1** [serenity-bdd/serenity-core#2529] opened 2021-08-12 20:41 UTC
i have a very odd problem that I cannot seem to figure. 

I have the serenity.properties set to capture screenshots before and after each step and it is capturing fine when a test passes. But when a test fails, no screenshot is captured. We have testcases, each of which can have multiple Acceptance criterias and some test steps to get to the condition. When the test case is successful, the screenshots are correctly displayed for each step, but when the test case fails, no screenshots are displayed for steps within that test case that went through fine. Example - for a passing test case this is what I see:

`	@Title("TP397-019")
	@Test
	public void Test004()
	{
		//Title: Stimulation is restricted, when electrodes are not configured. 
		//Depends on: TP397-007 to open the created OR Session
		log.info("Test TP397-019");
		TP397_019.has(
			new AcceptanceCriteria("Error message is displayed indicating electrode needs to be assigned")
			.with(new ExpectedResult<String>("Anode not selected"))
		);

		//Tap RUN
		cpApp.Patient.Sessions.ORSession.TapRun();

		//Verification: Error message is displayed indicating electrode needs to be assigned.
		TP397_019.evaluateAC(cpApp.AlertMessage.getMessage());

		cpApp.AlertMessage.clickOnPositiveButton();
	    Assert.assertTrue(TP397_019.listACs(), TP397_019.result());
	}`

![image](https://user-images.githubusercontent.com/82490680/129266363-a4084dd6-b599-41e1-92cf-f406aed47df4.png)

but for a failure in the following test case where an element was not visible, that happened for the line shown in bold below, absolutely no screen shots were generated, though all the steps up until that point passed:

`@Title("TP397-015")
	@Test
	public void Test005()
	{
		//Title: Stimulation on ETM is enabled. 
		//Depends on: TP397-001 for OR Session creation.
		log.info("Test TP397-015");
		TP397_015.has(
			new AcceptanceCriteria("Stimulation is enabled (RUN button displays text \"Stop\")")
			.with(new ExpectedResult<String>("Stop")),

			new AcceptanceCriteria("Stimulation is enabled (Active ETM icon is displayed)")
			.with(new ExpectedResult<ETXstatus>(ETXstatus.Active)),

			new AcceptanceCriteria("During stimulation, Rate textbox is disabled.")
			.with(new ExpectedResult<Boolean>(true)),

			new AcceptanceCriteria("During stimulation, Pulse Width textbox is disabled.")
			.with(new ExpectedResult<Boolean>(true)),

			new AcceptanceCriteria("During stimulation, Amplitude textbox is disabled.")
			.with(new ExpectedResult<Boolean>(true))
		);

		if(patient_james.ClinicalIndication.equals("SCS")) {
			TP397_015.has(
				new AcceptanceCriteria("(OR Session) LEAD POSITION button is disabled")
				.with(new ExpectedResult<Boolean>(true))
			);
		}else{
			TP397_015.has(
				new AcceptanceCriteria("(OR Session) ADD AND MANAGE PHOTOS is disabled")
				.with(new ExpectedResult<Boolean>(true))
			);
		}
		
		TP397_015.has(
			new AcceptanceCriteria("CP Log shows Start Area Execution command followed by an ACK.")
			.with(new ExpectedResult<AckNakResponse>(AckNakResponse.ACK))
		);
		
		//Assign A1 as Anode and A2 as Cathode.
		ORScreen.isDisplayed();
		ORScreen.ElectrodeConfiguration.setElectrode(Electrode.A1, ElectrodeType.Anode);
		ORScreen.ElectrodeConfiguration.setElectrode(Electrode.A2, ElectrodeType.Cathode);

		//Tap RUN to stimulate the session.
		ORScreen.TapRun();
		cpApp.LoaderScreen.waitUntilLoaderDisappearsIfItAppeared(10);

		//Verification: Stimulation is enabled.
		TP397_015.evaluateAC(ORScreen.RunButton.getText());
		TP397_015.evaluateAC(cpApp.Patient.ActionBar.BlueETXIcon.getStatus());
		TP397_015.evaluateAC(!ORScreen.AreaParameters.Rate.isEditable());
		TP397_015.evaluateAC(!ORScreen.AreaParameters.PulseWidth.isEditable());
		TP397_015.evaluateAC(!ORScreen.AreaParameters.Amplitude.isEditable());

		if(patient_james.ClinicalIndication.equals("SCS"))  TP397_015.evaluateAC(!ORScreen.LeadPositionButton.isEnabled()); 
		**else    TP397_015.evaluateAC(!ORScreen.AddManagePhotosButton.isEnabled());**
		
		//View CP Log for Start Area Execution command.
		LogGetter logGetter = new LogGetter();
		logGetter.pullCPLogIntoFolder(TP397_015.testID);
		logGetter.runLogParser(LogParserVersion.v2_0_3_0);
		LogObserver logObserver = new LogObserver(logGetter.getCPio1Log(Equipment.ETM1));
		logObserver.lookFor(new StartAreaExecution());
		StartAreaExecution observedLogData = (StartAreaExecution)(logObserver.getLogEntry(0));	  

		//Verification: CP log indicates stimulation is enabled as indicated by the Start Area Execution command followed by an ACK.
		TP397_015.evaluateAC(observedLogData.getAckNakResponse());

	    Assert.assertTrue(TP397_015.listACs(), TP397_015.result());
	}`

![image](https://user-images.githubusercontent.com/82490680/129266613-bfdf35d0-c1e2-467b-b8b5-e171d69d629d.png)

Any idea why this happens and how to fix it? Since there is no screenshot, there is no way of knowing if the element was actually visible or not.

**Comment by wakaleo** [comment] 2021-08-12 21:10
What version are you using?

**Comment by skhandekar1** [comment] 2021-08-12 21:13
Serenity 2.2.0. Unfortunately I will not be able to upgrade this since I work in a medical device company and all our tools need to go through a formal upgrade test to show to FDA.

**Comment by skhandekar1** [comment] 2021-08-12 21:14
I am looking through the serenity-core code, to try and figure out at what class is the screenshots being captured, without much luck. Could you point me to that as well. Not sure what i will do with the info but it might be a good starting point to debug the issue.

**Comment by wakaleo** [comment] 2021-08-12 21:15
I can't reproduce this in the latest version so I suspect it was fixed around version 2.4.x

**Comment by skhandekar1** [comment] 2021-08-12 21:17
Is there any code I can add on my side as a workaround to this problem?

**Comment by wakaleo** [comment] 2021-08-12 21:17
If you can't upgrade try wrapping your assertions in a @Step-annotates method

**Comment by skhandekar1** [comment] 2021-08-12 21:19
Is there an example on how to do this?

**Comment by skhandekar1** [comment] 2021-08-12 21:21
Also another question about error log on console. I get only a part of the log as follows:

`***************************************************************
[TP397-015] Evaluating AC5: 
"During stimulation, Amplitude textbox is disabled."
***************************************************************

true*********************************************************************
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 166 appendAcceptanceCriteriaResultToCSV - 
**********************************************
Write TestCase result to ResultReport 
**********************************************

[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: TP-000397
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: TP397-015
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: During stimulation, Amplitude textbox is disabled.
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: true
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: Pass
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: 
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: 
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 292 appendToCSV - WRITE NEXT: [TP-000397, TP397-015, During stimulation, Amplitude textbox is disabled., true, Pass, , ]
[INFO ] 2021-08-11 18:03:43 framework.testWriting.ResultWriter.ResultWriterCSV 178 appendAcceptanceCriteriaResultToCSV - 

[main] ERROR  - 
___ ____ ____ ___    ____ ____ ____ ____ ____ 
 |  |___ [__   |     |___ |__/ |__/ |  | |__/ 
 |  |___ ___]  |     |___ |  \ |  \ |__| |  \ 
---------------------------------------------
TP397-015
-----------------------------------------------
**[main] ERROR  -     Timed out after 2 seconds. Element not found**
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 204 appendTestCaseResultToCSV - 
**********************************************
Write TestCase result to ResultReport 
**********************************************

[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: TP-000397
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: TP397-015_Completed
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: 
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: 
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: 
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: Not Tested
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 288 appendToCSV - StringArray: 
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 292 appendToCSV - WRITE NEXT: [TP-000397, TP397-015_Completed, , , , Not Tested, ]
[INFO ] 2021-08-11 18:03:46 framework.testWriting.ResultWriter.ResultWriterCSV 208 appendTestCaseResultToCSV - WRITE NEXT: [TP-000397, TP397-015_Completed, Not Tested]
[INFO ] 2021-08-11 18:03:46 com.nalumed.mobapp.Listeners.ExecutionListener 72 testFinished - 
***********************`

The log just says 'element' not found, but there is no info on what the element is or line number. for that I have to open Serenity Reports. Is there a way to make the error logs to be stack traces or more detailed?

**Comment by wakaleo** [comment] 2021-08-12 21:32
Not really; it might be better in recent versions but Selenium does not store locator information in the WebElements

**Comment by skhandekar1** [comment] 2021-08-12 21:44
As for this question - "I am looking through the serenity-core code, to try and figure out at what class is the screenshots being captured, without much luck. Could you point me to that as well. Not sure what i will do with the info but it might be a good starting point to debug the issue.", do you happen to know where the code might be? If not this issue can be closed. Thank you very much for your help...

**Comment by wakaleo** [comment] 2021-08-13 05:55
Add a method to one of your step libraries like this:
```
    @Step("Check that {0}")
    private void ensureThat(String message, Runnable assertion) {
        assertion.run();
    }
```

Then make your assertions like this:
```
        ensureThat("All is good", () -> assertThat(true).isFalse());
```

**Comment by skhandekar1** [comment] 2021-08-13 18:56
[framework.zip](https://github.com/serenity-bdd/serenity-core/files/6984631/framework.zip)
We have not used any assertions. Our methods just do simple actions. We have not complicated each method just so that the code is more visible on the top level. Attached the code. Also our top level code looks as follows:

`package com.tp.tp397_v2.Procedure1;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import framework.commonUtilities.TestEquipment;
import framework.commonUtilities.CPConfiguration.CPConfigManager;
import framework.testWriting.AcceptanceCriteria;
import framework.testWriting.ExpectedResult;
import framework.testWriting.NaluTestCase;
import framework.testWriting.NaluTestSection;

import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Title;
import net.thucydides.core.annotations.WithTag;
import net.thucydides.core.annotations.WithTags;

@RunWith(SerenityRunner.class)
@WithTags
(
		{
			@WithTag(type = "TP", name = "TP-000397"),
			@WithTag(type = "TP397", name = "Procedure1"),
			@WithTag(type = "TP397", name = "TP397_Procedure1_Section01"),
		}
)
public class TP397_Procedure1_Section01 extends NaluTestSection
{
	String TP_ID = "TP-000397";
	TestEquipment Equipment = new TestEquipment("TP397");
	NaluTestCase TP397_002 = new NaluTestCase("TP397-002", TP_ID);

	@Override
	public void beforeEachTest()
	{
		/*
		 * This section assumes Patient James exists in CP, and James has no IPG registered as Patient device yet.
		 */
		log.info("beforeEachTest called!");
		resultWriter.setTestProtocolID(TP_ID);

		//Add specific devices to bluetooth whitelist
		/* 
		 * This is done to minimize impact of too many devices in communication with CP, 
		 * thereby improving the response time of CP communication with appium
		 */
		CPConfigManager cpConfigManager = new CPConfigManager();
		cpConfigManager.configFileObject.setBluetoothWhiteList(Equipment.ETXDevices(Equipment.ETM1));
		cpConfigManager.pushConfigFileToTablet();
		
		//Login to CP, search and select patient James.
		cpApp.Login.Login("147258");
		cpApp.MyPatients.Search("James");
		
		cpApp.MyPatients.EnterFirstPatient();
		
		//Navigate to Devices tab and associate ETM device. Register IPG as Patient's device.
		cpApp.Patient.TapDevices();
		cpApp.Patient.Devices.SelectPermanent();
		cpApp.Patient.Devices.AssociateBlueETX(Equipment.ETM1);
		cpApp.LoaderScreen.waitUntilLoaderDisappears(20);
		cpApp.Patient.Devices.RegisterIPGasPatientDevice();
		
		//Navigate to Sessions tab and attempt to add a session.
		cpApp.Patient.TapSessions();
		cpApp.Patient.Sessions.AddSession();
	}

    @Title("TP397-002")
	@Test
	public void Test001()
	{
	    TP397_002.has(
	        new AcceptanceCriteria("Toast message appeared.")
	        .with(new ExpectedResult<Boolean>(true)),
	    		
	        new AcceptanceCriteria("Toast message indicates OR Session cannot be created.")
	        .with(new ExpectedResult<String>("Error: Patient doesn't have a lead assigned yet.")),
	        
	        new AcceptanceCriteria("OR Session is not created (CP screen remains on Sessions screen).")
	        .with(new ExpectedResult<Boolean>(true))
	    );
	    
	    //Select OR Session option.
	    cpApp.Patient.Sessions.ChooseORSession();
	    cpApp.ToastMessage.waitFor();
	    
	    //Verification: Application will prevent the user from creating OR Session when IPG and lead is not configured.
	    //				Check if toast message indicating OR Session could not be created appeared. 
	    TP397_002.evaluateAC(cpApp.ToastMessage.isDisplayed());
	    TP397_002.evaluateAC(cpApp.ToastMessage.getText());
	    
	    TP397_002.evaluateAC(cpApp.Patient.waitForVisibilityOf(cpApp.Patient.sessionsTab, "sessionsTab"));
	    Assert.assertTrue(TP397_002.listACs() , TP397_002.result());
	}
}
`

So will your method still be applicable in my case?

**Comment by wakaleo** [comment] 2021-08-13 19:50
Try it and see

**Comment by wakaleo** [comment] 2021-08-29 08:36
Closing presumed resolved.

**Closed by wakaleo** 2021-08-29 08:36 UTC
