### ISSUE TITLE
Webdriver initialization dropped after Selnium 2 to 3 update

### ISSUE THREAD

**Issue by nkalgin** [serenity-bdd/serenity-core#754] opened 2017-04-07 10:49 UTC
All Serenity and selenium dependencyes updatet to latest versions:

webdriver.driver=chrome
System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromewebdriver.exe");
System.setProperty("webdriver.gecko.driver", "src/test/resources/drivers/geckodriver.exe");

after importing net.thucydides.core.steps.ScenarioSteps
and getDriver().get(url);

allways have an error:

```
net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.os.**CommandLine.find**(Ljava/lang/String;)Ljava/lang/String;

	at net.serenitybdd.core.webdriver.servicepools.DriverServiceExecutable.asAFile(DriverServiceExecutable.java:90)
	at net.serenitybdd.core.webdriver.servicepools.GeckoDriverServiceExecutable.geckoBinaryCalled(GeckoDriverServiceExecutable.java:38)
	at net.serenitybdd.core.webdriver.servicepools.GeckoDriverServiceExecutable.executablePath(GeckoDriverServiceExecutable.java:24)
	at net.serenitybdd.core.webdriver.servicepools.GeckoDriverServiceExecutable.inEnvironment(GeckoDriverServiceExecutable.java:20)
	at net.serenitybdd.core.webdriver.servicepools.GeckoServicePool.configureGeckoDriverBinaries(GeckoServicePool.java:38)
	at net.serenitybdd.core.webdriver.servicepools.GeckoServicePool.<init>(GeckoServicePool.java:29)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.<init>(FirefoxDriverProvider.java:29)
	at net.thucydides.core.webdriver.WebDriverFactory.driverProviders(WebDriverFactory.java:102)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:126)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:135)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:105)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:180)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:175)
	at cucumber.steps.NavigationSteps.opens_web_page(NavigationSteps.java:19)
```

I don't understand, why it trying to use geckodriver, when I set chrome.
Swithcing appears in that place:

```
 private Map<SupportedWebDriver, DriverProvider> driverProviders() {

        if (driverProvidersByDriverType == null) {
            driverProvidersByDriverType = Maps.newHashMap();

            CapabilityEnhancer enhancer = new CapabilityEnhancer(environmentVariables, fixtureProviderService);

            driverProvidersByDriverType.put(SupportedWebDriver.APPIUM, new AppiumDriverProvider(environmentVariables, enhancer));
            driverProvidersByDriverType.put(SupportedWebDriver.REMOTE, new RemoteDriverProvider(environmentVariables, enhancer));
            **driverProvidersByDriverType.put(SupportedWebDriver.FIREFOX, new FirefoxDriverProvider(environmentVariables, enhancer));**
            driverProvidersByDriverType.put(SupportedWebDriver.HTMLUNIT, new HtmlDriverProvider(environmentVariables, enhancer));
            driverProvidersByDriverType.put(SupportedWebDriver.PHANTOMJS, new PhantomJSDriverProvider(environmentVariables, enhancer));
            driverProvidersByDriverType.put(SupportedWebDriver.CHROME, new ChromeDriverProvider(environmentVariables, enhancer));
            driverProvidersByDriverType.put(SupportedWebDriver.SAFARI, new SafariDriverProvider(environmentVariables, enhancer));
            driverProvidersByDriverType.put(SupportedWebDriver.IEXPLORER, new InternetExplorerDriverProvider(environmentVariables, enhancer));
            driverProvidersByDriverType.put(SupportedWebDriver.EDGE, new EdgeDriverProvider(environmentVariables, enhancer));
            driverProvidersByDriverType.put(SupportedWebDriver.PROVIDED, new ProvidedDriverProvider(environmentVariables, enhancer));

        }
        return driverProvidersByDriverType;
    }
```

And, why it still use depricated CommandLine.find method?

**Comment by wakaleo** [comment] 2017-04-07 10:54
Possibly a duplicate of #751. Pull requests are welcome.

**Comment by nkalgin** [comment] 2017-04-07 11:45
Yes, and all requred dependencies was updated:
` 
 <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>1.2.4</version>
        </dependency>
 <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>1.1.28</version>
        </dependency>

<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>3.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>21.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-firefox-driver</artifactId>
            <version>3.3.1</version>
        </dependency>`

**Comment by wakaleo** [comment] 2017-04-07 13:46
Closing this as Selenium 3 is not officially supported by Serenity yet.

**Closed by wakaleo** 2017-04-07 13:46 UTC
