### ISSUE TITLE
Serenity 1.4.1-rc.6 keeps browser opened but restarts session for each @test

### ISSUE THREAD

**Issue by IgorJoin** [serenity-bdd/serenity-core#824] opened 2017-06-14 21:14 UTC
Hello,

I'm using Serenity with JUnit.

I'm using a default webdriver (Firefox) with uniqueSession = true.  For each @Test in my test class, Serenity resets the browser session even keeping the browser opened. Shouldn't it keep the session for the entire test class execution?

**Comment by wakaleo** [comment] 2017-06-14 21:36
Duplicate of #819

**Closed by wakaleo** 2017-06-14 21:36 UTC
