### ISSUE TITLE
Gradle build is not compilable with version 2.0.5 

### ISSUE THREAD

**Issue by ilzul** [serenity-bdd/serenity-core#1407] opened 2018-10-13 19:07 UTC
Hello,
After switching to new version 2.0.5, gradle build becomes not compilable.
The following error occurs:

> Could not set unknown property 'reportDirectory' for task ':checkOutcomes' of type org.gradle.api.DefaultTask.

Could you please suggest how to fix that?

**Comment by wakaleo** [comment] 2018-10-13 19:08
It looks like a regression introduced by a PR - I'll roll it back.

**Comment by wakaleo** [comment] 2018-10-13 19:19
Fixed in 2.0.6

**Comment by ilzul** [comment] 2018-10-13 19:19
Thank a lot!

**Closed by wakaleo** 2018-10-13 19:18 UTC
