### ISSUE TITLE
Steps disappear in the report

### ISSUE THREAD

**Issue by vuthelinh** [serenity-bdd/serenity-core#1010] opened 2017-11-08 02:06 UTC
This is setup in the pom.xml
```
<serenity.version>1.6.9</serenity.version>
<serenity.cucumber.version>1.5.17</serenity.cucumber.version>
```

but in the report html shows Serenity BDD version 1.5.1 and the Steps is disappear

![corebug](https://user-images.githubusercontent.com/983936/32528152-53fe6722-c46c-11e7-838f-04f8962b2230.JPG)

**Comment by wakaleo** [comment] 2017-11-08 08:00
Duplicate of https://github.com/serenity-bdd/serenity-cucumber/issues/101

**Closed by wakaleo** 2017-11-08 08:00 UTC
