### ISSUE TITLE
In case of flaky tests, when tests are rerun, aggregated reports does not show all test results 

### ISSUE THREAD

**Issue by dhaneshkhot** [serenity-bdd/serenity-core#3465] opened 2024-05-09 13:25 UTC
### What happened?

On the console we can see correct total number of tests ran, e.g.
`[WARNING] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Flakes: 10
`

However,  serenity aggregated report don't have all test results, e.g.
`[INFO] Test results for 3 tests generated in 2.1 secs in directory: file:/home/dhanesh/Documents/Development/serenity-cucumber-starter-master/target/site/serenity/
[INFO] ------------------------------------------------
[INFO] | SERENITY TESTS:               | SUCCESS
[INFO] ------------------------------------------------
[INFO] | Test scenarios executed       | 3
[INFO] | Total Test cases executed     | 3
[INFO] | Tests passed                  | 3
[INFO] | Tests failed                  | 0
[INFO] | Tests with errors             | 0
[INFO] | Tests compromised             | 0
[INFO] | Tests aborted                 | 0
[INFO] | Tests pending                 | 0
[INFO] | Tests ignored/skipped         | 0
[INFO] ------------------------------- | --------------
[INFO] | Total Duration| 189ms
[INFO] | Fastest test took| 033ms
[INFO] | Slowest test took| 095ms
`

### What did you expect to happen?

The aggregated Serenity test report should have correct final result of the tests.

### Serenity BDD version

4.1.10

### JDK version

17

### Execution environment

I reckon OS does not matter. Observed this on Mac OS and Fedora OS (40).

### How to reproduce the bug.

Reproduced the issue with `serenity-cucumber-starter-master` project with some changes.

Note: In the final assertion of each tests in feature files, added random boolean assertion in order to make tests flaky.

[serenity-cucumber-starter-master.zip](https://github.com/serenity-bdd/serenity-core/files/15262767/serenity-cucumber-starter-master.zip)

Running `mvn clean verify` in above sample project would do the job to reproduce issue.

### How can we make it happen?

Work on this myself and propose a PR (with Serenity BDD team guidance)

**Comment by wakaleo** [comment] 2024-05-09 14:08
Have you tried with the latest version?

**Comment by dhaneshkhot** [comment] 2024-05-09 14:29
Just checked with latest version of Serenity and the issue is still there.
Also updated the version in the description.

**Comment by wakaleo** [comment] 2024-05-09 14:36
Serenity isn't aware of rerun tests, it will just take the last value most likely

**Comment by dhaneshkhot** [comment] 2024-05-09 18:47
Not sure of that yet. Even with rerun count 0, and with only 1 feature file, results are weird. Not sure if the was because of re-runs anymore.

Refer to below attachment.
[Uploading serenity-cucumber-starter-master.zip…]()

**Comment by wakaleo** [comment] 2024-05-10 07:31
I can reproduce this with your sample but have no idea why it behaves that way. It seems to override the JSON output file, so that might be a good place to start - it writes the results to the same JSON file each time, so maybe the algorithm for calculating the JSON filename (which is a hash of the feature file path and scenario name is not producing a unique value each time.

**Comment by dhaneshkhot** [comment] 2024-05-10 17:24
Initially I suspected that too but now it looks like in case of failed tests, results are not aggregated correctly even in single run.
Tested with only 1 feature without re-run. Hence, at the moment I'm clueless too!

I'll try to investigate further whenever possible. Any pointers from community members would be helpful.

**Comment by wakaleo** [comment] 2024-05-10 17:31
I've never come across this before even with different kinds of failing tests so it doesn't seem to be a general issue.

**Comment by wakaleo** [comment] 2024-05-12 07:37
Can you try with version 4.1.11?

**Comment by dhaneshkhot** [comment] 2024-05-12 09:31
This is awesome! Thank you very much!
I can confirm on shared starter demo project, issue seems to have been resolved.
I'll check again on actual project tomorrow and update here.

**Comment by wakaleo** [comment] 2024-05-12 13:36
The root cause was a missing JUnit dependency, but the root root cause was an exception not being thrown in the right place when that happens which broke the reporting. Both should be fixed in 4.1.12.

**Comment by wakaleo** [comment] 2024-05-19 08:50
Fixed in 4.1.12

**Closed by wakaleo** 2024-05-19 08:50 UTC

**Comment by dhaneshkhot** [comment] 2024-05-22 20:15
I confirm the issue has been fixed.
