### ISSUE TITLE
No index.html in target/site/serenity

### ISSUE THREAD

**Issue by derTobsch** [serenity-bdd/serenity-core#83] opened 2015-06-25 10:33 UTC
This is a part of my maven pom. The report is generated absolute ok. But there is no index.html in the serenity directory. Did i miss anything or is it just a bug?

i looked at https://github.com/serenity-bdd/serenity-demos/blob/master/junit-webtests/pom.xml but found nothing i could use.

```
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>2.8</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>index</report>
                            <report>summary</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>

<plugins>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity-maven.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
</plugins>
```

the target/site/serenity does look like this after mvn verify site
<pre>
.
├── bootstrap
├── browser-remote.properties
├── css
├── datatables
├── dygraph
├── eebc91ccd7458dc01175a55cf7025f55cf726fe0bad1739da0445a1d94f6c3f5.html
├── eebc91ccd7458dc01175a55cf7025f55cf726fe0bad1739da0445a1d94f6c3f5.json
├── eebc91ccd7458dc01175a55cf7025f55cf726fe0bad1739da0445a1d94f6c3f5.xml
├── excanvas
├── favicon.ico
├── font-awesome
├── images
├── jit
├── jqplot
├── jqtree
├── jqueryui
├── nivo-slider
├── scripts
└── SERENITY-JUNIT-eebc91ccd7458dc01175a55cf7025f55cf726fe0bad1739da0445a1d94f6c3f5.xml
</pre>

**Comment by derTobsch** [comment] 2015-06-25 12:31
it does work with your demos at serenity-bdd/serenity-demos and junt. I will try to look up my failure.

**Comment by derTobsch** [comment] 2015-06-25 12:59
fixed it.

**Comment by rrussell39** [comment] 2015-07-10 17:23
I'm seeing this same issue when we updated from 1.0.47 to 1.0.59.  Can you explain what the problem is exactly?  We didn't change anything else in our configuration - passed parameters or otherwise.

**Comment by rrussell39** [comment] 2015-07-10 20:09
This might be helpful to others as it explained our problem: https://github.com/serenity-bdd/serenity-maven-plugin/issues/9

**Comment by derTobsch** [comment] 2015-07-11 11:20
@rrussell39 i will take a look at that on Monday.

**Comment by hypery2k** [comment] 2015-07-28 22:42
would be great if this can be fixed

**Comment by derTobsch** [comment] 2015-07-29 07:40
i think the problem is, that i used mvn clean test instead of mvn clean verify. I just used verify and everything worked fine. :-)

**Comment by wakaleo** [comment] 2015-07-30 06:10
Thanks for the update, I'll close this now.

**Closed by wakaleo** 2015-07-30 06:10 UTC
