### ISSUE TITLE
 Unable to extract body as class with SerenityRest

### ISSUE THREAD

**Issue by bassmake** [serenity-bdd/serenity-core#242] opened 2016-01-04 14:10 UTC
after sending request we want to extract body and map it to a java class
```
      .then()
      .statusCode(HttpStatus.SC_OK)
      .extract()
      .body()
      .as(SomeClass.class, ObjectMapperType.GSON);
```
but in `SerenityRest` you are doing some magic for pretty print and after that we receive String that is no longer valid json. Especially when there is multiline xml as value.

**Comment by bassmake** [comment] 2016-01-19 08:25
The problem is with `com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.prettyPrint`.
I would like to help with this issue, but I honestly wasn't able to find solutions. Any ideas here?

**Comment by YamStranger** [comment] 2016-01-19 08:39
Thanks @bassmake!!! We have several issues with rest assurance, and all have some root cause - it will be fixed soon.  Idea of fix - change rest assurance to stop using bytecode manipulation library or restrict usage of it (because rest.assured use groovy in some classes) and implement wrappers for methods - and returned classes.

**Comment by wakaleo** [comment] 2016-05-17 08:31
Hi @bassmake; there have been a lot of updates to the REST support in version 1.1.32-rc.2, could you confirm if you are still getting this issue?

**Comment by YamStranger** [comment] 2016-06-06 20:00
It seems that this issue already solved, and this ticket can be closed.

**Closed by YamStranger** 2016-06-06 20:00 UTC
Labels: bug, waiting for feedback

**Comment by bassmake** [comment] 2016-06-06 20:32
ok, lets close it
