### ISSUE TITLE
NoBaseStepListener has been registered

### ISSUE THREAD

**Issue by chiragghai** [serenity-bdd/serenity-core#1222] opened 2018-04-25 13:58 UTC
Hi @wakaleo, I am using the following compatibility after I found someone got it working fine.
Firefox -59.0
selenium-3.11.0
geckodriver -0.20.0
and in build.gradle, I have used the following 
/***********Dependencies of Automation testing Start***************/
compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version:'3.11.0'
compile group: 'net.serenity-bdd', name: 'serenity-core', version: '1.9.10'
compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.11.0'
testCompile group: 'junit', name: 'junit', version: '4.12'
compile group: 'log4j', name: 'log4j', version:'1.2.17'
compile group: 'org.seleniumhq.selenium', name: 'selenium-api', version: '3.11.0'
compile group: 'org.seleniumhq.selenium', name: 'selenium-server-standalone', version: '2.53.0'

when I run it says NoBaseStep listener has been registered.
Please let me know which more dependencies I am missing ?

**Comment by wakaleo** [comment] 2018-04-25 16:06
I’ve seen his before but haven’t been able to reproduce it. It is one of the older libraries pulling in a Selenium 2 dependency, and Maven is failing to prioritise the dependencies correctly. Can you provide a  sample project?

**Comment by wakaleo** [comment] 2018-04-26 10:13
Can you create a sample project with the same dependencies that reproduces the issues? Issues like this depend on what other dependencies are in your projects.

**Comment by chiragghai** [comment] 2018-04-26 10:58
No more dependencies are used except those mentioned above.

**Comment by wakaleo** [comment] 2018-04-26 11:01
@chiragghai If you would like someone to spend time troubleshooting your issue, it is important to make it as easy as possible, otherwise it will never be picked up (open source projects have no SLA). The problem is a dependency conflict (https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html). From the pom.xml file alone, it is very hard to detect, so we need a fully working (albeit minimal) project that reproduces the issue.

**Closed** 2022-02-12 15:12 UTC
Labels: waiting for feedback
