### ISSUE TITLE
moveToElement() function doesn't work

### ISSUE THREAD

**Issue by pisarenco92** [serenity-bdd/serenity-core#852] opened 2017-07-24 14:57 UTC
I have updated Serenity to 1.5.3 but moveToElement(element) function doesn't work. Also I'm using the latest geckodriver version 0.18.0.

If I use: 
`withAction().moveToElement(find(By.xpath(selector))).click().perform();`
I get the following error: Unable to convert: {actions=[org.openqa.selenium.interactions.Sequence@538613b3]}

Also I tried with: 
 ```
Actions myAction = new Actions(getDriver());
 myAction.moveToElement(find(By.xpath(selector))).click().perform(); 
```
and get: ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: mouseMoveTo

**Comment by wakaleo** [comment] 2017-07-24 17:29
This sounds like a driver issue (Serenity simply calls the WebDriver API, and the "Unable to convert: {actions=[org.openqa.selenium.interactions.Sequence@538613b3]}" error message is a Selenium error. Try seeing if it happens with chrome.

**Comment by pisarenco92** [comment] 2017-07-24 20:07
Hi John,

I have tried with chrome and moveToElement()  works.

Also I have created a simple project without Serenity and moveToElement() method works well with Firefox.

Thanks

**Comment by wakaleo** [comment] 2017-07-24 20:09
Is your test with Firefox using the geckodriver?

**Comment by pisarenco92** [comment] 2017-07-24 20:10
Yes, it using geckodriver.

**Comment by wakaleo** [comment] 2017-07-24 20:17
Try stepping into the Serenity code to see how it compares with your code

**Comment by pisarenco92** [comment] 2017-07-26 21:11
Hi John,
I have investigated and I can't understand what is the problem. I have created a simple project 
[serenity.zip](https://github.com/serenity-bdd/serenity-core/files/1178069/serenity.zip). Could you please take a look when you have a free time?
Thanks.

**Comment by cliviu** [comment] 2017-07-27 11:09
Hi @pisarenco92 , I'm also not sure what the problem is. Can you please check the output of the gecko driver for each execution (with/without) serenity  ? In my case there are two different firefox executables started 👍 
1501153227741	geckodriver	INFO	geckodriver 0.18.0
1501153227746	geckodriver	INFO	Listening on 127.0.0.1:28677
1501153228467	geckodriver::marionette	INFO	Starting browser **/usr/bin/firefox** with args ["-marionette"]

1501153319373	geckodriver	INFO	geckodriver 0.18.0
1501153319377	geckodriver	INFO	Listening on 127.0.0.1:1080
1501153319773	geckodriver::marionette	INFO	Starting browser **/usr/lib64/firefox/firefox** with args ["-marionette"]

**Comment by pisarenco92** [comment] 2017-07-27 12:46
Hi @cliviu, 
Without Serenity:
```
1501159214869	geckodriver	INFO	geckodriver 0.18.0
1501159214876	geckodriver	INFO	Listening on 127.0.0.1:12486
1501159215192	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1501159217333	Marionette	INFO	Listening on port 54051
1501159217604	Marionette	DEBUG	loaded listener.js
Jul 27, 2017 3:40:17 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-07-27 15:40:17.678 plugin-container[19769:1379543] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9c3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-07-27 15:40:17.681 plugin-container[19769:1379543] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9f03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1501159217690	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1501159219071	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1501159219071	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1501159220657	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://johnfergusonsmart.com/"
1501159220661	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483653"
1501159221528	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.youtube.com/embed/YxiTTncewSY?"
1501159221691	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483656"
1501159221737	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.youtube.com/embed/YxiTTncewSY?"
1501159221759	Marionette	DEBUG	Received DOM event "pageshow" for "https://johnfergusonsmart.com/"
```

With Serenity:
```
[main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
1501159366181	geckodriver	INFO	geckodriver 0.18.0
1501159366185	geckodriver	INFO	Listening on 127.0.0.1:14612
1501159366535	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1501159368373	Marionette	INFO	Listening on port 54876
1501159368426	Marionette	WARN	TLS certificate errors will be ignored for this session
1501159368647	Marionette	DEBUG	loaded listener.js
Jul 27, 2017 3:42:48 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-07-27 15:42:48.723 plugin-container[19781:1381552] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9c37, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-07-27 15:42:48.725 plugin-container[19781:1381552] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9f03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1501159368734	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1501159371041	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1501159371041	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1501159372618	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://johnfergusonsmart.com/"
1501159372626	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483653"
1501159373400	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.youtube.com/embed/YxiTTncewSY?"
1501159373592	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483656"
1501159373600	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.youtube.com/embed/YxiTTncewSY?"
1501159373728	Marionette	DEBUG	Received DOM event "pageshow" for "https://johnfergusonsmart.com/"
2017-07-27 15:42:56.392 firefox-bin[19780:1381420] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x1267081c0 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}, com.apple.inputmethod.EmojiFunctionRowItem
[main] ERROR net.serenitybdd.core.Serenity - 
```
Thanks.

**Comment by cliviu** [comment] 2017-07-29 22:10
hi @pisarenco92 . I describe you the actual status : if you want the FirefoxDriver to be used by serenity internally, you have to set the property **use.gecko.driver=false**. If you have the Gecko driver in classpath and the property webdriver.gecko.driver set and the gecko driver is not disabled by property, a Marionette RemoteWebDriver will be created. This is the difference between the two tests that you have posted. In order to behave the same you should have had instantiated a RemoteWebDriver in your "WithoutSerenityTest". 
The actual problem is that the RemoteWebDriver cannot deal with moveMouseTo() seeeventually this issue : https://github.com/SeleniumHQ/selenium/issues/4008

**Comment by pisarenco92** [comment] 2017-08-01 08:25
hi @cliviu Thanks a lot for the explanation. 
Is it possible in SERENITY  not to instantiate RemoteWebdriver?

**Comment by wakaleo** [comment] 2017-08-01 11:57
The FirefoxDriver is being replaced by the Marionette gecko driver; the only way to use the later version of Firefox is with the RemoteWebDriver.

**Comment by wakaleo** [comment] 2017-08-01 11:58
Closing this issue as it is a WebDriver bug (see https://github.com/SeleniumHQ/selenium/issues/3808)

**Closed by wakaleo** 2017-08-01 11:58 UTC
Labels: waiting for feedback
