### ISSUE TITLE
error: package net.thucydides.core.guice does not exist : Work Around for this. 

### ISSUE THREAD

**Issue by GauravTyagi007** [serenity-bdd/serenity-core#3226] opened 2023-08-16 10:38 UTC
error: package net.thucydides.core.guice does not exist
import net.thucydides.core.guice.Injectors;  

Can You provide a Work around this

**Comment by wakaleo** [comment] 2023-08-17 07:12
Duplicate of #3206

**Closed by wakaleo** 2023-08-17 07:12 UTC
