### ISSUE TITLE
Serenity Report Taking very long for UI test

### ISSUE THREAD

**Issue by MadhuChatterjee** [serenity-bdd/serenity-core#2633] opened 2021-12-09 10:45 UTC
I am running UI automation test with Serenity and Cucumber for one test scenario with 40 data under scenario outline examples. Test run is completed in 1minute but the report generation is taking 1 hour over. How can I solve this? Is there a way to reduce the report generation time for web tests like this? @wakaleo

**Comment by wakaleo** [comment] 2021-12-09 10:56
What version are you using?

**Comment by MadhuChatterjee** [comment] 2021-12-09 13:26
@wakaleo I am using below versions:
 <serenity.version>3.1.1</serenity.version>
    <cucumber.version>6.11.0</cucumber.version>

**Comment by wakaleo** [comment] 2021-12-09 13:30
Do you have many different tags?

**Comment by MadhuChatterjee** [comment] 2021-12-09 13:48
We are executing the test under @smoke take but I am not sure if you mean that. Do you want to know if what other tags we have for cucumber?

**Comment by wakaleo** [comment] 2021-12-09 14:14
Try witth 3.1.5

**Comment by MadhuChatterjee** [comment] 2021-12-14 13:32
Hi @wakaleo, I have updated the Serenity and I tried dividing examples in 5 scenarios instead of putting all of them together in one. Report generation time has reduced. I also tried parallel testing with 3 forks. Just wanted to know, the clock time is reduced for the parallel tests with 3 forks than what it is for sequential but the total execution time for parallel tests are higher than sequential. Is that a desired result? I understand total execution time takes account of all the threads and adds them, just wanted to ensure if my understanding is right?

**Comment by wakaleo** [comment] 2021-12-14 15:04
I don't think the report generation time should be affected by the number of scenarios - it's more related to the number of tags. That is addressed by the most recent version of Serenity. Report generation time is not related to parallel exeution. Yes, total execution time for parallel execution will be higher than sequential because of the overhead associated with parallel tests.

**Comment by MadhuChatterjee** [comment] 2021-12-14 15:46
@wakaleo Thanks. But I am using just one tag and updated version of Serenity (note: not using screenplay, just serenity core) and 38 examples in one scenario took 1.12 hours to generate report, whereas dividing them in smaller parts in multiple scenarios took just 12 minutes to generate report. I did not get any justification for this as well. Is there an instance ever happened where UI tests report generation took time ? (although test execution is not slow)

**Comment by wakaleo** [comment] 2021-12-14 17:46
Can you provide a sample projec that reproduces this? What OS are you using? Those times are crazy - there must be something else going on. Report generation is the same time whether it's UI or non-UI, and for that number of tests, it should be in under 15 seconds.

![image](https://user-images.githubusercontent.com/55986/146051857-70238549-2e37-40f8-9580-cfe844b1ee6f.png)

**Comment by wakaleo** [comment] 2022-01-23 09:06
I can't reproduce this issue - if it is still occuring with 3.1.15, try to create a sample project that reproduces the behaviour.

**Closed by wakaleo** 2022-01-23 09:06 UTC
Labels: waiting for feedback
