### ISSUE TITLE
Browser is not started for test which is executed after pending

### ISSUE THREAD

**Issue by a-en** [serenity-bdd/serenity-core#618] opened 2016-11-28 17:06 UTC
Hi there!

I've faced an issue which I'd like to bring out. I have a suite with tests, one of them is marked as pending (with @Pending annotation). The test, which goes after this pending one, is failing because instead of real browser, WebDriverStub is used for it.

`@Test
@Pending
public void test1() {}

@Test
public void test2() {}`

I've traced this a bit and it seems that `StepEventBus.getEventBus().webdriverCallsAreSuspended()` returns true for the test2 (which is not correct). Additional thing to mention, that it is reproducible only for the case when ProvidedDriver is used, so for standard one (like Chrome) everything works fine.

I can provide some simple examples of test suite, page object and implementation of DriverSource interface.

Serenity version: 1.1.42

**Comment by wakaleo** [comment] 2016-11-28 17:13
Yes, it would be great if you could provide a sample test.

**Comment by a-en** [comment] 2016-11-28 17:19
TestSuite.java

```
@RunWith(SerenityRunner.class)
public class TestSuite {

    @Managed
    private WebDriver driver;

    @Steps
    private MySteps mySteps;

    @Test
    @Pending
    public void test1() throws Exception {

    }

    @Test
    public void test2() throws Exception {
        mySteps.openGooglePage();
        mySteps.checkIfTitleMatches("Google");
    }
}
```


MyProvided.java

```
public class MyProvided implements DriverSource {
    @Override
    public WebDriver newDriver() {
        return new FirefoxDriver();
    }

    @Override
    public boolean takesScreenshots() {
        return true;
    }
}
```


MySteps.java
```
public class MySteps extends ScenarioSteps {

    private GooglePage googlePage;

    @Step
    public void openGooglePage() {
        googlePage.open();
    }

    @Step
    public void checkIfTitleMatches(String title) {
        assertEquals(title, googlePage.getTitle());
    }
}
```


GooglePage.java


```
@DefaultUrl("/")
public class GooglePage extends PageObject {

    public GooglePage(WebDriver driver) {
        super(driver);
    }

    public String getTitle() {
        return getDriver().getTitle();
    }
}
```

**Comment by a-en** [comment] 2016-11-28 18:47
Btw, same behavior if instead of @Pending use @Manual

**Comment by wakaleo** [comment] 2016-12-13 17:31
I can't reproduce this with the sample code you gave, could you provide a full sample project that reproduces the issue?

**Comment by a-en** [comment] 2016-12-16 10:41
Hi John,
the only file that I haven't attached was 'serenity.properties'. I realized that without it everything works fine. Here is the content of my 'serenity.properties':

```webdriver.driver=provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=utilities.MyProvided```

In fact I have just these files (mentioned above ) in my project, nothing more. Could you please give it a try with 'serenity.properties'? If it doesn't help, I'll share my project.

**Comment by a-en** [comment] 2017-03-07 09:52
@wakaleo, the issue is still reproducible for `@Ignore` annotation. Could you add fix for that as well?

**Comment by wakaleo** [comment] 2017-03-07 10:02
I'm not seeing the behaviour you describe in version 1.1.3-rc.3

**Comment by a-en** [comment] 2017-03-07 19:08
@wakaleo, are you trying with `@Ignore` annotation? I have tried to run it with 1.2.3-rc.3(and 1.2.3-rc.5) and it is still reproducible. For `@Pending` and `@Manual` it works fine, but not for `@Ignore`.

**Comment by wakaleo** [comment] 2017-03-07 19:15
can you provide a simple sample project?

**Comment by a-en** [comment] 2017-03-07 21:14
Sure, please find it [here](https://github.com/a-en/serenity-ignore-issue-example)

**Comment by a-en** [comment] 2017-03-09 16:21
@wakaleo, were you able to reproduce it with that project?

**Comment by wakaleo** [comment] 2017-03-09 18:57
Thanks for the sample project, the fix will be in the next release.

**Comment by a-en** [comment] 2017-04-03 08:57
@wakaleo, I'm still seeing this issue reproducible after upgrade to 1.2.4 version. The link to the project is the same. Could you take a look?

**Comment by wakaleo** [comment] 2017-04-03 14:24
It seems related to the use of the provided driver. Out of curiosity, why are you using a provided driver (they are meant for rare edge cases, not really for everyday use)

**Comment by a-en** [comment] 2017-04-04 08:29
We've moved there some logic of browser's initialization, based on env variables, os etc.

@wakaleo the bad thing that in 1.2.2 `@Pending` and `@Manual` worked fine with Provided driver, but in 1.2.4 they got broken again. Seems like regression issue.

**Comment by wakaleo** [comment] 2017-04-04 08:59
I think I have fixed it, just doing some further tests.

**Comment by wakaleo** [comment] 2017-05-02 10:05
Fixed.

**Closed by wakaleo** 2017-05-02 10:05 UTC
