### ISSUE TITLE
'#' symbol in scenario titles leads to incorrect reports

### ISSUE THREAD

**Issue by nikolaykolev** [serenity-bdd/serenity-core#230] opened 2015-12-11 09:37 UTC
I have some custom modifications on scenario titles to enable better formatting and sorting in csv report. One of the things is that I have scenario numbering in their title and I used #1, #2 ... When I ran the tests from 85 scenarios they fell down to 35 scenarios ... After a lot of debugging and wondering I found out it was because of the '#' symbol I put in scenarios titles.

Quote from John in google groups: "The "#" symbol is used to introduce links to external issue systems, so that might confuse it. Sound's like a bug of some kind, though."

**Comment by YamStranger** [comment] 2015-12-11 12:01
Hi @nikolaykolev, thanks for this issue. 

It is not a bug, and we have explanation in our [manual](http://thucydides.info/docs/serenity-staging/#_linking_scenarios_tests_with_issues)

Also we already had request for enhancement #203.

**Comment by nikolaykolev** [comment] 2015-12-11 12:03
Yes I know this but I guess it should not work this way when the # is in scenario's titles not in the meta info.
Example:
Scenario: #1 I log in the system

**Comment by YamStranger** [comment] 2015-12-11 12:12
Sure, I will include it in manual. Using # in scenario should bring same effect as using @Title annotation. 

Thanks

**Comment by YamStranger** [comment] 2015-12-11 12:31
@nikolaykolev please close this issue and lets move our discussion under serenity-bdd/serenity-documentation/issues/45 

Thanks a lot!

**Comment by nikolaykolev** [comment] 2015-12-11 12:42
Ok thanks! An updated documentation will do the work :)

**Closed** 2015-12-11 12:43 UTC
