### ISSUE TITLE
A recursive or cyclic reference was detected for the @Steps-annotated

### ISSUE THREAD

**Issue by PadmajaSampath** [serenity-bdd/serenity-core#1105] opened 2018-02-05 11:49 UTC
Hi,

We just updated the Serenity Version from **1.4.0** to **1.8.20** to take advantage of the WaitforAngularRequest implemented using NgWebDriver and we get the below error.

net.thucydides.core.steps.RecursiveOrCyclicStepLibraryReferenceException: A recursive or cyclic reference was detected for the @Steps-annotated

Project compiled successfully and using jdk 1.8.0.

Any help on this would be greatly appreciated.

Thanks

**Comment by wakaleo** [comment] 2018-02-05 12:09
This isn't a bug; in 1.8.x we use a different sharing strategy for @Step libraries. Each step library field is an individual instance, so you can have cyclic references if a step library refers to itself (directly or indirectly). The solution is to use the "shared" attribute (see https://wakaleo.gitbooks.io/the-serenity-book/content/step-libraries).

**Comment by wakaleo** [comment] 2018-02-09 00:38
Closing as not a bug.

**Closed by wakaleo** 2018-02-09 00:38 UTC
