### ISSUE TITLE
net.serenitybdd.rest.SerenityRest.then().statusCode(isIn(statusCodes))  reports a broken test when the assertion is not met instead of a failed test

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#1570] opened 2019-02-11 10:09 UTC
I'm using Serenity version 2.0.39.

this code

	package com.<...>;
	import java.util.Collection;
	import net.thucydides.core.annotations.Step;
	import static org.hamcrest.Matchers.isIn;

	public class MyStep {
		@Step("Then I expect to see one of {0} as status code")
		public void checkStatusCodeOneOf(Collection<Integer> statusCodes) {
  			net.serenitybdd.rest.SerenityRest.then().statusCode(isIn(statusCodes));
		}
	}

Reports orange (broken test) instead of red (failed test).
I'm fairly sure that may test code did return red in this case some Serenity versions ago. 

In the report you can see, then().statusCode(Matcher<? super Integer> expectedStatusCode) throws a java.lang.AssertionError
 
Could it be that the root cause of Serenity not showing this as “failed” but rather as “broken” is caused by the fact that this is a java.lang.* Exception, and not any  type of exception that extends some Exceptions from the JUnit framework, e.g. org.junit.ComparisonFailure?
 
What actually makes Serenity distinguish between “broken” and “failed”? 
Unfortunately, I could not find proper documentation here.

**Comment by wakaleo** [comment] 2019-02-12 02:09
"Failure" indicates an assertion error, and "Broken" indicates an error, from some other type of exception. But I can't reproduce this behaviour (see below), so maybe something else is going on. What error are you seeing in the reports?

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/55986/52606587-28bf2400-2e99-11e9-9005-d69ea5bcea01.png">

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/55986/52606624-4e4c2d80-2e99-11e9-8cc7-d18c98ec8f05.png">

**Comment by ppuetsch** [comment] 2019-02-12 07:35
Hi John, 
please find attached the screenshots from the report.
As you can see, in the report we also see a java.lang.AssertionError. 


![gh1](https://user-images.githubusercontent.com/47553592/52619047-e6014a00-2ea0-11e9-83eb-0e7f9cb5991e.png)

![gh2](https://user-images.githubusercontent.com/47553592/52618863-4d6aca00-2ea0-11e9-9236-2be4e132ccc9.jpg)



I did have the feeling that I also saw AssertionErrors from the Code Snipped posted by @SchnuckySchuster that lead to a Failed Test - I did not yet see any patterns that could explain the behaviour. 

Could you confirm my understanding about how it _should_  work: Every exception that extends java.lang.AssertionError should lead to a failed Test, any Exception that does not extend java.lang.AssertionError leads to a broken test?

Do you have any Idea how we could trace into this?

Best regards,
Philip

**Comment by wakaleo** [comment] 2019-02-12 16:21
Have a look at the `FailureAnalysis` class. Basically, your understanding is correct: AssertionErrors should cause failures, and anything else should cause errors.

**Comment by Chelinadevi** [comment] 2020-09-07 10:55
Hi,
I am facing an issue when working with SerenityRest. I have simple get request to fetch the student info.

1) When using **RestAssured().given().when().get().then().statuscode(200)**  ---> This is working fine with junit and also from maven build and index.html is generated.

2) Whereas, **SerenityRest().given().when().get().then().statuscode(200)** ----> is causing the test to fail 

I am not sure why this issue is happening. Please help me resolve this issue.
Thanks in advance.

**Comment by wakaleo** [comment] 2020-09-07 11:01
@Chelinadevi What error are you seeing?

**Comment by Chelinadevi** [comment] 2020-09-07 16:32
Hi,

Thanks for your reply.

Below is the attached screenshot for reference. This is when running the
junit test. The issue is:

java.lang.ExceptionInInitializerError
at
net.serenitybdd.rest.utils.RestDecorationHelper.decorate(RestDecorationHelper.java:20)
at net.serenitybdd.rest.SerenityRest.given(SerenityRest.java:216)
at
com.studentapp.junit.FirstSerenityTest.getallstudents(FirstSerenityTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at
net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:33)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at
net.serenitybdd.junit.runners.SerenityRunner.performRunChild(SerenityRunner.java:460)
at
net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:435)
at
net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:42)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:239)
at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.UnsupportedOperationException: Cannot define class
using reflection: Could not find sun.misc.Unsafe
at
net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:334)
at
net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:187)
at
net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:205)
at
net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:126)
at
net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
at
net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
at
net.serenitybdd.rest.utils.RestSpecificationFactory.<clinit>(RestSpecificationFactory.java:48)
... 31 more


[image: image.png]

**Comment by Chelinadevi** [comment] 2020-09-07 16:33
The pom.xml file is as below:

 <project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>StudentApp</groupId>
<artifactId>SerenityRest</artifactId>
<version>0.0.1-SNAPSHOT</version>

<name>Serenity JUnit Quick Start Project</name>

<dependencies>
<dependency>
<groupId>net.serenity-bdd</groupId>
<artifactId>serenity-core</artifactId>
<version>1.9.25</version>
</dependency>
<dependency>
<groupId>net.serenity-bdd</groupId>
<artifactId>serenity-junit</artifactId>
<version>1.9.25</version>
</dependency>
<dependency>
<groupId>net.serenity-bdd</groupId>
<artifactId>serenity-rest-assured</artifactId>
<version>1.9.25</version>
</dependency>
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-simple</artifactId>
<version>1.6.1</version>
</dependency>
<dependency>
<groupId>javax.xml.bind</groupId>
<artifactId>jaxb-api</artifactId>
<version>2.3.0</version>
</dependency>

<dependency>
<groupId>org.assertj</groupId>
<artifactId>assertj-core</artifactId>
<version>1.7.0</version>
<scope>test</scope>
</dependency>

<dependency>
<groupId>javax.xml.bind</groupId>
<artifactId>jaxb-api</artifactId>
<version>2.3.1</version>
</dependency>

<dependency>
<groupId>com.sun.xml.bind</groupId>
<artifactId>jaxb-core</artifactId>
<version>2.2.11</version>
</dependency>
<dependency>
<groupId>com.sun.xml.bind</groupId>
<artifactId>jaxb-impl</artifactId>
<version>2.2.11</version>
</dependency>

</dependencies>
<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.18</version>
<configuration>
<skip>true</skip>
<includes>
<include>**/studentapp/**/*.java</include>
</includes>
</configuration>
</plugin>

<plugin>
<artifactId>maven-failsafe-plugin</artifactId>
<version>2.18</version>
<configuration>
<includes>
<include>**/studentapp/**/*.java</include>
</includes>
<forkCount>4</forkCount>
<reuseForks>true</reuseForks>


<argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
</configuration>
<executions>
<execution>
<goals>
<goal>integration-test</goal>
<goal>verify</goal>
</goals>
</execution>
</executions>
</plugin>

<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.2</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
</plugin>


<plugin>
<groupId>net.serenity-bdd.maven.plugins</groupId>
<artifactId>serenity-maven-plugin</artifactId>
<version>1.9.25</version>
<dependencies>
<dependency>
<groupId>net.serenity-bdd</groupId>
<artifactId>serenity-core</artifactId>
<version>1.9.25</version>
</dependency>
</dependencies>
<executions>
<execution>
<id>serenity-reports</id>
<phase>post-integration-test</phase>
<goals>
<goal>aggregate</goal>
</goals>
</execution>
</executions>
</plugin>

<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-deploy-plugin</artifactId>
<version>2.8.2</version>
</plugin>

</plugins>
</build>

</project>

**Comment by Chelinadevi** [comment] 2020-09-07 16:40
Error in maven build:

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model
for StudentApp:SerenityRest:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)'
must be unique: javax.xml.bind:jaxb-api:jar -> version 2.3.0 vs 2.3.1 @
line 45, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they
threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support
building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------------------< StudentApp:SerenityRest
>-----------------------
[INFO] Building Serenity JUnit Quick Start Project 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar
]---------------------------------
[WARNING] The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid,
transitive dependencies (if any) will not be available, enable debug
logging for more details
[WARNING] The POM for com.sun.xml.bind:jaxb-impl:jar:2.2.11 is invalid,
transitive dependencies (if any) will not be available, enable debug
logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SerenityRest ---
[INFO] Deleting D:\Eclipse-New-New\SerenityRest\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @
SerenityRest ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered
resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory
D:\Eclipse-New-New\SerenityRest\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @
SerenityRest ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252,
i.e. build is platform dependent!
[INFO] Compiling 1 source file to
D:\Eclipse-New-New\SerenityRest\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources)
@ SerenityRest ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered
resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @
SerenityRest ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252,
i.e. build is platform dependent!
[INFO] Compiling 5 source files to
D:\Eclipse-New-New\SerenityRest\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.18:test (default-test) @ SerenityRest ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ SerenityRest ---
[INFO] Building jar:
D:\Eclipse-New-New\SerenityRest\target\SerenityRest-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.18:integration-test (default) @
SerenityRest ---
[INFO] Failsafe report directory:
D:\Eclipse-New-New\SerenityRest\target\failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize;
support was removed in 8.0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
com.google.inject.internal.cglib.core.$ReflectUtils$1
(file:/C:/Users/vasue/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar)
to method
java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of
com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal
reflective access operations
WARNING: All illegal access operations will be denied in a future release
Running com.studentapp.junit.FirstSerenityTest
456 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener -

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __
 .___________.____    ____
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\
\  /   /
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \
  \/   /
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |
\_    _/
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |
|  |
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|
|__|


 News and tutorials at http://www.serenity-bdd.info

 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/

 Join the Serenity Community on Rocket Chat at
https://serenity-bdd.rocket.chat
 Serenity BDD Support and Training at
http://serenity-bdd.info/#/trainingandsupport
 Learn Serenity BDD online at http://serenity-dojo.com

-------------------------------------------------------------------------------------

860 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test
Suite Started: First serenity test
1364 [main] INFO net.thucydides.core.steps.ConsoleLoggingListener -
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/


TEST STARTED: getallstudents
-------------------------------------------------------------------
1365 [main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
2713 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener -
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/
          \_\

TEST FAILED WITH ERROR: This is first serenity
---------------------------------------------------------------------
2718 [main] ERROR net.thucydides.core.steps.ConsoleLoggingListener -
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.032 sec
<<< FAILURE! - in com.studentapp.junit.FirstSerenityTest
getallstudents(com.studentapp.junit.FirstSerenityTest)  Time elapsed: 1.248
sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
at
net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:334)
at
net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:187)
at
net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:205)
at
net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:126)
at
net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
at
net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
at
net.serenitybdd.rest.utils.RestSpecificationFactory.<clinit>(RestSpecificationFactory.java:48)
at
net.serenitybdd.rest.utils.RestDecorationHelper.decorate(RestDecorationHelper.java:20)
at net.serenitybdd.rest.SerenityRest.given(SerenityRest.java:216)
at
com.studentapp.junit.FirstSerenityTest.getallstudents(FirstSerenityTest.java:31)


Results :


Tests in error:
  FirstSerenityTest.getallstudents:31 » ExceptionInInitializer


Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding Cp1252,
i.e. build is platform dependent!
[INFO]
[INFO] --- serenity-maven-plugin:1.9.25:aggregate (serenity-reports) @
SerenityRest ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
com.google.inject.internal.cglib.core.$ReflectUtils$1
(file:/C:/Users/vasue/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar)
to method
java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of
com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal
reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] current_project.base.dir: D:\Eclipse-New-New\SerenityRest
[INFO] Generating test results for 1 tests
[INFO] 3 requirements loaded after 462 ms
[INFO] 3 related requirements found after 462 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports: 488 ms
[INFO] Configured report threads: 20
[INFO] Test results for 1 tests generated in 1712 ms
[INFO]
[INFO] --- maven-failsafe-plugin:2.18:verify (default) @ SerenityRest ---
[INFO] Failsafe report directory:
D:\Eclipse-New-New\SerenityRest\target\failsafe-reports
[WARNING] File encoding has not been set, using platform encoding Cp1252,
i.e. build is platform dependent!
[INFO]
[INFO]
------------------------------------------------------------------------
[INFO] Skipping Serenity JUnit Quick Start Project
[INFO] This project has been banned from the build due to previous failures.
[INFO]
------------------------------------------------------------------------
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  16.832 s
[INFO] Finished at: 2020-09-07T22:08:30+05:30
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-failsafe-plugin:2.18:verify (default) on
project SerenityRest: There are test failures.
[ERROR]
[ERROR] Please refer to
D:\Eclipse-New-New\SerenityRest\target\failsafe-reports for the individual
test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wakaleo** [comment] 2020-09-07 16:41
Probably a version conflict of some kind. Have a look at https://github.com/serenity-bdd/bdd-trader for a sample project with the latest dependencies.

**Comment by Chelinadevi** [comment] 2020-09-07 17:20
I tried the latest versions as well and still see the below error(
*ExceptionInInitializer
* )

There is no problem when using RestAssured, but the problem is when using
SerenityRest

[main] ERROR  -
         __  _____ _____ ____ _____   _____ ____  ____   ___  ____
 _      / / |_   _| ____/ ___|_   _| | ____|  _ \|  _ \ / _ \|  _ \
(_)____| |    | | |  _| \___ \ | |   |  _| | |_) | |_) | | | | |_) |
 |_____| |    | | | |___ ___) || |   | |___|  _ <|  _ <| |_| |  _ <
(_)    | |    |_| |_____|____/ |_|   |_____|_| \_\_| \_\\___/|_| \_\
        \_\

This is first serenity
---------------------------------------------------------------------
[main] ERROR  -
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed:
6.037 s <<< FAILURE! - in com.studentapp.junit.FirstSerenityTest
[ERROR] getallstudents(com.studentapp.junit.FirstSerenityTest)  Time
elapsed: 1.6 s  <<< ERROR!
java.lang.ExceptionInInitializerError
at
com.studentapp.junit.FirstSerenityTest.getallstudents(FirstSerenityTest.java:31)
Caused by: java.lang.UnsupportedOperationException: Cannot define class
using reflection: Unsupported class file major version 58
at
com.studentapp.junit.FirstSerenityTest.getallstudents(FirstSerenityTest.java:31)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   FirstSerenityTest.getallstudents:31 » ExceptionInInitializer
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO]
[INFO] --- serenity-maven-plugin:2.3.2:aggregate (serenity-reports) @
SerenityRest ---
[INFO] Test results for 1 tests generated in 2 secs in directory:
file:/D:/Eclipse-New-New/SerenityRest/target/site/serenity/
[INFO] -----------------------------------------
[INFO]  SERENITY TESTS : ERROR
[INFO] -----------------------------------------
[INFO] | Tests executed         | 1
[INFO] | Tests passed           | 0
[INFO] | Tests failed           | 0
[INFO] | Tests with errors      | 1
[INFO] | Tests compromised      | 0
[INFO] | Tests pending          | 0
[INFO] | Tests ignored/skipped  | 0
[INFO] ------------------------ | --------------
[INFO] | Total Duration         | 1s 583ms
[INFO] | Fastest test took      | 1s 583ms
[INFO] | Slowest test took      | 1s 583ms
[INFO] -----------------------------------------
[INFO]
[INFO] SERENITY REPORTS
[INFO]   - Full Report:
file:///D:/Eclipse-New-New/SerenityRest/target/site/serenity/index.html
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M3:verify (default) @ SerenityRest
---
[INFO]
[INFO]
------------------------------------------------------------------------
[INFO] Skipping Serenity JUnit Quick Start Project
[INFO] This project has been banned from the build due to previous failures.
[INFO]
------------------------------------------------------------------------
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  18.236 s
[INFO] Finished at: 2020-09-07T22:47:19+05:30
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M3:verify (default) on
project SerenityRest: There are test failures.
[ERROR]
[ERROR] Please refer to
D:\Eclipse-New-New\SerenityRest\target\failsafe-reports for the individual
test results.
[ERROR] Please refer to dump files (if any exist) [date].dump,
[date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by wakaleo** [comment] 2020-09-07 17:25
It's a version conflict. Refer to the combination of versions used in the sample project. It's a project-specific issue (caused by an incompatible version of the bytebuddy library by the looks of it), not a Serenity one.

**Comment by Chelinadevi** [comment] 2020-09-07 17:42
Thank you very much for your inputs...I got it resolved...Now I am able to
run with both RestAssured and SerenityRest

I resolved by changing to version to


<dependency>
    <groupId>net.bytebuddy</groupId>
    <artifactId>byte-buddy</artifactId>
    <version>1.10.10</version>
</dependency>

**Comment by Chelinadevi** [comment] 2020-09-10 18:11
Hi,

I am working on serenity rest assured.

I need to put the dynamic payload to request body. Could you please assist
me on this. Or can you please share repository where I can refer a similar
code.

Thank you

**Comment by globalworming** [comment] 2020-09-11 09:04
this issue is resolved, i put your question in a new one

**Closed by globalworming** 2020-09-11 09:04 UTC
Labels: waiting for feedback
