### ISSUE TITLE
No Serenity support for Selenium gecko driver

### ISSUE THREAD

**Issue by ashish0401** [serenity-bdd/serenity-core#591] opened 2016-11-03 02:01 UTC
Serenity doesn't support gecko driver for the newest Firefox versions.
This is impacting UI testing if heavily depended on firefox coverage.
Even though you can override the default selenium bindings in POM but system property not set for gecko driver in Serenity code.
Can we have some date when this can be fixed ?

I can see following errors when tried to run tests with gecko driver:

Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

And 

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

**Comment by vuthelinh** [comment] 2016-11-03 06:48
Hi Ashish0401

It seems to be the same with 

https://github.com/serenity-bdd/serenity-core/issues/447

**Comment by wakaleo** [comment] 2016-11-03 06:49
Duplicate of #447 - see latest updates there.

**Closed by wakaleo** 2016-11-03 06:49 UTC

**Comment by BrahmendraJayaraju** [comment] 2021-06-16 10:17
i am able to launch firefox 89.0.1 version firefox but its not entering url showing below warning.please help me which version is compatible for firefox . Driver info: driver.version: FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Timed out waiting 45 seconds for Firefox to start.
