### ISSUE TITLE
Steps in @After block are skipped if an Exception is thrown

### ISSUE THREAD

**Issue by swalkersbw** [serenity-bdd/serenity-core#54] opened 2015-04-29 03:55 UTC
When tests fail due to an assertion in a Test class then the @After steps are executed before the results of the assertion failure are logged in the report output sequence.
When tests fail due to an exception being thrown anywhere ( Test/Step/Page ) then the @After steps do not execute and are marked as 'SKIPPED' in the report sequence.  This means that cleanup tasks cannot be reliably carried out, i.e. there is no mechanism that allows for cleanup checks to be executed.

**Comment by YamStranger** [comment] 2015-11-11 11:40
Hi @swalkersbw! Thanks for reporting this issue. Please include in this issue your build script, and short example of project to reproduce it. And we for sure will help you!
Thanks

**Comment by YamStranger** [comment] 2015-11-17 18:53
Hello @swalkersbw
This issue can be closed. It was tested under 1.1.21 and can not be reproduced:
This class used:

```
@RunWith(SerenityRunner.class)
public class SampleTest {
    private static int number = 0;
    @Steps
    TestSteps steps;

    @Before
    public void setUp() throws IOException {
        number += 1;
        Files.createDirectory(Paths.get("folder" + number));
    }

    @After
    public void cleanUp() throws IOException {
        Files.delete(Paths.get("folder" + number));
    }


    @Test
    public void shouldExecuteThisTest() {
        steps.then_folder_exists(number);
    }

    @Test
    public void shouldExecuteThisTestToo() {
        steps.then_folder_exists(number);
        Assert.fail("Should fail for issue");
    }
}
```

and Steps class
```
public class TestSteps {

    @Step
    public void then_folder_exists(final int number) {
        Assert.assertTrue("Folder is not created during \"@Before\"",Files.exists(Paths.get("folder" + number)));
    }
}
```
It executed as expected:
Folder created during @Before, checked during execution of method, and was removed during @After (checked working directory manually). 
Second method fail with correct message, and after this fail - folder was removed. The same folder doesn't exist after execution of test. 

Here is screenshots:
![report1](https://cloud.githubusercontent.com/assets/1667699/11221300/1be4fb2c-8d6d-11e5-8013-6f60e7550923.png)
![succe](https://cloud.githubusercontent.com/assets/1667699/11221301/1bea6968-8d6d-11e5-8f72-800f55e014f9.png)
![fail](https://cloud.githubusercontent.com/assets/1667699/11221303/1f74f6c0-8d6d-11e5-82b6-fd03c5071d95.png)


@swalkersbw please close this issue, or provide more examples. 
Tanks a lot for this issue!

**Comment by serjQA** [comment] 2016-04-06 12:52
but if in test will be exception, and in after method we will use steps. In my project it doesnt seems to work. Maybe you suggest some decision to use steps in @after methods, because some time there is much easier to clean with steps(for example create item, check something, in if during checking will be exception, execute delete item step)

**Comment by YamStranger** [comment] 2016-04-06 14:48
@serjQA test provided above was created for demonstration that all works fine. 

During executing test this line
```
 Assert.assertTrue("Folder is not created during \"@Before\"",Files.exists(Paths.get("folder" + number)));
```
throws exception and after that statement in @after method remove all folders. 
So all @after method executed successfully after "intermediate" test throw exception

So It works fine and that is why this issue was closed. 

Please give me some examples when it does not work for you - and I will try to help

Thanks!

**Comment by gciltaru** [comment] 2016-05-09 15:14
@YamStranger Hi, I have a similar problem and I think it is caused by calling a method with @Step annotation in the @after method, if the test method fails.

So, if you wrap
`Files.delete(Paths.get("folder" + number));
 `
into a Step from TestSteps:
`	@Step
	public void after_method(final int number) {
		Files.delete(Paths.get("folder" + number));
	}`
then call it like:
`@After
    public void cleanUp() throws IOException {
        steps.after_method(number)
    }`

If the test fails, the steps.after_method is not executed, and it may appear that cleanUp() is not executed.

**Comment by YamStranger** [comment] 2016-05-09 19:12
Thanks @gciltaru. 

Will take a look how it is possible to fix - using of @Step method on @after method.

**Comment by cliviu** [comment] 2016-05-09 22:16
Hi @gciltaru. I was able to reproduce the problem and I will try to find some fix

**Comment by YamStranger** [comment] 2016-06-21 18:15
@swalkersbw, @cliviu is this issue can be closed?

**Comment by cliviu** [comment] 2016-06-22 10:21
From my point of view, yes

**Comment by YamStranger** [comment] 2016-06-29 15:49
It seems that this issue was solved and ticket should be closed. 
@gciltaru thansk this this ticket!!

@cliviu thanks a lot for fix!

**Closed by YamStranger** 2016-06-29 15:49 UTC
Labels: bug
