### ISSUE TITLE
Aggreate Report : Test count is shown correctly in aggregated report

### ISSUE THREAD

**Issue by SubhasishC** [serenity-bdd/serenity-core#686] opened 2017-02-13 06:59 UTC
Hi,

I am testing rest api with serenity bdd + maven project.

The project has two runner class refering to two separate feature files F1.feature & F2.feature

I am running both runner class parallelly to reduce the execution time.

Suppose first feature has 10 scenarios & second feature file has 15 scenarios. Then after execution of individual runner class, the individually generated index.html is showing correct data as per below:

Index.html for 1st feature file
Test Type 	Total 	Pass  	Fail  	Pending  	Ignored 

Automated    10     10(100%) 0		 0				0

Index.html for 2nt feature file
Test Type 	Total 	Pass  	Fail  	Pending  	Ignored 

Automated    15     15(100%) 0		 0				0

However, after the executing serenity:aggregate command on both the above results, I should get proper aggregated report. However, this is not happening.

The aggregate report has index.html as per below

Index.html for aggregate report
Test Type 	Total 	Pass  	Fail  	Pending  	Ignored 

Automated    50     50(100%) 0		 0				0

The data shown in  the report is double of what it should be.

I am using the below version:

serenity.cucumber.version = 1.1.20
serenity.version=1.2.2

Please help.

**Comment by wakaleo** [comment] 2017-02-13 07:23
Could you provide a sample project where this is happening?

**Comment by SubhasishC** [comment] 2017-02-13 09:59
I will not be able to provide any sample project. However, I have edited my problem. Please look into the 1st comment & help.

Thanks in Advance,
Subhasish

**Comment by wakaleo** [comment] 2017-02-19 11:44
I'm unable to reproduce this issue without more details. When Serenity generates the reports, it simply uses all the JSON files it finds in the target/site/serenity directory, regardless of where they come from. The only way for it to report that there are more is if there are in fact additional JSON files in this directory. Can you provide the target directories produced by each test run?

**Comment by wakaleo** [comment] 2017-11-01 15:59
I'm assuming this is fixed in the latest versions.

**Closed by wakaleo** 2017-11-01 15:59 UTC
Labels: waiting for feedback
