### ISSUE TITLE
Serenity launches 2 instances of Chrome if the driver parameter is not set in the @Managed annotation

### ISSUE THREAD

**Issue by amarmaliuk** [serenity-bdd/serenity-core#378] opened 2016-04-12 13:25 UTC
Hey guys,

I'm facing an issue that Serenity launches 2 instances of Chrome browser if the 'driver' property is not explicitly specified within the @Managed annotation. 
It does not happen with the firefox though (when firefox is set in serenity.properties).
I didn't find similar issue here so it would be great if you could have a look.

(I spent hours figuring out what's wrong with my tests, and it appeared it is even reproducible for a very basic scenario)

test class
```java
@RunWith(SerenityRunner.class)
public class TmpTest {

    // @Managed(driver = "chrome") -> in this case only 1 instance is being open
    @Managed
    WebDriver driver;

    GooglePage testPage;

    @Test
    public void test() {
        testPage.open(); //the first instance is being open here
        testPage.search("google"); //the second is here
    }
}
```

page object
```java
@DefaultUrl("http://www.google.com")
public class GooglePage extends PageObject {

    @FindBy(id = "lst-ib")
    public WebElementFacade element;

    public void search(CharSequence ... charSequences) {
        element.sendKeys(charSequences);
    }
}
```

serenity.properties
```
webdriver.driver=chrome
webdriver.chrome.driver=chromedriver.exe
```

pom.xml
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <groupId>my.temp</groupId>
    <artifactId>serenity-tmp</artifactId>
    <version>1.0-SNAPSHOT</version>
    <modelVersion>4.0.0</modelVersion>
    <properties>
        <serenity.version>1.1.29-rc.3</serenity.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
    </dependencies>
</project>
```

**Comment by wakaleo** [comment] 2016-04-12 15:04
Are you resizing the window?

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 12 April 2016 at 2:25:18 PM, andrey (notifications@github.com) wrote:

Hey guys,

I'm facing an issue that Serenity launches 2 instances of Chrome browser if the 'driver' property is not explicitly specified within the @Managed annotation.
It does not happen with the firefox though (when firefox is set in serenity.properties).
I didn't find similar issue here so it would be great if you could have a look.

(I spent hours figuring out what's wrong with my tests, and it appeared it is even reproducible for a very basic scenario)

test class

@RunWith(SerenityRunner.class)
public class TmpTest {

    // @Managed(driver = "chrome") -> in this case only 1 instance is being open
    @Managed
    WebDriver driver;

    GooglePage testPage;

    @Test
    public void test() {
        testPage.open(); //the first instance is being open here
        testPage.search("google"); //the second is here
    }
}
page object

@DefaultUrl("http://www.google.com")
public class GooglePage extends PageObject {

    @FindBy(id = "lst-ib")
    public WebElementFacade element;

    public void search(CharSequence ... charSequences) {
        element.sendKeys(charSequences);
    }
}
serenity.properties

webdriver.driver=chrome
webdriver.chrome.driver=chromedriver.exe

pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <groupId>my.temp</groupId>
    <artifactId>serenity-tmp</artifactId>
    <version>1.0-SNAPSHOT</version>
    <modelVersion>4.0.0</modelVersion>
    <properties>
        <serenity.version>1.1.29-rc.3</serenity.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
    </dependencies>
</project>

**Comment by amarmaliuk** [comment] 2016-04-12 15:22
@wakaleo, I do getDriver().manage().window().maximize() in my tests, however this is also reproducible for the case I mentioned in the description (open a page, call a page object method).

**Comment by YamStranger** [comment] 2016-04-12 18:13
Hello @amarmaliuk 

I think that page object already has driver inside it - did you try remove that property at all and use only page object? 

For not serenity will initialize all @Managed drivers will they be used or not (we have some issue for this)

**Comment by amarmaliuk** [comment] 2016-04-12 18:23
@YamStranger , 
As you can see in a code snippet provided the page object (GooglePage.class) does not have a driver inside. This makes me a bit confuse.

> did you try remove that property at all and use only page object?
Do you mean remove GooglePage testPage from TmpTest.class?

Thanks.

**Comment by YamStranger** [comment] 2016-04-12 18:35
@amarmaliuk I mean next structure of tests:

Test method uses particular Step(or steps) in StepsClass, and Step use PageObject, and Browser managed inside PageObject without declaration. 

For example here is PageObject: https://github.com/serenity-bdd/serenity-web-todomvc-core/blob/35b521023083f5ae2005c8c1a5b98a5478cdd9f0/src/main/java/net/serenitybdd/web/todosmvc/pages/TodoPage.java

And here is Steps Class that contains PageObject: https://github.com/serenity-bdd/serenity-test-projects/blob/07e63913e1baf1b694f5de4665fa2f6f21e4b426/web-todomvc-tests/jbehave-without-examples/src/test/java/net/serenitybdd/demos/todos/steps/ATodoUser.java

And here is JUnit test that uses Steps Class: https://github.com/serenity-bdd/serenity-test-projects/blob/07e63913e1baf1b694f5de4665fa2f6f21e4b426/junit-in-parallel/src/test/java/net/serenitybdd/demos/actions/UserCanPerformSimpleActionNumber.java

As you see here there is no @Managed driver, because it managed inside PageObject. 

I just not sure why you need next lines in your code: 
```
 // @Managed(driver = "chrome") -> in this case only 1 instance is being open
    @Managed
    WebDriver driver;
```
because it will produce additional browser instance that actually will not be used

**Comment by amarmaliuk** [comment] 2016-04-12 19:56
@YamStranger 
I'm afraid you've provided an incorrect example.
The `UserCanPerformSimpleActionNumber.class` does not use the `net.serenitybdd.demos.todos.steps.ATodoUser.class` you mentioned. It uses the `net.serenitybdd.demos.actions.steps.ATodoUser.class` one. 
Having the `UserCanPerformSimpleActionNumber.class` like the following
```java
import net.serenitybdd.demos.actions.steps.ATodoUser;
@RunWith(SerenityRunner.class)
public class UserCanPerformSimpleActionNumber {
    @Steps
    ATodoUser jane;
    @Test
    public void do_some_action_number () {
        jane.opens_the_todo_application();
    }
}
```
will throw the NullPointerException in method
```java
public class ATodoUser {
    @Step
    public void opens_the_todo_application() {
        onTheTodoHomePage.open();
    }
    TodoPage onTheTodoHomePage;
}
```
as the  onTheTodoHomePage was never initialised.
This this why the @Managed WebDriver needs to be specified in the UserCanPerformSimpleActionNumber.class (same as it is in this example http://www.thucydides.info/docs/serenity/#_serenity_pageobjects_in_junit).

Any thoughts on this?
Thanks.

**Comment by YamStranger** [comment] 2016-04-12 20:49
@amarmaliuk it seems that it would be better add here link to project as example and not classes ( 

Here is project https://github.com/serenity-bdd/serenity-test-projects/tree/master/web-todomvc-tests

Yes, null pointer will appear if test will be used without webdriver: 
```
...
@RunWith(SerenityRunner.class)
@WithTag("smoketest")
public class CompleteTodos {
/*
    @Managed
    WebDriver joesBrowser;
*/
    @Steps
    ATodoUser joe;
....
```
it was bad idea ( 

So, lest return to your problem...

I tried to reproduce your issue using CompleteTodos in package net.serenitybdd.demos.todos.features.update_my_todos.  It has almost same structure as your test, and what most important - 'driver' property is not explicitly specified within the @Managed annotation.

```
...
@RunWith(SerenityRunner.class)
@WithTag("smoketest")
public class CompleteTodos {
    @Managed
    WebDriver joesBrowser;
    @Steps
    ATodoUser joe;
....
```

I tried to run provided below test project with command to use firefox: 
```
./gradlew clean :junit-serenity-tests:test -Dwebdriver.driver=firefox -Dtest.single=CompleteTodos aggregate
```
as well as with command to use chrome:
```
./gradlew clean :junit-serenity-tests:test -Dwebdriver.driver=chrome-Dtest.single=CompleteTodos aggregate
```
I used latest core as you. 

Unfortunately I can not reproduce your issue, all works fine - browser was opened only once during test, same behaving with firefox and chrome. 

Also on my system latest chromedriver is installed: https://sites.google.com/a/chromium.org/chromedriver/

and I used latest chrome/firefox versions. 

Please provide version of chromedriver and firefox/chrome what you use - may be it will help to close this ticket

Thanks!

**Comment by amarmaliuk** [comment] 2016-04-12 22:00
@YamStranger it looks like the issue with my example is absence of @Steps layer. If I wrap up page object methods with @Step methods in a steps class, declare a field of this class type in my test class and use its methods ("page object > steps class with page object declaration > test" hierarchy) - everything looks good.

If I have the page object declared as a field in my test class and I call its methods within a test, it causes multiple browser instances creation.

If this is an unintended usage of serenity - the ticket can be closed for sure.
The only question then is why this is not reproducible for firefox driver...

Thanks for your time.

**Comment by YamStranger** [comment] 2016-04-13 04:59
@amarmaliuk It is great that you solve your issue. 

Basically Steps class for Serenity BDD it is best way of organizing tests, and it is source for reports. So, page objects should be used in Steps classes. 

But, it will be great to fix this issue with browser and PageObject without Steps object, it is for sure bug.

Thanks for this ticket!

**Comment by wakaleo** [comment] 2016-05-15 13:18
Hi @amarmaliuk,

I've added the following test to try to reproduce the issue in the latest code base:
```
@RunWith(SerenityRunner.class)
public class SamplePassingScenarioWithPageObjects {
    
    @Managed(driver = "chrome")
    public WebDriver web driver

    IndexPage indexPage;

    @Test
    public void happy_day_scenario() throws Throwable {
        indexPage.open();
        assertThat(indexPage.getTitle()).isNotEmpty();
    }
}
```
However it seems to be working fine. Could you try with the latest version when it comes out in the next couple of days?

**Comment by amarmaliuk** [comment] 2016-05-16 09:28
Hey @wakaleo ,
There is no issue with your example as you have explicitly specified the Chrome as a driver in the Managed annotation.
The issue this ticket is about is that there will be 2 Chrome instances launched if the driver parameter is not defined in the Managed annotation.
Re-checked on 1.1.32-rc.1
Thanks.

**Comment by wakaleo** [comment] 2016-05-17 08:05
Hi @amarmaliuk,

I've been unable to reproduce this with version 1.1.32-rc.2, but I've added some tests for this case. If you can reproduce the issue in version 1.1.32-rc.2, could you post a sample project?

**Comment by amarmaliuk** [comment] 2016-05-17 10:30
Hi @wakaleo ,
It's still reproducible for me on 1.1.32-rc.2. Please have a look at the attachment.
Thanks.
[serenity-tmp.zip](https://github.com/serenity-bdd/serenity-core/files/267941/serenity-tmp.zip)

**Comment by wakaleo** [comment] 2016-05-17 11:40
This will be in release 1.1.32

**Closed** 2016-05-17 11:40 UTC
Labels: bug, waiting for confirmation

**Comment by berlin-sky** [comment] 2017-02-21 13:50
Hi John, please can you let us know if this issue is resolved, I can still see this happening in 1.139.

**Comment by wakaleo** [comment] 2017-02-21 13:53
What version are you using? (The latest is 1.2.3-rc.3)

**Comment by paul-ng** [comment] 2017-02-23 03:58
The latest version 1.2.3-rc.4 still have this problem

**Comment by wakaleo** [comment] 2017-02-23 05:30
I'm not getting this issue (using the code in the original post) in version 1.2.3-rc.4. If you are having issues, please provide a sample project that reproduces the issue and we will take a look.

**Comment by rakeshnambiar** [comment] 2017-06-13 11:56
@paul-ng .. I too had the similar issue in 1.2.3-rc.4. But after I update the Chrome Driver and Chrome browser to the latest version it's resolved. Would you mind to run your tests in the latest browser version?
