### ISSUE TITLE
unable to pass WebElementFacade to Select class in selenium 4.1.1

### ISSUE THREAD

**Issue by MohammedWaasim** [serenity-bdd/serenity-core#2860] opened 2022-06-28 15:49 UTC
Earlier in older version of selenium 3, we were able to pass on WebElementFacade in the Select. 
now with serentiy 3.1.15 and selenium 4.1.1 we get below error.
@wakaleo can you please help!
```
@FindBy(xpath = "//select[contains(@name,'mar')]")
private WebElementFacade maritalStatusSelectField;

final Select ms = new Select(maritalStatSelectField);
ms.selectByVisibleText(text);

```
java.lang.UnsupportedOperationException: getDomAttribute

	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.thucydides.core.annotations.locators.AbstractSingleItemHandler.invoke(AbstractSingleItemHandler.java:43)
	at com.sun.proxy.$Proxy64.getDomAttribute(Unknown Source)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)

**Comment by lgermani** [comment] 2022-06-29 11:59
Are you executing your tests using a Remote driver? like on SauceLabs

**Comment by wakaleo** [comment] 2022-06-29 14:53
Duplicate of #2861

**Closed** 2022-06-29 14:53 UTC
