### ISSUE TITLE
Empty reports when using @RunWith(SerenityParameterizedRunner.class)

### ISSUE THREAD

**Issue by pisarenco92** [serenity-bdd/serenity-core#440] opened 2016-06-09 07:54 UTC
Hi,

I'm trying to use @RunWith(SerenityParameterizedRunner.class) in serenity 1.1.36 and it seems not to work when generating reports (empty reports). I'm using serenity with JUnit and Appium.

My test code:

    @RunWith(SerenityParameterizedRunner.class
    @UseTestDataFrom(value = "GenderTest.csv", separator = ',')
    public class GenderTest {	

	@Managed(driver = "appium")
	WebDriver driver;
	
	@Steps
	GenderPageSteps genderSteps;
	
	@Steps
	HomePageSteps homeSteps;
	
	@Steps
	CountryLanguageSteps countryLanguageSteps;
	
	public String gender;
	public String language;
	public int numberOfCountries;
	public String country;
	
	@Test
	public void selectGenderTest(){
		countryLanguageSteps.loaded(numberOfCountries); 
		countryLanguageSteps.selectCountry(country);
		countryLanguageSteps.clickStart();
		genderSteps.loaded(3);
		genderSteps.selectGender(gender);
		homeSteps.loadedHomePage(gender);
	}

I run test and no errors.

When I run serenity:aggregate a warning is showing: This file was not a valid JSON Serenity test report: 2ab61cf7641a456499539609cbbc690ae99655b612d1d8f6f50b5da3c33b647b.json

And when I open the report, report is empty:
![screen shot 2016-06-09 at 10 52 22 am](https://cloud.githubusercontent.com/assets/15072906/15922430/4d6ab4ca-2e30-11e6-93b0-8c976a7b7787.png)

If I change to run with @RunWith(SerenityRunner.class) works fine.

Did anybody else having same issues?

**Comment by wakaleo** [comment] 2016-06-09 18:25
I can't reproduce this issue, could you create a sample project?

**Comment by hypery2k** [comment] 2016-06-09 19:42
duplicate of #443

**Comment by pisarenco92** [comment] 2016-06-10 09:50
Here is a simple project:
[com.zip](https://github.com/serenity-bdd/serenity-core/files/308764/com.zip)

**Comment by wakaleo** [comment] 2016-06-10 09:54
Could you try with 1.1.37-rc.3?

**Comment by pisarenco92** [comment] 2016-06-10 09:56
Here is a simple project:
[com.zip](https://github.com/serenity-bdd/serenity-core/files/308770/com.zip)

**Comment by wakaleo** [comment] 2016-06-10 16:12
This is actually a different issue, due to a problem with the GSON serialisation. It will be fixed in the next release.

**Closed** 2016-06-10 16:14 UTC
Labels: waiting for feedback
