### ISSUE TITLE
waitUntilVisible is waiting for 0 sec only

### ISSUE THREAD

**Issue by vikram-6wunderkinder** [serenity-bdd/serenity-core#34] opened 2015-03-09 14:35 UTC
This method was working in thucydides but broken in serenity

org.openqa.selenium.ElementNotVisibleException: Timed out after 0 seconds waiting for net.serenitybdd.core.pages.WebElementFacadeImpl$1@6b01af7

Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'

System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_60'

Driver info: driver.version: unknown

Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'

System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_60'

Driver info: driver.version: unknown

at net.serenitybdd.core.pages.WebElementFacadeImpl.throwErrorWithCauseIfPresent(WebElementFacadeImpl.java:632)

at net.serenitybdd.core.pages.WebElementFacadeImpl.waitUntilVisible(WebElementFacadeImpl.java:609)

Please look into this

thanks & regards,
Vikram

**Comment by vikram-6wunderkinder** [comment] 2015-03-09 15:05
This method calls elementIsDisplayed() and it checks if element is currently visible , isn't it suppose to wait for default 30 seconds ? As method name itself says "waitfor..." 

same queries for other methods in WebElementFacadeImpl.java

**Comment by wakaleo** [comment] 2015-03-25 23:39
Are you still getting this issue in the latest Serenity version?

**Comment by wakaleo** [comment] 2015-04-23 14:48
I'll close this issue as I could not reproduce the issue in the latest version. Please reopen if it reoccurs in Serenity 1.0.47+

**Closed by wakaleo** 2015-04-23 14:48 UTC
