### ISSUE TITLE
net.serenity-bdd:serenity-jbehave-archetype throws SurefireReflectionException

### ISSUE THREAD

**Issue by SreeCharanShroff** [serenity-bdd/serenity-core#85] opened 2015-06-25 16:23 UTC
1. Do: 
mvn archetype:generate -Dfilter=net.serenity-bdd:serenity-jbehave-archetype
fill all details
2. Update pom.xml to:
<includes>
                        <include>**/*Test*.java</include>
                        <include>**/When*.java</include>
</includes>
3. mvn clean verify

Expected:
No errors

Actuals:
Even though tests are executed, build fails, throws:

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.987 sec
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: org.apache.maven.surefire.testset.TestSetFailedException: java.lang.NullPointerException; nested exception is java.lang.NullPointerException: null
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:166)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:63)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:139)
	... 9 more
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.maven.surefire.junitcore.ConcurrentReporterManager.getTestSet(ConcurrentReporterManager.java:157)
	at org.apache.maven.surefire.junitcore.ConcurrentReporterManager.testStarting(ConcurrentReporterManager.java:105)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.testStarted(JUnit4RunListener.java:87)
	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:115)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:61)
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:112)
	at de.codecentric.jbehave.junit.monitoring.JUnitScenarioReporter.beforeStory(JUnitScenarioReporter.java:100)
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeStory(DelegatingStoryReporter.java:67)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStory(ConcurrentStoryReporter.java:112)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:284)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:239)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:182)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:233)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] 
[INFO] --- serenity-maven-plugin:1.0.53:aggregate (serenity-reports) @ automation ---
Merging requirements = []
Merging requirements = []
Merged requirements set = []
[INFO] Reading requirements from net.thucydides.core.requirements.FileSystemRequirementsTagProvider@eb6ec6
[INFO] Reading requirements from net.thucydides.core.requirements.PackageAnnotationBasedTagProvider@34d45ec0
[INFO] Requirements found:[]
[INFO] REPORTS GENERATED IN C:\temp\SerenityDemos\automation\target\site\serenity
[INFO] REPORT HOME PAGE: C:\temp\SerenityDemos\automation\target\site\serenity\index.html
[INFO] Generating release reports for: []
[INFO] 
[INFO] --- maven-failsafe-plugin:2.12:verify (default) @ automation ---
[INFO] Failsafe report directory: C:\temp\SerenityDemos\automation\target\failsafe-reports
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.569 s
[INFO] Finished at: 2015-06-25T21:52:54+05:30
[INFO] Final Memory: 22M/232M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.12:verify (default) on project automation: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\temp\SerenityDemos\automation\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by YamStranger** [comment] 2015-11-22 16:07
Hello @SreeCharanShroff, I can't reproduce this issue on current version of serenity. 

Please provide additional details. 

If this issue already fixed, and you can not reproduce it as well as me - please close it. 

Thanks a lot!

**Comment by YamStranger** [comment] 2015-12-02 12:14
It seems that this issue already fixed, and can be closed.

**Closed by YamStranger** 2015-12-02 12:14 UTC
