### ISSUE TITLE
Incompatible hamcrest 1.3 with mockito-all (inner hamcrest 1.1)

### ISSUE THREAD

**Issue by ihostage** [serenity-bdd/serenity-core#111] opened 2015-08-12 13:21 UTC
Discussed http://stackoverflow.com/questions/18770943/mockito-junit-hamcrest-versioning/31702824
```
java.lang.NoSuchMethodError: org.hamcrest.core.AnyOf.anyOf([Lorg/hamcrest/Matcher;)Lorg/hamcrest/core/AnyOf;
	at org.hamcrest.text.IsEmptyString.<clinit>(IsEmptyString.java:18)
	at org.hamcrest.Matchers.isEmptyOrNullString(Matchers.java:1255)
```
I don't know very well Gradle, unlike Мaven :smile: 
May be you can remove deprecated dependecy 'mockito-all' and change it to 'mockito-core'?

This patch is compiled, but i'm not sure what it correct for Gradle :pensive: 
```patch
diff --git a/build.gradle b/build.gradle
index eef2477..2d5b39a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -202,7 +202,7 @@ subprojects {
         testCompile "org.hamcrest:hamcrest-integration:${hamcrestVersion}"
         testCompile "org.hamcrest:hamcrest-library:${hamcrestVersion}"
         testCompile "org.hamcrest:hamcrest-core:${hamcrestVersion}"
-        compile('org.mockito:mockito-all:1.10.18') {
+        compile('org.mockito:mockito-core:1.10.19') {
             exclude group: "org.hamcrest"
         }
         testCompile('org.spockframework:spock-core:1.0-groovy-2.3') {
@@ -221,9 +221,6 @@ subprojects {
 
     configurations.all {
         resolutionStrategy.eachDependency { DependencyResolveDetails details ->
-            if (details.requested.name == 'mockito-all') {
-                details.useTarget group: 'org.mockito', name: 'mockito-core', version: '1.10.19'
-            }
             if (details.requested.name == 'hamcrest-core') {
                 details.useTarget group: 'org.hamcrest', name: 'hamcrest-core', version: "${hamcrestVersion}"
             }
diff --git a/serenity-rest-assured/build.gradle b/serenity-rest-assured/build.gradle
index 5c8f5ff..2dc9607 100644
--- a/serenity-rest-assured/build.gradle
+++ b/serenity-rest-assured/build.gradle
@@ -13,5 +13,5 @@ dependencies {
         exclude group: 'org.codehaus.groovy', module:'groovy-xml'
     }
     compile "net.bytebuddy:byte-buddy:0.6.5"
-    compile "org.mockito:mockito-all:1.10.18"
+    compile "org.mockito:mockito-core:1.10.19"
 }

```

**Comment by ihostage** [comment] 2015-08-12 13:25
Now i use work around. I don't use *Serenity* transitive dependencies and set dependency for hamcrest directly in my pom.xml
```xml
<dependency>
  <groupId>org.hamcrest</groupId>
  <artifactId>hamcrest-core</artifactId>
  <version>1.3</version>
  <scope>compile</scope>
</dependency>
```

**Comment by ihostage** [comment] 2015-08-13 10:31
A similar problem in **serenity-maven-plugin**
```
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.1.4:aggregate (serenity-reports) on project ussitest: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.1.4:aggregate failed: An API incompatibility was encountered while executing net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.1.4:aggregate: java.lang.NoSuchMethodError: org.hamcrest.CoreMatchers.startsWith(Ljava/lang/String;)Lorg/hamcrest/Matcher;
```

work around, set dependency for hamcrest directly 
```xml
<plugin>
  <groupId>net.serenity-bdd.maven.plugins</groupId>
  <artifactId>serenity-maven-plugin</artifactId>
  <version>${serenity.plugin.version}</version>
  <dependencies>
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-core</artifactId>
      <version>1.3</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-core</artifactId>
      <version>${serenity.version}</version>
    </dependency>
  </dependencies>
  <executions>
    <execution>
      <id>serenity-reports</id>
      <phase>post-integration-test</phase>
      <goals>
        <goal>aggregate</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

**Comment by Invictum** [comment] 2015-08-13 11:27
Try to apply mentioned solution for maven, but got the same error.

**Comment by ihostage** [comment] 2015-08-13 11:31
Are you sure what hamcrest dependency before serenity-core? This is important. And ``${serenity.plugin.version}`` should be equals ``${serenity.version}``

**Comment by Invictum** [comment] 2015-08-13 11:44
Yeap, dependency order fix it) Thanks for solution.

**Comment by derTobsch** [comment] 2015-08-18 07:47
I got this error since 1.1.4 - does anyone has an idea? 
<pre>
net.thucydides.core.webdriver.WebdriverAssertionError: java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V
</pre>

**Comment by ilkomiliev** [comment] 2015-08-18 08:48
Are you using maven? Have you applied the proposed workarounds here? Perhaps mockito-all is defined as dependency in another jar? Otherwise a long search will be necessary comparing incompatible versions - I've gone through it...

**Comment by ihostage** [comment] 2015-08-18 09:01
*Problem*: mockito-all contains classes from **hamcrest-1.1**. Serenity, JUnit and other, has transitive dependency from **hamcrest-1.3**. As a result, classes in conflict.
*Work around*: ClassLoader need find **hamcrest-1.3** before **mockito-all**. For this, in your build tools (maven, gradle, etc) you need define dependency from **hamcrest-1.3** directly and before mockito-all.
PS: for maven, look previous comments.

**Comment by wakaleo** [comment] 2015-08-18 09:08
This is a bug with the Gradle generation of the Maven pom files - should be
fixed in 1.1.5 (which is now out).

On 18 August 2015 at 09:48, ilkomiliev <notifications@github.com> wrote:

> Are you using maven? Have you applied the proposed workarounds here?
> Perhaps mockito-all is defined as dependency in another jar? Otherwise a
> long search will be necessary comparing incompatible versions - I've gone
> through it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/111#issuecomment-132122368>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ihostage** [comment] 2015-08-18 09:20
Good news :+1:  John, fix in this commit https://github.com/serenity-bdd/serenity-core/commit/ed62f9307eb62e79ba8a880b4c54b64b7a14f1b2?

**Comment by derTobsch** [comment] 2015-08-18 14:58
We are using 1.1.5 in every dependency we are using now (core,maven and junit). But we got similar errors since then

<pre>
net.thucydides.core.webdriver.WebdriverAssertionError: java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V
</pre>

**Comment by wakaleo** [comment] 2015-08-18 15:44
Do you have a stack dump?

On 18 August 2015 at 15:58, Tobias Schneider <notifications@github.com>
wrote:

> We are using 1.1.5 in every dependency we are using now (core,maven and
> junit). But we got similar errors since then
>
> net.thucydides.core.webdriver.WebdriverAssertionError: java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/111#issuecomment-132240048>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by derTobsch** [comment] 2015-08-19 07:04
i took a deeper look and the failures depends on 'org.hamcrest.Matchers.hasItems'. Because that is not provided? 'org.hamcrest.CoreMatchers.hasItems' is not available in CoreMatchers. Seems weird because that should be there.

Got the Thread dump for you:
<pre>
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at net.contargo.imtis.webtests.steps.management.price.PriceManagementSteps.then_new_main_run_price_has_values_pre_filled(PriceManagementSteps.java:875)
	  at net.contargo.imtis.webtests.steps.management.price.PriceManagementSteps$$EnhancerByCGLIB$$cdedbaa9.CGLIB$then_new_main_run_price_has_values_pre_filled$49(<generated>:-1)
	  at net.contargo.imtis.webtests.steps.management.price.PriceManagementSteps$$EnhancerByCGLIB$$cdedbaa9$$FastClassByCGLIB$$d3512e54.invoke(<generated>:-1)
	  at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	  at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:334)
	  at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:319)
	  at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:296)
	  at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:129)
	  at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:56)
	  at net.contargo.imtis.webtests.steps.management.price.PriceManagementSteps$$EnhancerByCGLIB$$cdedbaa9.then_new_main_run_price_has_values_pre_filled(<generated>:-1)
	  at net.contargo.imtis.webtests.features.management.price.LumpsumPriceTest.check_for_working_main_run_price_duplication(LumpsumPriceTest.java:220)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:497)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at net.serenitybdd.junit.runners.SerenityStatement.evaluate(SerenityStatement.java:24)
	  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	  at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:440)
	  at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:60)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:249)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
</pre>

The Exception will be thrown in MethodProxy in line 124.
--

I tested every combination of the dependencies from 1.1.3 to 1.1.5 and the problem is serenity-core since version 1.1.4 (also 1.1.5)

**Comment by Invictum** [comment] 2015-08-19 07:48
Detected the same issue with assertion with 'org.hamcrest.CoreMatchers.equalTo'.
Reproduced on core 1.1.5.

**Comment by derTobsch** [comment] 2015-08-19 07:58
@Invictum equalTo will be used in hasItems. Good to know its not only me :)

**Comment by wakaleo** [comment] 2015-08-19 08:11
It's due to a bug in the way Gradle produces the pom files which fails to
exclude the hamcrest 1.1 dependency somewhere - the workaround is to
include a dependency on hamcrest 1.3 at the top level of your project.

On 19 August 2015 at 08:58, Tobias Schneider <notifications@github.com>
wrote:

> @Invictum <https://github.com/Invictum> equalTo will be used in hasItems.
> Good to know its not only me :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/111#issuecomment-132482429>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by ihostage** [comment] 2015-08-26 13:08
John, in version 1.1.6 this commit https://github.com/serenity-bdd/serenity-core/commit/743ec7b5c289e575057fbc78b448f6d08f5c6e0a fix issue?

**Comment by derTobsch** [comment] 2015-08-26 13:13
it seems. i upgraded all to 1.1.6 and all tests are running. Thanks!

**Comment by ihostage** [comment] 2015-08-26 13:15
:+1:

**Closed** 2015-09-01 01:27 UTC

**Comment by marcandreuf** [comment] 2017-03-31 13:33
By folloing instructions in this issue.

This gradle configuration worked for me to fix this issue.

```
dependencies {
.....
    testCompile("junit:junit:4.12"){
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    //hamcrest must be loaded before mockito-all for issues in hamcrest classes !! 
    testCompile group: 'org.hamcrest', name: 'hamcrest-core', version: '1.3'
    testCompile group: 'org.assertj', name: 'assertj-core', version: '3.6.2'
    testCompile group: 'org.mockito', name: 'mockito-all', version: '1.10.19'
}
```

**Comment by wakaleo** [comment] 2017-03-31 13:43
Thanks for the update Marc.

**Comment by tungnk0711** [comment] 2021-08-19 17:49
> Yeap, dependency order fix it) Thanks for solution.

but not hasSize()
