### ISSUE TITLE
@Pending, @WIP doesn't take effect in report

### ISSUE THREAD

**Issue by pekra** [serenity-bdd/serenity-core#172] opened 2015-11-10 06:24 UTC
Hi,

actual I'm using:
serenity-core: 1.1.2
serenity.maven.plugin.version: 1.1.2
serenity.cucumber.version: 1.1.1

on this stack tagging Cucumber Features or Scenarios with @wip @pending @skip doesn't take any effect on the report which is generated at the end of test execution. 

Also updating to the latest serenity-core version doesn't have any effect on that issue.

Regards
Peter

**Comment by cliviu** [comment] 2015-11-11 10:58
Hi @pekra , I was not able to reproduce your problem using  the current serenity demo project
https://github.com/serenity-bdd/serenity-demos/tree/master/cucumber-webtests .
After annotating a scenario with @pending, I had the following output in the reports: 
![cucumber_pending](https://cloud.githubusercontent.com/assets/2623175/11089585/2bdbabe0-886b-11e5-8cd8-3db3e39de2fe.png)

![cucumber_pending_1](https://cloud.githubusercontent.com/assets/2623175/11089587/37a5c8f2-886b-11e5-847b-4d83a453544f.png)

Can you please provide us more informations to be able to reproduce the problem ?

**Comment by cliviu** [comment] 2015-11-11 11:05
ok, now I see : the tags are case sensitive : you should use exactly @pending, @wip, @skip

**Comment by YamStranger** [comment] 2015-11-24 22:41
Hello @pekra!

Please check answer from @cliviu. 

If this issue can be solved by following this advice - please close it. 

Thanks a lot!!

**Comment by YamStranger** [comment] 2015-12-02 12:13
It seems that this issue can be closed

**Closed** 2015-12-02 12:13 UTC
