### ISSUE TITLE
Broken links in index.html serenity jbehave older version

### ISSUE THREAD

**Issue by jaspreetmanchinda** [serenity-bdd/serenity-core#927] opened 2017-09-14 11:28 UTC
I have multiple projects running on older version of serenity 

```
    1.) <serenity.version>1.1.36</serenity.version>
    	<serenity.jbehave.version>1.13.0</serenity.jbehave.version>
    
    2.) <serenity.version>1.1.42</serenity.version>
    	<serenity.jbehave.version>1.12.0</serenity.jbehave.version>
```

but broken links are getting generated in the index.html.

Cannot update version to latest version as it is causing internal dependency issue.

I would like to understand what is the actual cause for the same and which dependency conflict can cause the issue.

**Comment by wakaleo** [comment] 2017-09-14 11:35
The algorithm to generate the file names changed, which means that you will get broken links if you use incompatible version of the libraries. Your best bet is to resolve your dependency conflicts and upgrade to the latest version.

**Comment by jaspreetmanchinda** [comment] 2017-09-14 11:55
Agreed, that is what I wanted to know, which dependencies can break the algorithm.

**Comment by wakaleo** [comment] 2017-09-14 12:08
Look at the serenity-jbehave poms, and see what versions of serenity-core they are using.

**Comment by jaspreetmanchinda** [comment] 2017-09-14 13:05
in the first example above <serenity.jbehave.version>1.13.0</serenity.jbehave.version> is using <serenity.core>1.1.36</serenity.core> which is the same as dependency version mentioned in project pom.
What else can break the algorithm?

**Comment by wakaleo** [comment] 2017-09-14 13:06
Hard to tell

**Comment by wakaleo** [comment] 2017-09-23 07:21
Can you reproduce this issue with serenity-core 1.5.12 and serenity-jbehave 1.28.0?

**Comment by jaspreetmanchinda** [comment] 2017-09-25 04:05
Its working fine in latest version. Issue is earlier it was working fine in previous version too but it stopped working after I deleted my m2 and downloaded all the dependencies again, I am not sure if this is the issue here.

**Comment by wakaleo** [comment] 2017-09-25 06:10
It is due to running the aggregate command with a newer version of Serenity against test results from an older version. If it's working for you with the latest version I will close the issue.

**Comment by jaspreetmanchinda** [comment] 2017-09-25 06:13
there are different projects I an working on. I am using latest version for new project whereas in old project I am still getting that issue.

**Comment by wakaleo** [comment] 2017-09-25 06:14
The problem comes from incompatible library versions of Serenity (the core dependencies, the maven plugins, and jbehave or cucumber integration etc).

**Comment by wakaleo** [comment] 2017-10-31 23:29
Did you get this issue sorted out?

**Comment by wakaleo** [comment] 2017-11-06 16:15
Closed for inactivity.

**Closed by wakaleo** 2017-11-06 16:15 UTC
Labels: waiting for feedback
