### ISSUE TITLE
Serenity Report Summary shows the test as failed/error when actually passed on retry

### ISSUE THREAD

**Issue by mihaiserdean** [serenity-bdd/serenity-core#51] opened 2015-04-23 12:17 UTC
the maven command has the retry in case of failure/error
-Dsurefire.rerunFailingTestsCount=1 -Dmax.retries=1 -DJUNIT_RETRY_TESTS=true -Dwebdriver.timeouts.implicitlywait=31000 -Dwebdriver.wait.for.timeout=31000 -Dserenity.timeout=60 

also running the tests in parallel with batch_number 1 2 and batch_count = 2 in jenkins as multi configuration project and aggregating the results by copying the 2 batch_number target folders into one target folder and then executing mvn serenity:aggregate

using serenity 1.0.45

If a test fails or has errors, it will repeat it (once as specified above) and if it's passed, then in the serenity test report summary, it will mark it as failed/error: 200 passed , 0 pending, 0 failed, 1 with errors, although second run shows pass.
In the report in the tests table, clicking on that test, it will show the two runs (just as there were two rows in a csv file), one with error, one with pass (which is ok). so can you make the summary take the pass result and not show it with error? so "201 passed , 0 pending, 0 failed, 0 with errors".

in thucydides 0.9.275, the report top summary showed correctly for the above scenario. in the test titles table it was marked as error, but in the top summary it stated all pass.

**Comment by wakaleo** [comment] 2015-04-23 23:41
I'm not able to reproduce this - both surefire.rerunFailingTestsCount (or failsafe.rerunFailingTestsCount)  and max.retries seem to work fine, independently or together. Note that they are totally separate implementations (the surefile.rerunFailingTestsCount property was implemented after the Thucydides one), so probably not a good idea to combine them. Do you have a sample project that reproduces this issue?

**Comment by wakaleo** [comment] 2015-05-05 21:02
Could you see if this happens with 1.0.47 and, if so, create a sample project that reproduces the issue?

**Comment by mihaiserdean** [comment] 2015-05-06 10:56
I will update to 1.0.47 and delete the surefile.rerunFailingTestsCount property and let you know if I reproduce it.

**Comment by afcbpeter** [comment] 2015-05-18 13:53
Hi,

I'm having this issue as well on 1.0.47. The test passes in the Maven Build but Serenity isn't having it.

The faliure I get is this. expected:<[Logout]> but was:<[]> which says to me it's not finding the element, but why would the Maven build pass? the output fail and the Jenkins build show as failed also.

**Comment by wakaleo** [comment] 2015-05-18 20:37
Could you provide a sample project that reproduces this issue?

**Comment by rrussell39** [comment] 2015-05-18 21:17
Ok - since posting this I have got it to work.  I had to set this property on the command line:
thucydides.outputDirectory=target/site/thucydides
The tricky part is that the log warnings indicate:
2015-05-18 14:12:46,919 [main] WARN  net.thucydides.core.ThucydidesSystemProperty.legacyPropertyValueIfPresentIn:712 Legacy property format detected for thucydides.outputDirectory, please use the serenity.* format instead.
However, using serenity.outputDirectory DOES NOT work.  Further, setting either value in the thucydides.properties file DOES NOT work.
Is that a bug?

**Comment by YamStranger** [comment] 2015-11-11 11:32
@mihaiserdean this issue quite similar to #132. May be next tips will be helpful
* to be sure that you are talking about  serenity reports (ander serenity output dir). They are builds after gradle reports. Here you can find details [configuration](http://thucydides.info/docs/serenity-staging/#_building_serenity_projects_in_gradle). Gradle reports can be rad, but serenity-reports should be green. 
* try run [example project](https://github.com/serenity-bdd/serenity-demos/tree/master/junit-webtests) (I tested it with gradle 2.5). Clone it from git, remove all from serenity.properties. And run ```gradle clean test aggregate```. You will find two reports: - fail under build/** and successful under target/serernity/site (default path for serernity reports).

If you will have some additional questions - please ask them

**Comment by YamStranger** [comment] 2015-11-19 07:49
Hello @mihaiserdean!

This should be closed under 1.1.22-rc.5.

Please close it, if so

**Closed** 2015-11-27 13:47 UTC
