### ISSUE TITLE
Test result summary doesn't show ignored test

### ISSUE THREAD

**Issue by g-dimartino** [serenity-bdd/serenity-core#756] opened 2017-04-08 21:03 UTC
I have created a new project using serenity through cucumber JUnit tests, but even if I tag a scenario with @ignore, @ignored, @skip or @wip it is not showing up in the test result summary as an ignored scenario.

In the tests list the scenarios are all marked as skipped, but not in the test result summary nor in the pie chart.

Here is my result summary
![schermata 2017-04-08 alle 21 59 40](https://cloud.githubusercontent.com/assets/27094466/24832379/bf673f66-1ca6-11e7-9278-37fcbc1f8e29.png)

And here is my test list
![schermata 2017-04-08 alle 21 59 55](https://cloud.githubusercontent.com/assets/27094466/24832380/bf7f5a56-1ca6-11e7-9093-ddec2e41f5be.png)

And here is my feature file
@Story:Test-01
Feature: Test serenity integration

	Scenario: Execute a dummy test to check the serenity runner
		Given I am using cucumber
		When I run the project
		Then the steps are executed

	Scenario: Execute a dummy failing test to check the serenity report
		Given I am using cucumber
		When I run the project
		Then the final step fail

	Scenario: Execute a dummy compromised test to check the serenity report
		Given I am using cucumber
		When I run the project
		Then the final step is compromised

	@pending
	Scenario: Execute a dummy test with pending annotation
		Given I am using cucumber
		When I run the project
		Then the steps are executed

	@wip
	Scenario: Execute a dummy test with wip annotation
		Given I am using cucumber
		When I run the project
		Then the steps are executed

	@ignore
	Scenario: Execute a dummy test with ignore annotation
		Given I am using cucumber
		When I run the project
		Then the steps are executed

	@ignored
	Scenario: Execute a dummy test with ignored annotation
		Given I am using cucumber
		When I run the project
		Then the steps are executed

	@skip
	Scenario: Execute a dummy test with skip annotation
		Given I am using cucumber
		When I run the project
		Then the steps are executed

	@manual
	Scenario: Execute a dummy test with manual annotation
		Given I am using cucumber
		When I run the project
		Then the steps are executed

Am I missing something?

**Comment by wakaleo** [comment] 2017-04-08 21:07
What version are you using?

**Comment by g-dimartino** [comment] 2017-04-08 23:18
<serenity.version>1.2.2</serenity.version>
<serenity.cucumber.version>1.1.23</serenity.cucumber.version>

**Comment by wakaleo** [comment] 2017-04-11 10:46
There were some fixes in this area in the latest versions, try with 1.2.5-rc.2 and 1.1.28

**Comment by g-dimartino** [comment] 2017-04-11 19:18
I've updated the versions but I have exactly the same issue:
pie chart and result summary are not showing those test;
related tags show them as ignored (in grey colour);
tests list fast-forward them.

**Comment by wakaleo** [comment] 2017-04-11 19:20
Can you produce a sample project to reproduce the issue?

**Comment by g-dimartino** [comment] 2017-04-11 19:33
[restAPI-test-framework.zip](https://github.com/serenity-bdd/serenity-core/files/914459/restAPI-test-framework.zip)

**Comment by wakaleo** [comment] 2017-04-11 20:15
Should be fixed in the next release.

**Closed** 2017-04-11 20:14 UTC

**Comment by g-dimartino** [comment] 2017-04-11 20:20
Have you found what was the issue?
Do I need to update something on my project?

**Comment by wakaleo** [comment] 2017-04-11 20:21
Yes, SKIPPED tests weren't being counted correctly. The fix will be available in the next release.

**Comment by g-dimartino** [comment] 2017-04-11 20:24
Perfect, thank you.

**Comment by g-dimartino** [comment] 2017-04-11 22:21
I apologize if I bother you again, but looking at your commit I don't understand why the test outcome for the ignored scenario is "skipped" and not "ignored".
Moreover, looking at the console log of the execution, all the scenarios (with @pending, @wip, @ignore, @ignored, @skip and @manual) are actually executed before beeing marked as "Skipped" in the report.

**Comment by wakaleo** [comment] 2017-04-12 06:21
Ignore and Skip (including @wip, @ignore, @ignored, @skip) are basically synonyms - different testing frameworks have different terms for the same idea.

**Comment by wakaleo** [comment] 2017-04-12 06:22
They are still reported in the console, but not executed.

**Comment by g-dimartino** [comment] 2017-04-12 06:29
So it means that, for example, cucumber uses skipped and Jbehave uses ignored?
I've seen that if I perform a dry run the passing scenarios are marked as ignored both in result summary and in test list (with a (/) sign).

About the executions, if you look at my project, I've put a println in each step and I can see those lines in the console.

**Comment by wakaleo** [comment] 2017-04-12 06:31
Neither Cucumber or JBehave have the concept or handling of skipped or ignored tests; different projects and teams use different conventions. The top-level step definitions will be executed in Cucumber (we can't do anything about that, because it's run by Cucumber), but instrumented steps or tasks will be skilled.

**Comment by g-dimartino** [comment] 2017-04-12 06:36
What you mean by "instrumented steps"?

**Comment by wakaleo** [comment] 2017-04-12 06:37
Any method with the @Step annotation or any Screenplay Performable.

**Comment by g-dimartino** [comment] 2017-04-12 06:39
Ok, I will look into it; thanks again for your time.

**Comment by g-dimartino** [comment] 2017-04-12 19:32
Hello again,
I have created a Step library and called it from the cucumber steps, but the steps are still executed even if tagged with @pending and, even if the scenario is marked as skipped, the individual steps are marked as "success".

Here is my updated project:
[test-framework.zip](https://github.com/serenity-bdd/serenity-core/files/917638/test-framework.zip)

Am I missing something?
