### ISSUE TITLE
How to use chrome or edge in serenity screnplay bdd ?

### ISSUE THREAD

**Issue by jecardenasri01** [serenity-bdd/serenity-core#3221] opened 2023-08-11 21:56 UTC
serenity.conf file that works to run with microsoft edge
i  used net.serenity-bdd:serenity-gradle-plugin:3.9.8

_______
edge exit

{
  drivers {
    windows {
      webdriver.chrome.driver = src/test/resources/webdriver/chromedriver.exe
      webdriver.gecko.driver = src/test/resources/webdriver/geckodriver.exe
      webdriver.ie.driver = src/test/resources/webdriver/msedgedriver.exe
    }
  }

  webdriver {
    driver = "edge"
    autodownload = true

    timeouts {
      script = 15000
      pageLoad = 15000
      implicit = 15000
    }
    capabilities {
      browserName = "MicrosoftEdge"
      "ms:edgeOptions" {
        args = [
          "remote-allow-origins=*",
          "ignore-certificate-errors",
          "start-maximized",
          "incognito"]
      }
    },
  }
}
__________

this serenity.conf file that only execute correctly test whit chrome driver  i tried execute whit edge but failed

{
  drivers {
    windows {
      webdriver.chrome.driver = src/test/resources/webdriver/chromedriver.exe
      webdriver.gecko.driver = src/test/resources/webdriver/geckodriver.exe
      webdriver.ie.driver = src/test/resources/webdriver/msedgedriver.exe
    }
  }

  webdriver {
    driver = "chrome"
    autodownload = true

    timeouts {
      script = 15000
      pageLoad = 15000
      implicit = 15000
    }
    capabilities {
      browserName = "MicrosoftEdge"
      "ms:edgeOptions" {
        args = [
          "remote-allow-origins=*",
          "ignore-certificate-errors",
          "start-maximized",
          "incognito"
        ]
      }
    },
    capabilities {
      browserName = "chrome"
      "goog:chromeOptions" {
        args = [
          "remote-allow-origins=*",
          "ignore-certificate-errors",
          "start-maximized",
          "incognito"
        ]
      }
    }
  }
}

__________________
![image](https://github.com/serenity-bdd/serenity-core/assets/45072804/11390e94-42ea-465c-ac14-ab272b08b8b4)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError
WebDriver was unable to create a new instance of type class org.openqa.selenium.edge.EdgeDriver
WebDriver reported the following message: Could not start a new session. Response code 500. Message: session not created: No matching capabilities found 
Host info: host: 'IMAGEMAKER-PC', ip: '192.168.10.81'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.2'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [remote-allow-origins=*, ignore-certificate-errors, start-maximized, incognito]}, ms:edgeOptions: {args: [ignore-certificate-errors, start-maximized, incognito, remote-allow-origins=*, ignore-certificate-errors, start-maximized, incognito], extensions: []}}]}]
See below for more details.

**Comment by wakaleo** [comment] 2023-08-19 07:22
Duplicate of #3225

**Closed by wakaleo** 2023-08-19 07:22 UTC
