### ISSUE TITLE
() in Scenario leads to crash in result aggregation >> NullPointerException

### ISSUE THREAD

**Issue by SchnuckySchuster** [serenity-bdd/serenity-core#507] opened 2016-08-24 06:13 UTC
Scenario: This () will crash the aggregation step
Given i run this scenario
When the step aggregate runns
Then I will see a crash that looks like below and no index.html is created

[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (default) on project view-web-tests: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There wa
s an error in the forked process
org.apache.maven.surefire.testset.TestSetFailedException: java.lang.NullPointerException
        at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:213)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:109)
       at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
       at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.NullPointerException
        at org.apache.maven.surefire.junitcore.ConcurrentRunListener.testStarting(ConcurrentRunListener.java:129)
        at org.apache.maven.surefire.common.junit4.JUnit4RunListener.testStarted(JUnit4RunListener.java:91)
        at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
        at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
        at org.junit.internal.runners.model.EachTestNotifier.fireTestStarted(EachTestNotifier.java:42)
        at cucumber.runtime.junit.JUnitReporter.startExecutionUnit(JUnitReporter.java:50)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:89)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)

Mit besten Grüßen,
Gerhard Schuster

Raum                 22.00.54
Durchwahl       6253
Mobil                 0179/100633

Home Shopping Europe GmbH, Sitz: Ismaning, Amtsgericht München HR B 159494, Geschäftsführer: Richard Reitzner (Vorsitzender), Ralph Brugger, Sonja Piller, Jan Schulze, Aufsichtsratsvorsitzender: Dr. Konrad Hilbers
Der Inhalt dieser E-Mail oder eventueller Anhänge ist ausschließlich für den bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser E-Mail oder dessen Vertreter sein sollten, so beachten Sie bitte, dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen.
The information contained in this email is intended solely for the addressee. If you are not the intended recipient, any form of disclosure, reproduction, distribution or any action taken or re-frained from in reliance on it, is prohibited and may be unlawful. Please notify the sender immediately.

**Comment by wakaleo** [comment] 2016-08-24 06:36
Could you give an example of a scenario that causes this issue?

**Comment by SchnuckySchuster** [comment] 2016-08-24 06:39
Hi John,

what do you mean?
Didn't I post a scenario?

>Scenario: This () will crash the aggregation step
>Given i run this scenario
>When the step aggregate runns
>Then I will see a crash that looks like below and no index.html is created

**Comment by cliviu** [comment] 2016-09-06 22:27
Hi @SchnuckySchuster , I was not able to reproduce your problem. I have tried with a Cucumber scenario  having brackets () in title. Are you sure that the brackets () are causing the problem ?  Can you please try to run the scenario without the brackets ?

**Comment by SchnuckySchuster** [comment] 2016-09-08 06:42
Hi Liviu,

I'm very sure that the brackets are causing the problem.
- I'm running with serenity version 1.1.36
- I start the test with mvn clean verify
- I use jdk 1.8.0_71
Whenever I insert () into the scenario title I see the NullPointerException I've posted.
Whenever I remove the () there is no crash.

Try this here:

Scenario: This () will crash at result aggregation

It always crashes on my system.


If you still can't reproduce the issue, I would not mind if you drop it. I can live without () in the scenario title.





Mit besten Grüßen,
Gerhard Schuster 

Festnetz: 	08637/986157
Mobil: 		0179/1006330

Am 07.09.2016 um 00:27 schrieb Liviu Carausu <notifications@github.com>:

Hi @SchnuckySchuster , I was not able to reproduce your problem. I have tried with a Cucumber scenario having brackets () in title. Are you sure that the brackets () are causing the problem ? Can you please try to run the scenario without the brackets ?

**Comment by wakaleo** [comment] 2016-09-08 06:58
The error seems to be in the surefire plugin:

```
Caused by: java.lang.NullPointerException
at org.apache.maven.surefire.junitcore.ConcurrentRunListener.testStarting(ConcurrentRunListener.java:129)
```

I would put a breakpoint there to try to see what is going on.

**Comment by cliviu** [comment] 2016-09-08 06:59
It looks like a cucumber bug : https://github.com/cucumber/cucumber-jvm/issues/960

**Comment by wakaleo** [comment] 2017-01-05 13:22
I'm going to close this one as I don't think it is Serenity-related. Please feel free to reopen it if you can reproduce it in a sample project.

**Closed by wakaleo** 2017-01-05 13:22 UTC
