### ISSUE TITLE
Each test method clears cookie even though im using @Managed(uniqueSession = true)

### ISSUE THREAD

**Issue by breinjhel** [serenity-bdd/serenity-core#273] opened 2016-01-23 03:00 UTC
Hi,

My tests before is running ok until i upgraded to 1.1.24. Im always using 
@Managed(uniqueSession = true)
WebDriver driver;

So that each method will always use 1 browser session. But now I noticed my cookie are erased on each method. Like its a new session but still 1 browser.

Please help.

**Comment by breinjhel** [comment] 2016-01-23 03:04
I just read the changelog of 1.1.22 and I found this
 - When using a unique browser for multiple tests, clear the cookies and HTML local storage between tests.

Why do we do that. I need to have 1 session through out my tests.

**Comment by YamStranger** [comment] 2016-01-23 12:36
Hello @breinjhel! Thanks for this issue. 

I copied it from [manual](http://thucydides.info/docs/serenity-staging/#_serenity_webdriver_support_in_junit): 
>You can also get Serenity to open the browser at the start of the tests, and leave it open until all of the tests in this test case have been executed, using the uniqueSession parameter:

Do you use same browser (with same session) for same of test_case (for all tests in it) or same browser for different test_cases (and all tests for them)?

**Comment by breinjhel** [comment] 2016-01-23 13:54
Hi @YamStranger ,

I use uniqueSession to run all my tests in a single browser and single session so all cookies and localstorage from all tests are carried over.

I use it like each @Test methods are like steps. So for example:


@Test
public void step_1_add_client(){
 // Test here
}

@Test
public void step_2_delete_client(){

}

To make sure each tests are run in an order I use @FixMethodOrder(MethodSorters.NAME_ASCENDING) in Junit

**Comment by YamStranger** [comment] 2016-01-23 13:56
Thanks @breinjhel

**Comment by breinjhel** [comment] 2016-01-23 13:58
Thanks for the fast feedback @YamStranger

**Comment by wakaleo** [comment] 2016-02-04 08:22
This is as intended: the cookies and session data is cleared deliberately between each test, because this can interfere with subsequent tests that should in theory be independent. It is usually considered bad practice to have dependencies between your tests, or rely on a particular test execution order, as it makes running the test in isolation, filtering the tests, or running them in parallel much harder. The intent is to just keep the browser open so as to save the time required to open the browser for each test.

A possible work-around would be to add a property to the @Managed annotation to allow session data to be cleared or not explicitly, e.g.

```
@Managed(uniqueSession = true, clearCookies=Never)
WebDriver driver;
```
or
```
@Managed(uniqueSession = true, clearCookies=BeforeEachTest)
WebDriver driver;
```

**Comment by breinjhel** [comment] 2016-02-04 09:27
Nice! Thats what I just need. I know its bad practice to have dependent
tests but for my current test process I wanted to have each tests like
Adding user, Editing , Deleting, in different test methods and at the same
time run in order rather than have each tests do an Add user before cause
that would be redundant and to save lots of time. UI test can take really
long to finish.

Thanks!

**Comment by breinjhel** [comment] 2016-02-04 09:55
By the way is that parameter already in 1.1.24? I just used it ij my end
and im getting an error.

@Managed(uniqueSession = true, clearCookies = "Never")
WebDriver driver;

**Comment by wakaleo** [comment] 2016-02-04 09:58
No, it will be in the next release.

**Comment by breinjhel** [comment] 2016-02-04 10:00
Yeah I just read it right after I sent the reply lol :) Thanks.

**Comment by breinjhel** [comment] 2016-02-04 10:03
Anyway I love your work and I bought your book about BDD. What do you suggest we should do if we are creating a test script for a CRUD functionality of a UI. Do we create Add, Edit, Search Delete functionalities in different methods and have Add and Delete as @Before and @After each methods?

**Comment by wakaleo** [comment] 2016-02-04 10:09
Something like that. Ideally, I would have a different test for Add, Edit,
Search and Delete, and for the last three, I would use API calls or similar
to perform the Add and Delete operations in the @Before and @After methods,
without going through the UI for these.

On 4 February 2016 at 10:03, breinjhel <notifications@github.com> wrote:

> Anyway I love your work and I bought your book about BDD. What do you
> suggest we should do if we are creating a test script for a CRUD
> functionality of a UI. Do we create Add, Edit, Search Delete
> functionalities in different methods and have Add and Delete as @Before
> <https://github.com/Before> and @After <https://github.com/After> each
> methods?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/273#issuecomment-179743444>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7497151337
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by breinjhel** [comment] 2016-02-04 10:21
I see. Thats what Ive been doing but the current project I am testing
doesnt have Rest API. So I have to go to the UI. Also are you placing those
tests in 1 class? If so wouldnt that  conflict with a @Before Add user and
a single test for add user?

Thanks for your input.

**Comment by wakaleo** [comment] 2016-02-04 10:29
Can you ask the developers to give you access to a remote API (REST or
otherwise)? As you mentioned, going through the UI for each setup/teardown
is going to be very slow...

On 4 February 2016 at 10:21, breinjhel <notifications@github.com> wrote:

> I see. Thats what Ive been doing but the current project I am testing
> doesnt have Rest API. So I have to go to the UI. Also are you placing those
> tests in 1 class? If so wouldnt that conflict with a @Before Add user and
> a single test for add user?
>
> Thanks for your input.
> On Feb 4, 2016 6:10 PM, "John Ferguson Smart" <notifications@github.com>
> wrote:
>
> > Something like that. Ideally, I would have a different test for Add,
> Edit,
> > Search and Delete, and for the last three, I would use API calls or
> similar
> > to perform the Add and Delete operations in the @Before and @After
> methods,
> > without going through the UI for these.
> >
> > On 4 February 2016 at 10:03, breinjhel <notifications@github.com> wrote:
> >
> > > Anyway I love your work and I bought your book about BDD. What do you
> > > suggest we should do if we are creating a test script for a CRUD
> > > functionality of a UI. Do we create Add, Edit, Search Delete
> > > functionalities in different methods and have Add and Delete as @Before
> > > <https://github.com/Before> and @After <https://github.com/After> each
> > > methods?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/serenity-bdd/serenity-core/issues/273#issuecomment-179743444
> > >
> > > .
> > >
> >
> >
> >
> > --
> > ___________________________________________________
> > John Smart | Wakaleo Consulting | +44 7497151337
> > Making smart teams collaborate better
> > http://www.wakaleo.com | john.smart@wakaleo.com
> > ___________________________________________________
> >
> > We love breaking down silos and helping smart teams collaborate better!
> Ask
> > about our tailored on-site workshops in *Agile Requirements Discovery
> > <http://wakaleo.com/training/advanced-agile-requirements-workshop>*,
> > *Behaviour
> > Driven Development
> > <http://wakaleo.com/training/advanced-agile-requirements-workshop>*,
> > *Agile
> > Development Practices
> > <http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and
> > *Test
> > Automation
> > <
> >
> http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides
> > >*
> > !
> > ___________________________________________________
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/serenity-bdd/serenity-core/issues/273#issuecomment-179747912
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-core/issues/273#issuecomment-179752613>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7497151337
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by breinjhel** [comment] 2016-02-04 11:27
Thanks for the advice @wakaleo

**Comment by YamStranger** [comment] 2016-04-15 05:01
This enhancement already implemented

**Closed by YamStranger** 2016-04-15 05:01 UTC
Labels: enhancement
