### ISSUE TITLE
Serenity doesn't generate folders for report

### ISSUE THREAD

**Issue by RStrizhak** [serenity-bdd/serenity-core#550] opened 2016-09-25 16:20 UTC
Hi 

We try to update our automation framework to serenity-core 1.1.41 version and serenity-jbehave 1.13.0 version, but when we generate Report using command **mvn compile serenity:aggregate**  - Serenity doesn't generate folders for report (like bootstrap, css, datatables, jqtree, images, etc) and ultimately show this:
![image](https://cloud.githubusercontent.com/assets/5132567/18816505/60542836-8354-11e6-8247-0184d69967ab.png)

**Maven log:**
21:26:00 [test_suite] $ /opt/apache-maven-3.3.9/bin/mvn -f pom.xml -DSuite=Smoke compile serenity:aggregate -s settings.xml
21:26:02 [INFO] Scanning for projects...
21:26:03 [INFO]                                                                         
21:26:03 [INFO] ------------------------------------------------------------------------
21:26:03 [INFO] Building Test Framework 1.0-SNAPSHOT
21:26:03 [INFO] ------------------------------------------------------------------------
21:26:04 [INFO] 
21:26:04 [INFO] --- build-helper-maven-plugin:1.8:add-source (default) @ test-framework ---
21:26:05 [INFO] Source directory: /app/jenkins/workspace/test_suite/gensrc added.
21:26:05 [INFO] Source directory: /app/jenkins/workspace/test_suite/src/test/java added.
21:26:05 [INFO] Source directory: /app/jenkins/workspace/test_suite/src/main/java added.
21:26:18 [INFO] 
21:26:18 [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-framework ---
21:26:18 [INFO] Using 'UTF-8' encoding to copy filtered resources.
21:26:18 [INFO] Copying 447 resources
21:26:18 [INFO] 
21:26:18 [INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ test-framework ---
21:26:18 [INFO] Compiling 1463 source files to /app/jenkins/workspace/test_suite/target/classes
21:26:35 [INFO]                                                                         
21:26:35 [INFO] ------------------------------------------------------------------------
21:26:35 [INFO] Building Test Framework 1.0-SNAPSHOT
21:26:35 [INFO] ------------------------------------------------------------------------
21:26:35 [INFO] 
21:26:35 [INFO] --- serenity-maven-plugin:1.1.41:aggregate (default-cli) @ test-framework ---
21:26:36 [INFO] webdriver.driver=chrome
21:26:36 [INFO] serenity.timeout=10
21:26:36 [INFO] serenity.test.root=com.auto.framework
21:26:36 [INFO] serenity.take.screenshots=FOR_FAILURES
21:26:36 [INFO] serenity.maintain.session=true
21:26:36 [INFO] webdriver.timeouts.implicitlywait=5000
21:26:36 [INFO] jira.url=https://jira.qwerty.com
21:26:36 [INFO] webdriver.wait.for.timeout=30000
21:26:36 [INFO] current_project.base.dir: /app/jenkins/workspace/test_suite
21:26:36 Generating HTML Story Reports from /app/jenkins/workspace/test_suite/target/site/serenity
21:26:36 Generating HTML Story Reports to /app/jenkins/workspace/test_suite/target/site/serenity
21:29:55 GENERATE CUSTOM REPORTS
21:29:55 [INFO] ------------------------------------------------------------------------
21:29:55 [INFO] BUILD SUCCESS
21:29:55 [INFO] ------------------------------------------------------------------------
21:29:55 [INFO] Total time: 03:53 min
21:29:55 [INFO] Finished at: 2016-09-24T21:29:55+03:00
21:29:56 [INFO] Final Memory: 71M/1676M
21:29:56 [INFO] ------------------------------------------------------------------------

We execute parallel running tests on the several Batches(folders for report exist here), copy artifacts(just files) to main job and generate report.

If we use single run: **mvn -f pom.xml integration-test serenity:aggregate -s settings.xml** - everything works OK.

Please help how to solve this issue?

**Comment by RStrizhak** [comment] 2016-09-25 19:48
I have done investigation:

### - if I use 1.1.36 or below
mvn clean
mvn serenity:aggregate
Folders for report in target\site\serenity were generated and I see correct Serenity report

### - if I use 1.1.38 or above
mvn clean
mvn serenity:aggregate
Folders for report in target\site\serenity were *NOT* generated

Why did you remove it from serenity:aggregate? :(

**Comment by wakaleo** [comment] 2016-09-25 22:21
The reports should be generated normally, so if they are not being generated, something is interfering with the report generation process. This could be a dependency conflict with other dependencies in your project. Could you check your logs for other errors?

**Comment by klimapro** [comment] 2016-09-26 06:03
Dear John,
Unfortunately i have same behavior as RStrizhak. 
And I have done investigation with new Serenity project, from scratch. 
I have generate Serenity project from archetype and perform same steps:

mvn clean
mvn serenity:aggregate

Empty report is observed:

**Comment by wakaleo** [comment] 2016-09-26 06:12
What version of JUnit are you using?

**Comment by klimapro** [comment] 2016-09-26 06:14
John,
```
<dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
</dependency>
```
At this moment, this version is default for Serenity archetype.

**Comment by wakaleo** [comment] 2016-09-26 06:24
Can you produce a sample project reproducing the issue?

**Comment by klimapro** [comment] 2016-09-26 06:45
John,
Yes, i can.

```
**$ mvn archetype:generate -Dfilter=net.serenity-bdd:serenity-jbehave-archetype**
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Choose archetype:
1: remote -> net.serenity-bdd:serenity-jbehave-archetype (Serenity automated acceptance testing project using Selenium 2, JUnit and JBehave)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): : 1
Choose net.serenity-bdd:serenity-jbehave-archetype version:
1: 1.0.2
2: 1.0.6
3: 1.0.7
4: 1.0.8
5: 1.1.7
6: 1.1.17
7: 1.1.18
8: 1.1.19
9: 1.1.20
10: 1.1.36
11: 1.1.38
Choose a number: 11: 11
Downloading: https://repo.maven.apache.org/maven2/net/serenity-bdd/serenity-jbehave-archetype/1.1.38/serenity-jbehave-archetype-1.1.38.jar
Downloaded: https://repo.maven.apache.org/maven2/net/serenity-bdd/serenity-jbehave-archetype/1.1.38/serenity-jbehave-archetype-1.1.38.jar (7 KB at 10.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/serenity-bdd/serenity-jbehave-archetype/1.1.38/serenity-jbehave-archetype-1.1.38.pom
Downloaded: https://repo.maven.apache.org/maven2/net/serenity-bdd/serenity-jbehave-archetype/1.1.38/serenity-jbehave-archetype-1.1.38.pom (712 B at 3.2 KB/sec)
Define value for property 'groupId': : com.klymenko.vadym
Define value for property 'artifactId': : serenityReport
Define value for property 'version':  1.0-SNAPSHOT: :
Define value for property 'package':  com.klymenko.vadym: :
Confirm properties configuration:
groupId: com.klymenko.vadym
artifactId: serenityReport
version: 1.0-SNAPSHOT
package: com.klymenko.vadym
 Y: : Y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: serenity-jbehave-archetype:1.1.38
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.klymenko.vadym
[INFO] Parameter: artifactId, Value: serenityReport
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: com.klymenko.vadym
[INFO] Parameter: packageInPathFormat, Value: com/klymenko/vadym
[INFO] Parameter: package, Value: com.klymenko.vadym
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: groupId, Value: com.klymenko.vadym
[INFO] Parameter: artifactId, Value: serenityReport
[INFO] project created from Archetype in dir: C:\JavaProjects\SerenityEmptyReport\serenityReport
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min
[INFO] Finished at: 2016-09-26T09:40:53+03:00
[INFO] Final Memory: 18M/320M
[INFO] ------------------------------------------------------------------------

```
After that, i perform:

```
mvn clean
mvn serenity:aggregate
```
And behavior the same, pure HTML report.

**Comment by wakaleo** [comment] 2016-09-26 06:50
Running "serenity:aggregate" will not run the tests, so this command will produce an empty report. Do you get the same behaviour when you run "mvn verify"?

**Comment by sudheerpujar** [comment] 2016-09-26 07:14
Hi John,
I have same issue with other two options (3 and 4) of -Dfilter=serenity and version 1.1.38.
Report generates perfectly fine for version 1.1.36 but there other failures related to  webdriver.
Please refer the issue #549 report by me.  I will add more details today at some point of time.

**Comment by klimapro** [comment] 2016-09-26 07:22
John,
Yes, serenity:aggregate produce an empty report, and when we perform mvn verify - it start tests and report is correct. But problem occurs for empty report in my case, and empty reports displayed correctly on older versions. 
And how to mention RStrizhak, the behavior is observed when copy artifacts from several batches in one **\target\site\serenity** folder.

**Comment by wakaleo** [comment] 2016-09-26 07:24
So the problem only occurs when you generate a report with no test outcomes?

**Comment by sudheerpujar** [comment] 2016-09-26 07:26
John,
Root cause seems to me is this 

**character to be escaped is missing**

```
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
at java.util.regex.Matcher.replaceAll(Matcher.java:955)
at java.lang.String.replaceAll(String.java:2223)
at net.thucydides.core.requirements.classpath.NarrativeText.definedIn(NarrativeText.java:16)
at net.thucydides.core.requirements.classpath.NonLeafRequirementsAdder.to(NonLeafRequirementsAdder.java:61)
at net.thucydides.core.requirements.PackageRequirementsTagProvider.addRequirementsDefinedIn(PackageRequirementsTagProvider.java:199)
at net.thucydides.core.requirements.PackageRequirementsTagProvider.requirementsReadFromClasspath(PackageRequirementsTagProvider.java:113)
```

**Comment by klimapro** [comment] 2016-09-26 07:31
John, not only for no test outcomes,
Problem occurs on Jenkins when perform parallel run of tests, and copy artifacts from several bathces in one **\target\site\serenity** folder. 

> We execute parallel running tests on the several Batches(folders for report exist here), copy artifacts(just files) to main job and generate report.

**Comment by wakaleo** [comment] 2016-09-26 07:54
What Operating System is your Jenkins server running on?

**Comment by klimapro** [comment] 2016-09-26 08:26
John,
For executing parallel - On Jenkins servers is CentOS release 6.6 (Final)
For empty report when no test outcomes - Win7, Win10, MacOs.
It seems, that is no matter which OS is installed.

**Comment by wakaleo** [comment] 2016-09-26 08:30
@klimapro: Are you getting the same "java.lang.IllegalArgumentException: character to be escaped is missing" error that @sudheerpujar reported?

**Comment by RStrizhak** [comment] 2016-09-26 08:48
Hi John,
Did you try to reproduce this issue on serenity 1.1.41 version?

We don't get any Exceptions during generate Serenity Report, see log:

> mvn serenity:aggregate
> [INFO] Scanning for projects...
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building est Framework 1.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- serenity-maven-plugin:1.1.41:aggregate (default-cli) @ test-framework ---
> [INFO] webdriver.driver=chrome
> [INFO] serenity.timeout=10
> [INFO] serenity.test.root=com.qwerty.qwerty
> [INFO] serenity.take.screenshots=FOR_FAILURES
> [INFO] serenity.maintain.session=true
> [INFO] webdriver.timeouts.implicitlywait=5000
> [INFO] jira.url=https://jira.qwerty.com
> [INFO] webdriver.wait.for.timeout=30000
> [INFO] current_project.base.dir: D:\WorkSpace\taf
> Generating HTML Story Reports from D:\WorkSpace\taf\target\site\serenity
> Generating HTML Story Reports to D:\WorkSpace\taf\target\site\serenity
> GENERATE CUSTOM REPORTS
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 13.824 s
> [INFO] Finished at: 2016-09-26T11:35:24+03:00
> [INFO] Final Memory: 28M/1211M
> [INFO] ------------------------------------------------------------------------

We use solution for parallel running tests described here https://dzone.com/articles/faster-web-tests-parallel (something like this with new Serenity interpretation)
> This job needs to copy the Thucydides report artifacts from the matrix build jobs into the current workspace, and then run the **mvn thucydides:aggregate** command to generate the Thucydides aggregate reports.

**now with Serenity 1.1.41 version it doesn't work**

Maybe you can suggest temporary decision for our case? Or is it possible to solve this issue in new Serenity version? I suppose serenity:aggregate should generate report in any conditions (no test outcomes, copied artifacts from Batches, after running test with mvn verify) :)

Thank you!

**Comment by wakaleo** [comment] 2016-09-26 08:58
I haven't reproduced anything except an issue with copying report resources when there are no test outcomes. I am more concerned with the issue of failing test reports when there are test outcomes, which may have been caused by the issue mentioned above. If you can provide an example of a sample project that produces this issue, that would help.

**Comment by RStrizhak** [comment] 2016-09-27 16:07
Hi John,

Uploaded [**project with test outcomes.**](http://www.filedropper.com/testproject_1) 

**Wrong** report generation using **1.1.41 version**:
1) Download, unzip project and execute **mvn serenity:aggregate** - check report - no folders for report at target\site\serenity directory
2) Next execute **mvn clean serenity:aggregate** - check report - no folders for report at target\site\serenity directory

**Correct** report generation using **1.1.36 version**:
3) unzip, change serenity.version to 1.1.36 and execute **mvn serenity:aggregate** - check report - folders were created  for report at target\site\serenity directory
4) Next execute **mvn clean serenity:aggregate** - check report - folders were created for report at target\site\serenity directory

Try to reproduce please. Thanks

**Comment by aukevanleeuwen** [comment] 2016-09-29 11:32
Just wanted to let you know that I am experiencing the same thing after the upgrade.

**Comment by cliviu** [comment] 2016-09-29 11:35
the problem will be fixed in the next release

**Comment by RStrizhak** [comment] 2016-09-29 12:19
Liviu, thank you for fix!

Could you please to give an estimate when will be published the next release?

**Comment by RStrizhak** [comment] 2016-10-01 17:49
Liviu, John thanks!

Issue isn't reproduce in [v1.1.42](https://github.com/serenity-bdd/serenity-core/releases/tag/v1.1.42) version

**Closed** 2016-10-01 17:54 UTC

**Comment by andriyyarish** [comment] 2017-10-03 10:34
I've faced with the described issue even in versions 1.4.* , 1.5.* (current version is 1.5.4-rc.2) during upgrading from 1.1.36. So 
- "clean verify" generates only pure html reports inside site/serenity without resources (there are no exceptions or warnings on report generation)
- "clean serenity:aggregate" generate correct empty report and all necessary resources 
So I found workaround that works for me:
- "clean serenity:aggregate verify" - it generates empty report and resources in site/serenity after clean then within "verify" run tests and perform aggregate one more time

**Comment by wakaleo** [comment] 2017-10-03 10:37
When in doubt, delete the target directory (on Windows in particular, some locked files might prevent the resource copying from working correctly).

**Comment by andriyyarish** [comment] 2017-10-03 11:33
In my case even with pre deleted target directory before execution of "clean verify" it generates only pure html reports inside site/serenity without resources.

**Comment by dineshsundaram** [comment] 2018-01-30 05:10
Can anyone please tell me the solution addressed to this problem. Am using 1.1.37-rc.6  and facing blank reports as stated in this problem. 

wakaleo or RStrizhak: Could you please suggest what solution for this problem?

**Comment by andriyyarish** [comment] 2018-02-01 17:05
dineshsundaram, did you try to perform : ""clean serenity:aggregate verify" - it generates empty report and resources in site/serenity after clean then within "verify" run tests and perform aggregate one more time" as described before ?

**Comment by AnandGiduthuri** [comment] 2024-11-04 05:59
Hi all i am getting same issue how to resolve this issue. 
![image](https://github.com/user-attachments/assets/a4ef8a93-ef6b-4454-8509-06bd26a3c82b)
no bootstrap, jquery, js, data tables folder are generated. can any one me

![image](https://github.com/user-attachments/assets/eeb70e94-6e0d-41e7-8549-336cff51ca0c)
