### ISSUE TITLE
Error using tags in Junit with parametrized tests

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1261] opened 2018-05-29 19:39 UTC
Using the SerenityParametrizedRunner class and tagging some tests, causes that serenity doesn't find any test to execute. This is happening in the last version.

**Comment by wakaleo** [comment] 2018-05-30 20:13
@cliviu any ideas on this?

**Comment by ricardorlg** [comment] 2018-05-30 20:20
The problem happens when serenity is trying to get the tags associated to the method name, It always gets an empty list, but if I run in debug I can get the tags, is really weird.

**Comment by wakaleo** [comment] 2018-05-30 20:32
Hmmm, could be related to threads and thread-local variables maybe?

**Comment by ricardorlg** [comment] 2018-05-30 20:32
I think so.

**Comment by cliviu** [comment] 2018-05-31 05:32
Hmm, we have not changed anything regarding threading, but can you provide a short test project to help us reproduce the problem?

**Comment by ricardorlg** [comment] 2018-05-31 16:55
sure, I will upload an example code.

**Comment by dileepguntamadugu** [comment] 2019-03-06 04:53
This issue still exists would be great if a fix is available

**Comment by wakaleo** [comment] 2019-03-06 05:04
PRs are welcome

**Comment by heikikiisler** [comment] 2019-04-05 08:39
This seems to be working now with 2.0.42

**Comment by wakaleo** [comment] 2019-04-05 08:41
Cool, I will close this issue then - Thanks for the update

**Closed by wakaleo** 2019-04-05 08:41 UTC
