### ISSUE TITLE
Firefox 47 -unsupported driver exception

### ISSUE THREAD

**Issue by ak120684** [serenity-bdd/serenity-core#471] opened 2016-07-01 17:30 UTC
Using:

> serenity_version = "1.1.36"
> serenity_jbehave_version = "1.13.0"
> jersey_version = "2.22.2"

Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:146)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:133)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:103)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:178)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:173)

**Comment by wakaleo** [comment] 2016-07-01 17:49
This is related to https://github.com/SeleniumHQ/selenium/issues/2110 - the next release will include the new dependency, but as a workaround you can updated the Selenium dependencies in your project directly (http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Cselenium-java%7C2.53.1%7Cjar)

**Comment by ak120684** [comment] 2016-07-01 17:55
Cool, that worked...thanks..

**Comment by YamStranger** [comment] 2016-07-02 14:25
@ak120684  It seems that dependency updated, so I will close this issue.

**Closed by YamStranger** 2016-07-02 14:25 UTC

**Comment by prathimak** [comment] 2016-08-16 13:09
Hi there can anyone help me out,we are using thucydides ,i am not able to run tests with firefox and ie.

is there any steps i can follow,below exception i got when i try to run on firefox for ie also i am getting similar exception
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver

**Comment by wakaleo** [comment] 2016-08-16 13:13
Could you post the versions you are using?

**Comment by prathimak** [comment] 2016-08-16 13:17
Firefox: 47,selenium -2.45,selenium-firefox - 2.45,thucydides.version - 0.9.275,
		thucydides.jbehave.version - 0.9.275

**Comment by wakaleo** [comment] 2016-08-16 13:19
You will need to upgrade to Serenity to use the more recent versions of the drivers, as the WebDriver API has changed since we renamed the project from Thucydides to Serenity 2 years ago.

**Comment by prathimak** [comment] 2016-08-16 13:27
Can i have the migration guide to migrate to Serenity

**Comment by larisagrecu** [comment] 2016-09-08 09:01
I am using latest version of serenity (1.1.37-rc.8) and Firefox 47. The test are running but I get this error very often: 
`java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: Timeout waiting for process to die

	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:143)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$200(UnixProcess.java:201)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:246)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:194)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:364)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:310)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:529)
	at net.thucydides.core.webdriver.WebDriverFacade.forcedQuit(WebDriverFacade.java:125)
	at net.thucydides.core.webdriver.WebDriverFacade.reset(WebDriverFacade.java:117)
	at net.thucydides.core.webdriver.WebdriverProxyFactory.resetDriver(WebdriverProxyFactory.java:86)
	at net.serenitybdd.junit.runners.SerenityRunner.prepareBrowserForTest(SerenityRunner.java:480)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:427)
	at net.serenitybdd.junit.runners.SerenityRunner.runChild(SerenityRunner.java:52)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at net.serenitybdd.junit.runners.SerenityRunner.run(SerenityRunner.java:242)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.os.ProcessUtils$ProcessStillAliveException: Timeout waiting for process to die
	at org.openqa.selenium.os.ProcessUtils.waitForProcessDeath(ProcessUtils.java:67)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:139)
	... 33 more
Caused by: java.lang.InterruptedException
	at java.lang.ProcessImpl.waitFor(ProcessImpl.java:451)
	at org.openqa.selenium.os.ProcessUtils$ProcessWaiter.run(ProcessUtils.java:164)
	... 1 more`

Could be caused by compatibility between versions? I didn't had this problems with lower versions like Firefox 41.1 and serenity 1.2.21, although didn't tried other combinations.

**Comment by wakaleo** [comment] 2016-09-08 09:04
This is Firefox refusing to respond to Selenium's request to quit, so potentially an issue with the Firefox driver, or OS load.

**Comment by larisagrecu** [comment] 2016-09-08 09:12
Then a possible solution will be to downgrade the Firefox version

**Comment by wakaleo** [comment] 2016-09-08 09:13
The Selenium guys recommend 45.3 last time I checked.

**Comment by larisagrecu** [comment] 2016-09-14 15:01
Even if I downgraded to Firefox 45.3, I still get that error from time to time, not to often, but is still there. It's hard to find a compatible "relation" between Firefox and Selenium, apparently. Every time I upgrade either Firefox or Serenity, something gets broken. At the moment, for example, I have issues with uploading files, which weren't present with lover versions like Firefox 41 and Serenity 1.1.21.

**Comment by wakaleo** [comment] 2016-09-14 15:32
Chrome tends to be more reliable in my experience - the issue is not with Serenity, but with the versions of Selenium and the Firefox API which tend to get out of sync from time to time.

**Comment by larisagrecu** [comment] 2016-09-15 07:05
You think would be suitable to keep lower versions of FF and Serenity in order to avoid this kind of problems? I can't use at the moment Chrome browser because the requirement is to use Firefox.

**Comment by wakaleo** [comment] 2016-09-15 07:30
You can just use a lower version of Selenium (not Serenity), in most cases that will work fine.

**Comment by larisagrecu** [comment] 2016-09-15 08:00
You're saying to use a lower Selenium dependency directly in my project, in addition to Serenity dependency?  I mention that the framework I use is built with Serenity bdd - Gradle - jUnit, in java.

**Comment by wakaleo** [comment] 2016-09-15 08:02
If you find the right combination of FF and WenDriver, yes, that should work (unless the WebDriver API changed, of course)

**Comment by larisagrecu** [comment] 2016-09-15 10:56
This is the list of dependencies from my "build.gradle" file:
`dependencies {
    compile('de.telekom.bart:bart-account-manager:2.0.7')
    compile('net.serenity-bdd:serenity-core:1.1.38')
    compile('org.slf4j:slf4j-api:1.7.7')
    compile('org.slf4j:log4j-over-slf4j:1.7.7')
    compile('org.slf4j:jul-to-slf4j:1.7.7')
    compile('org.slf4j:jcl-over-slf4j:1.7.7')
    compile('ch.qos.logback:logback-classic:1.1.3')
    compile('de.testbirds.tech:testcase-api:0.3.20')
    compile('org.mnode.ical4j:ical4j:1.0.7')
    compile('org.seleniumhq.selenium:selenium-java:2.45.0')
    testCompile('net.serenity-bdd:serenity-junit:1.1.38')
    testCompile('org.reflections:reflections:0.9.8')
    testCompile('junit:junit:4.12')
    testCompile('org.assertj:assertj-core:1.7.0')
}`

Am I using them right, or is something wrong? Didn't found yet a right combination of FF and WebDriver.  Besides that, in my list of External Libraries , appears the latest version of Selenium, not the one I gave explicitly in the dependency list. See screenshot attached. 
![dependencies](https://cloud.githubusercontent.com/assets/22004716/18547441/1bbbd2d8-7b4c-11e6-9a1c-890cd27552ee.PNG)
