### ISSUE TITLE
Story missing in the report if it fails/throws exception in @BeforeStory method

### ISSUE THREAD

**Issue by nikolaykolev** [serenity-bdd/serenity-core#104] opened 2015-08-05 13:59 UTC
If a story has @BeforeStory and it throws an exception in the before story method it does not show in the report at all. I'm building with maven, serenity version 1.1.2.

**Comment by wakaleo** [comment] 2015-08-05 14:18
Is this a duplicate of https://github.com/serenity-bdd/serenity-jbehave/issues/13? If not, it should be in the serenity-behave project.

**Closed by wakaleo** 2015-08-05 14:18 UTC

**Comment by nikolaykolev** [comment] 2015-08-05 14:53
opened it there, sorry and thanks
