### ISSUE TITLE
Getting error message when invoking Serenity Test

### ISSUE THREAD

**Issue by vaseem78652** [serenity-bdd/serenity-core#2528] opened 2021-08-12 00:20 UTC
Recently I am  getting this error message while running my code.

**Here is the basic sample code:**
I have given the path of the chrome browser in serenity.properties file as webdriver.chrome.driver=src\\test\\resources\\drivers\\chromedriver.exe

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.WebDriver;

import net.serenitybdd.junit.runners.SerenityRunner;
import net.thucydides.core.annotations.Managed;

@RunWith(SerenityRunner.class)
public class loginTest {
	@Managed
	WebDriver driver;
	@Test
	public void login()
	{
		driver.get("http://google.com");
		
	}

}

Getting this error message:

An exception was caught and reported. Message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1b68ddbd
java.lang.IllegalStateException: Unable to load cache item.

Please help me.

**Comment by wakaleo** [comment] 2021-08-13 05:56
Make sure you are using the latest version of Serenity.

**Comment by vaseem78652** [comment] 2021-08-13 07:22
I checked i am using the latest version of serenity bdd from maven.

Anything else i can do to fix this issue.

**Comment by wakaleo** [comment] 2021-08-13 07:29
It's a JVM-related issue, possibly caused by an old version of guava. Check your project for dependency conflicts.

**Comment by ajaykumardhaka** [comment] 2021-08-19 15:42
@wakelo I am trying to run a basic serenity rest. Like launching browser. However I am getting issue. The same code is running fine on local machine. However getting error while running at VM(RDC) for all browsers like chrome, firefox. I have tried all the latest and old versions of serenity.but issue still exist.  Attaching screenshot of log 
![Uploading IMG_20210819_210706.jpg…]()

**Comment by wakaleo** [comment] 2021-11-12 10:01
This is fixed by using the latest versions and making sure you have no dependency conflicts.

**Closed by wakaleo** 2021-11-12 10:01 UTC

**Comment by hetal0212** [comment] 2023-07-29 00:48
Getting the below error when I run my API serenity framework 
[main] ERROR io.github.bonigarcia.wdm.online.HttpClient - Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115
[main] WARN io.github.bonigarcia.wdm.versions.VersionDetector - Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115 to get latest version of chromedriver (Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Downloading https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac_arm64.zip
[main] INFO io.github.bonigarcia.wdm.online.Downloader - Extracting driver from compressed file chromedriver_mac_arm64.zip
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/hetalpatel/.cache/selenium/chromedriver/mac-arm64/114.0.5735.90/chromedriver
Starting ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}) on port 46285
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1690591573.792][WARNING]: This version of ChromeDriver has not been tested with Chrome version 115.
