### ISSUE TITLE
index.html is not generating

### ISSUE THREAD

**Issue by samsul-kabir** [serenity-bdd/serenity-core#1625] opened 2019-03-15 23:33 UTC
Hello there,

I have been trying to generate aggregated report where all my test cases will be reflected. But separate reports has been generating. here is my part of my 

**part of pom.xml**

`<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>2.0.41</serenity.version>
		<serenity.maven.version>2.0.41</serenity.maven.version>
		<serenity.cucumber.version>1.9.31</serenity.cucumber.version>
		<java.version>1.8</java.version>
	</properties>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.20</version>
					<configuration>
						
						<testFailureIgnore>true</testFailureIgnore>
					</configuration>
				</plugin>
				<plugin>
					
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>2.18</version>
					<configuration>
						<includes>
							<include>**/MainRunner.java</include>
						</includes>
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>integration-test</goal>
								<goal>verify</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.2</version>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>net.serenity-bdd.maven.plugins</groupId>
					<artifactId>serenity-maven-plugin</artifactId>
					<version>${serenity.maven.version}</version>
					<dependencies>
						<dependency>
							<groupId>net.serenity-bdd</groupId>
							<artifactId>serenity-core</artifactId>
							<version>${serenity.version}</version>
						</dependency>
					</dependencies>
					<executions>
						<execution>
							<id>serenity-reports</id>
							<phase>post-integration-test</phase>
							<goals>
								<goal>aggregate</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>`

**My test file is given below:**
`@Steps
	   CountriesSearchSteps countriesSearchSteps;

	   @Test
	   public void verifyThatWeCanFindUnitedStatesOfAmericaCountryUsingTheCodeUS() {
	       countriesSearchSteps.searchCountryByCode("US");
	       countriesSearchSteps.searchIsExecutedSuccesfully();
	       countriesSearchSteps.iShouldFindCountry("United States of America");
	   }

	   @Test
	   public void verifyThatWeCanFindIndiaCountryUsingTheCodeIN(){
	       countriesSearchSteps.searchCountryByCode("IN");
	       countriesSearchSteps.searchIsExecutedSuccesfully();
	       countriesSearchSteps.iShouldFindCountry("India");
	   }

	   @Test
	   public void verifyThatWeCanFindBrazilCountryUsingTheCodeBR(){
	       countriesSearchSteps.searchCountryByCode("BR");
	       countriesSearchSteps.searchIsExecutedSuccesfully();
	       countriesSearchSteps.iShouldFindCountry("Brazil");
	   }`

It is generating separate for each Junit Test. But I want to have aggregate report.

Can someone please help on this?

**Comment by wakaleo** [comment] 2019-03-16 01:38
The full report gets generated when you run `mvn serenity:aggregate` or `mvn verify`

**Comment by samsul-kabir** [comment] 2019-03-16 08:04
Hello John, Thank you for your help.

When I try `mvn serenity:aggregate`, it does not run my test, but it creates index.html which is empty. 

When I try `mvn verify` it does not generate aggregated reports. It generates 3 reports. After this when I try `mvn serenity:aggregate`, it creates index.html with aggregated view. So I have to run `mvn verify` first and then  `mvn serenity:aggregate` to get the full result. Is there any better way to do both in one go?

This is what I get when I try `mvn serenity:aggregate`

```
[INFO] Generating test results for 0 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.FileSystemRequirementsTagProvider@22ad1bae, net.thucydides.core.requirements.PackageRequirementsTagProvider@18d003cd]
[INFO] 0 requirements loaded after 21 ms
[INFO] 0 related requirements found after 21 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 84 ms
[INFO] Configured report threads: 20
[INFO] Test results for 0 tests generated in 1.4 secs
```

**Comment by wakaleo** [comment] 2019-03-16 14:41
Have a look at the starter projects to see how to bind the aggregate goal to the verify phase

**Comment by wakaleo** [comment] 2019-04-04 10:28
Closing, presumed answered

**Closed by wakaleo** 2019-04-04 10:28 UTC
Labels: question

**Comment by O2F** [comment] 2019-05-13 22:27
Hello @wakaleo ,
Well I confess that I'm having the same problem as stated above.

> Have a look at the starter projects to see how to bind the aggregate goal to the verify phase
Ok because I'm not the best on maven and for the sake of not changing too much I used your started project just to try to test the aggregate (so all the POM without any change).

The only change I made was on the runner class that instead of running with "CucumberWithSerenity" I use with "SerenityRunner" as you can see below:

`@RunWith(SerenityRunner.class)
public class CucumberTestSuite {


    @Test
    public void cenas() {
        when().get("https://api.iextrading.com/1.0/stock/aapl/company").then().statusCode(Matchers.equalTo(200));
    }
}`

Using any of `mvn clean verify`, `mvn verify` or `mvn serenity:aggregate` doesn't seem to have any effect and although the test pass:

> [INFO] Running starter.CucumberTestSuite
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.591 s - in starter.CucumberTestSuite
> [INFO]
> [INFO] Results:
> [INFO]
> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

The report is not taking into account any test:

> [INFO] --- serenity-maven-plugin:2.0.40:aggregate (serenity-reports) @ serenity-rest-starter ---
> [INFO] current_project.base.dir: C:\Users\<username>\Desktop\serenity-rest-starter-master
> [INFO] Generating test results for 0 tests

If you have the time can you try to reproduce it.
Thank you in advance.

**Comment by Isidor2811** [comment] 2019-11-27 10:15
same happens with jbehave
