### ISSUE TITLE
junit xml generated by gradle task : still issue

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-core#1023] opened 2017-11-13 10:43 UTC
hello @wakaleo 

- Serenity version : 1.7.0
- Serenity gradle : 1.7.0
- Serenity jbehave : 1.33

Regarding this one : https://github.com/serenity-bdd/serenity-core/issues/1008
There is still an issue with the generation of the junit xml : 

- When a test failed, the TEST-Scenario-StoryName.xml is not generated

You can see it on the screen :

![bad junit xml files](https://user-images.githubusercontent.com/29480659/32721530-0e62a40e-c867-11e7-80cd-47bc5e814c8e.png)

All white part on the chart are when test are failing, they should be red, and still have 6 tests.

By the way, I only use the TEST-Scenario-xxx.xml files for the report in jenkins, but I dont know the utility of all the others xml files, can you please give me some clarifications ? thanks :-)

**Comment by wakaleo** [comment] 2017-11-13 10:52
I can't reproduce this issue, and won't have time to look at it in detail for a while. Have a look at the JUnitXMLOutcomeReporter and JUnitXMLConverter and see if anything odd is going on there, and submit a PR if you find anything.

**Comment by mmanach** [comment] 2017-11-13 15:57
I'm currently investigating on this...
A first basic question : **should we use the SERENITY-TEST-xxx.xml generated in the /target/site/serenity/, or TEST-Scenario-xxx.xml generated by gradle in build/test-results/test/ ?**
My issue comes from the gradle one, but with serenity seems ok.

**Comment by wakaleo** [comment] 2017-11-13 16:01
The JUnit reports generated by Serenity are prefixed with SERENITY-JUNIT

**Comment by wakaleo** [comment] 2017-11-17 14:12
This may be a surefire/failsafe issue rather than a Serenity one - Serenity doesn't generate the JUnit reports other than the SERENITY-TEST-* ones.

**Comment by wakaleo** [comment] 2017-11-27 07:28
Could you confirm if you get the correct JUnit reports in Jenkins when you use the SERENITY-TEST-* reports?

**Comment by mmanach** [comment] 2017-11-27 09:29
with last version 1.8.1 ?

**Comment by wakaleo** [comment] 2017-11-27 09:33
Yes

**Comment by mmanach** [comment] 2017-11-27 10:56
Seems still issue with **{workspace}/build/test-results/test/TEST-Scenario*.xml**
Failed cases are not retrieved.

**Comment by wakaleo** [comment] 2017-11-27 10:57
As I mentioned, Serenity does not generate the TEST-Scenario* files. I presume they come from the Main failsafe plugin. Could you try with the JUnit test outputs produced by Serenity?

**Comment by mmanach** [comment] 2017-11-27 12:43
Ah yes sorry, I misread your comment : the Junit files generated by Serenity (SERENITY-TEST-* ) are ok !

**Comment by wakaleo** [comment] 2017-11-27 12:45
Cool! I'll close this issue then, as the TEST-* outputs are not directly related to Serenity or part of the Serenity code base.

**Closed by wakaleo** 2017-11-27 12:45 UTC
