### ISSUE TITLE
serenity 2.2.2 and 2.15 serenity report not generating with multiple JUNIT tags

### ISSUE THREAD

**Issue by tfarrar** [serenity-bdd/serenity-core#2060] opened 2020-04-29 16:24 UTC
I upgraded my serenity version from 2.0.91 to 2.2.2 .
-  I am using the Serenity JUNIT screenplay configuration.

When running mvn build with multiple tags the serenity report is NOT generating.
note: the single-page-html  generate with no problem.
for example:
mvn clean verify  -Dtags="test-type:HEALTHCHECK or test-type:REGRESSION"

When I use a single tags all the reports work..
for example:
mvn clean verify  -Dtags="test-type:HEALTHCHECK"

**Comment by cliviu** [comment] 2020-05-31 22:04
hey @tfarrar , can you confirm that the issue is fixed with the latest serenity version ?

**Comment by tfarrar** [comment] 2020-06-02 21:20
Thanks @cliviu 
I upgraded to version 2.2.5 and I was able to use tags below of junit tests.
mvn clean verify -Dtags="test-type:HEALTHCHECK or test-type:REGRESSION"

**Comment by tfarrar** [comment] 2020-06-02 21:20
Fixed in version 2.2.5

**Closed** 2020-06-02 21:20 UTC
