### ISSUE TITLE
 Failed to generate report for Test Summary Report - userStory must not be null

### ISSUE THREAD

**Issue by vky26** [serenity-bdd/serenity-core#1684] opened 2019-05-21 16:29 UTC
Hi Guys,
I automate native app with Java Jbehave Serenity. I encountered an issue with the report generation on the execution of more than 80 cases.  
In continuation to report being not generated after the execution (https://github.com/serenity-bdd/serenity-core/issues/1682), now I have added capabilities to avoid JAVA Heap space issue. From the recent logs, I couldn't find that issue anymore. Got new error and report didn't get generated. 

Test Environment: 
Mac OS 10.14.3, Mobile Native App (Android Phone with OS 8.0) 
Appium Version: 1.12.1
Jenkins Trigger with maven

Serenity Details:
<serenity.version>2.0.4</serenity.version>
<serenity.jbehave.version>1.42.0</serenity.jbehave.version>

[INFO] Configured report threads: 20
[INFO] Generating test results for 83 tests
[INFO] 75 requirements loaded after 452 ms
[INFO] 75 related requirements found after 455 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 1 secs
[INFO] Configured report threads: 20
[WARNING] Failed to generate report for Test Summary Report - java.util.concurrent.ExecutionException: java.lang.IllegalStateException: userStory must not be null
net.serenitybdd.reports.model.UnstableFeaturesBuilder.withMaxOf(UnstableFeatures.kt:29)
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: userStory must not be null
   at java.util.concurrent.FutureTask.report (FutureTask.java:122)
   at java.util.concurrent.FutureTask.get (FutureTask.java:206)
   at net.thucydides.core.reports.html.Reporter.generateReports (Reporter.java:53)
   at net.thucydides.core.reports.html.Reporter.generateReportsFor (Reporter.java:29)
   at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn (HtmlAggregateStoryReporter.java:211)
   at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom (HtmlAggregateStoryReporter.java:134)
   at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.generateHtmlStoryReports (SerenityAggregatorMojo.java:243)
   at net.serenitybdd.maven.plugins.SerenityAggregatorMojo.execute (SerenityAggregatorMojo.java:186)
   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
   at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
   at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
   at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
   at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
   at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
   at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
   at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
   at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
   at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
   at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
   at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
   at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke (Method.java:498)
   at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
   at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
   at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
   at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.IllegalStateException: userStory must not be null
   at net.serenitybdd.reports.model.UnstableFeaturesBuilder.withMaxOf (UnstableFeatures.kt:29)
   at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext (FreemarkerContext.java:112)
   at net.thucydides.core.reports.html.TextSummaryReportTask.generateReports (TextSummaryReportTask.java:31)
   at net.thucydides.core.reports.html.ReportExecutor.call (ReportExecutor.java:32)
   at net.thucydides.core.reports.html.ReportExecutor.call (ReportExecutor.java:11)
   at java.util.concurrent.FutureTask.run (FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
   at java.lang.Thread.run (Thread.java:745)

Any pointers would be appreciated. @wakaleo 
Thanks

**Comment by wakaleo** [comment] 2019-06-01 15:25
Have you tried with the most recent versions?

**Comment by vky26** [comment] 2019-06-19 10:01
Thanks @wakaleo . 
Failed again with  `<serenity.version> - 2.0.42` and `<serenity.jbehave.version> - 1.45.0` 
will try again with latest and shall update
Trying the below config for next run
`<serenity.version> - 2.0.42` and `<serenity.jbehave.version> - 1.45.0`

**Comment by wakaleo** [comment] 2019-07-24 08:33
Possibly fixed in the latest version

**Comment by mpuertao** [comment] 2021-05-03 04:57
Hello, I have the same problem. I'm testing with serenity core version 2.4.24. Any possible solution?

**Comment by wakaleo** [comment] 2021-05-03 06:00
@mpuertao could you post the exact stack trace?

**Comment by mpuertao** [comment] 2021-05-03 12:51
Hello John, best regards.


  07:46:48.116 [Test worker] DEBUG net.serenitybdd.core.photography.Darkroom - Send negative for processing for target\site\serenity\9d99f379541dcc66975077e9dc975bc60ef96eb8ec9801712a0
4b1abae22d816.png
    07:46:49.065 [Test worker] INFO  -
      _____   ___   ___   _____     ___     _     ___   ___   ___   ___  
     |_   _| | __| / __| |_   _|   | _ \   /_\   / __| / __| | __| |   \
       | |   | _|  \__ \   | |     |  _/  / _ \  \__ \ \__ \ | _|  | |) |
       |_|   |___| |___/   |_|     |_|   /_/ \_\ |___/ |___/ |___| |___/

    Validate deploy of 'sucursal virtual ' environment QA
    ----------------------------------------------------------------------

co.com.bancolombia.certificacion.runners.SmokeTestRunner STANDARD_OUT

    1 Scenarios (1 passed)
    3 Steps (3 passed)
    0m17,005s


    07:46:49.065 [Test worker] DEBUG net.thucydides.core.reports.ReportService - Reporting formats: [JSON]
    07:46:49.212 [Test worker] DEBUG net.thucydides.core.reports.ReportService - Reporting formats: [JSON]
    07:46:49.218 [Test worker] DEBUG net.thucydides.core.reports.ReportService - Generating reports for 1 test outcomes using: net.thucydides.core.reports.json.JSONTestOutcomeReporter@3f
6c8e85
    07:46:49.218 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome Consults for validate deploy on QA:Validate deploy of 'sucursal virtual banco
lombia' environment QA
    07:46:49.218 [pool-1-thread-1] INFO net.thucydides.core.reports.ReportService - net.thucydides.core.reports.json.JSONTestOutcomeReporter@3f6c8e85: Generating report for test outcome:
 Consults for validate deploy on QA:Validate deploy of 'sucursal virtual' environment QA
    07:46:49.218 [pool-1-thread-1] DEBUG net.thucydides.core.reports.json.JSONTestOutcomeReporter - Generating JSON report for Validate deploy of 'sucursal virtual' environme
nt QA to file C:\ProyectoAutomatizacion\PROYECTOS-BANCO\NU0007001_Demo_SmokeTestQA_MR_Test\WEB_Test\SmokeTestQA_WEB_Test\target\site\serenity\f86e8e8142d93c126874690ca32dcfa0699716af4695
c913d416015ccc3fb481.json (using temp file C:\ProyectoAutomatizacion\PROYECTOS-BANCO\NU0007001_Demo_SmokeTestQA_MR_Test\WEB_Test\SmokeTestQA_WEB_Test\target\site\serenity\f86e8e8142d93c1
26874690ca32dcfa0699716af4695c913d416015ccc3fb481.json20fe3d57-c6b0-47dc-9cf8-0b86bd971b52)
    07:46:49.281 [pool-1-thread-1] DEBUG net.thucydides.core.reports.ReportService - Processing test outcome Consults for validate deploy on QA:Validate deploy of 'sucursal virtual banco
lombia' environment QA done
    07:46:49.281 [Test worker] DEBUG net.thucydides.core.reports.ReportService - Shutting down executor service
    07:46:49.281 [Test worker] DEBUG net.thucydides.core.reports.ReportService - Reports generated in: 63 ms
    07:46:49.536 [Test worker] INFO io.cucumber.core.plugin.SerenityReporter - Cleanup test resources for URI file:///C:/ProyectoAutomatizacion/PROYECTOS-BANCO/NU0007001_Demo_SmokeTestQA
_MR_Test/WEB_Test/SmokeTestQA_WEB_Test/src/test/resources/features/smoketestqa/smoke_test_qa.feature
    07:46:49.536 [Test worker] DEBUG net.serenitybdd.core.photography.Darkroom - Closing darkroom
    07:46:49.536 [Darkroom Processing Line] DEBUG net.serenitybdd.core.photography.DarkroomProcessingLine - Darkroom processing line shutting down

Gradle Test Executor 2 finished executing tests.

> Task :test
Finished generating test XML results (0.023 secs) into: C:\ProyectoAutomatizacion\PROYECTOS-BANCO\NU0007001_Demo_SmokeTestQA_MR_Test\WEB_Test\SmokeTestQA_WEB_Test\build\test-results\tes
Generating HTML test report...
Finished generating test html results (0.012 secs) into: C:\ProyectoAutomatizacion\PROYECTOS-BANCO\NU0007001_Demo_SmokeTestQA_MR_Test\WEB_Test\SmokeTestQA_WEB_Test\build\reports\tests\te
st
:test (Thread[Execution worker for ':',5,main]) completed. Took 22.046 secs.
:aggregate (Thread[Execution worker for ':',5,main]) started.

> Task :aggregate
Caching disabled for task ':aggregate' because:
  Build cache is disabled
Task ':aggregate' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Generating Serenity Reports for SmokeTestQA_WEB_Test to directory file:///C:/ProyectoAutomatizacion/PROYECTOS-BANCO/NU0007001_Demo_SmokeTestQA_MR_Test/WEB_Test/SmokeTestQA_WEB_Test/targe
t/site/serenity/
Failed to generate report for Test Summary Report - java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'java.lang.Comparable kotlin.collections.CollectionsKt.minOrNull
(java.lang.Iterable)'
net.serenitybdd.reports.model.DurationsKt.startToFinishTimeIn(Durations.kt:45)
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'java.lang.Comparable kotlin.collections.CollectionsKt.minOrNull(java.lang.Iterable)'
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at net.thucydides.core.reports.html.Reporter.generateReports(Reporter.java:56)
        at net.thucydides.core.reports.html.Reporter.generateReportsFor(Reporter.java:32)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:212)
        at net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:136)
        at net.thucydides.core.reports.UserStoryTestReporter$generateReportsForTestResultsFrom.call(Unknown Source)
        at net.serenitybdd.plugins.gradle.SerenityPlugin$_apply_closure1$_closure9.doCall(SerenityPlugin.groovy:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:670)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:643)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:568)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:553)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:536)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:276)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:265)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at java.base/java.util.Optional.map(Optional.java:258)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Comparable kotlin.collections.CollectionsKt.minOrNull(java.lang.Iterable)'
        at net.serenitybdd.reports.model.DurationsKt.startToFinishTimeIn(Durations.kt:45)
        at net.serenitybdd.reports.model.DurationsKt.clockDurationOf(Durations.kt:38)
        at net.thucydides.core.reports.html.FreemarkerContext.getBuildContext(FreemarkerContext.java:108)
        at net.thucydides.core.reports.html.TextSummaryReportTask.generateReports(TextSummaryReportTask.java:31)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:33)
        at net.thucydides.core.reports.html.ReportExecutor.call(ReportExecutor.java:12)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        ... 1 more









The error continue much more...



dependencies:

ext {
    serenityCoreVersion = "2.4.24"
    serenityCucumberVersion = "2.4.24"
    junitVersion = "4.13.1"
    assertJVersion = '3.8.0'
    logbackVersion = '1.2.3'
    slf4jVersion = '1.7.7'
}

dependencies {
    implementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-junit:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-screenplay:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-cucumber6:${serenityCucumberVersion}"
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    testImplementation "junit:junit:${junitVersion}"
    implementation "org.assertj:assertj-core:${assertJVersion}"
    implementation "org.slf4j:slf4j-simple:${slf4jVersion}"
}

**Comment by wakaleo** [comment] 2021-05-03 12:57
Looks like a different issue ("java.lang.NoSuchMethodError: 'java.lang.Comparable kotlin.collections.CollectionsKt.minOrNull") - are you sure you are using the latest version of the Gradle plugin?

**Comment by mpuertao** [comment] 2021-05-03 13:11
John, I am using net.serenity-bdd: serenity-gradle-plugin: 2.4.24 which is the latest.

Any hint, or something I can change to validate?



apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'net.serenity-bdd.aggregator'

group 'co.com.bancolombia.certificacion'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    mavenLocal()
    jcenter()
   
}

buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        jcenter()
     
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:2.4.24")
    }
}

ext {
    serenityCoreVersion = "2.4.24"
    serenityCucumberVersion = "2.4.24"
    junitVersion = "4.13.1"
    assertJVersion = '3.8.0'
    logbackVersion = '1.2.3'
    slf4jVersion = '1.7.7'
}

dependencies {
    implementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-junit:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-screenplay:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}"
    implementation "net.serenity-bdd:serenity-cucumber6:${serenityCucumberVersion}"
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"
    testImplementation "junit:junit:${junitVersion}"
    implementation "org.assertj:assertj-core:${assertJVersion}"
    implementation "org.slf4j:slf4j-simple:${slf4jVersion}"
}

gradle.startParameter.continueOnFailure = true
gradle.startParameter.refreshDependencies = true

test.finalizedBy(aggregate)

**Comment by wakaleo** [comment] 2021-05-03 13:26
What version of Java are you using?

**Comment by mpuertao** [comment] 2021-05-03 14:28
I have tried with these: 

![image](https://user-images.githubusercontent.com/33495827/116881927-772b7b00-abe9-11eb-8bc5-fa5db3fb6951.png)

**Comment by mpuertao** [comment] 2021-05-03 14:29
John, Do you have an example that the live documentation report works with the latest versions of serenity and cucumber6?

**Comment by lawiorko** [comment] 2021-05-25 11:22
@mpuertao I had similar issue and had to change gradle wrapper version. I have added below to build gradle.
```
wrapper {
    gradleVersion = "6.8.3"
}
```

Also it may require to remove .gradle and gradle directories and let gradle download it again.
I spent a lot of time on that and it resolved my issue.

**Comment by mpuertao** [comment] 2021-05-25 12:42
@lawiorko  excellent, it worked perfectly for me. Very thanks

![image](https://user-images.githubusercontent.com/33495827/119499876-c702eb00-bd2c-11eb-863a-dc22fac58ef5.png)

**Closed** 2022-02-12 15:11 UTC
