### ISSUE TITLE
Custom Webdriver Source gets called for every step (@Given, @When, @Then)

### ISSUE THREAD

**Issue by SaiprasadKrishnamurthy** [serenity-bdd/serenity-core#99] opened 2015-07-29 14:54 UTC
Hi there,

I have a custom webdriver (extended the FirefoxWebDriver) using the steps provided in the serenity manual. This works fine.

But the problem is this is called for  every time when a pageobject.open() is called (even within the same scenario) step which launches a new browser. 

Rather, it should reuse the existing browser for the steps that are part of the same scenario.

This works as expected in case of a regular firefox driver.

Do I have to make this driver source as a singleton or something? Any properties required additionally?

Should I register my custom driver somewhere for serenity to reuse it?

Is there anything I'm missing?

**Comment by wakaleo** [comment] 2015-10-24 10:47
Can you provide a sample project to reproduce the issue?

**Comment by YamStranger** [comment] 2015-11-17 21:04
Hello @SaiprasadKrishnamurthy. Thanks for contacting us. 
Please provide your project to reproduce this issue.

**Comment by YamStranger** [comment] 2015-11-27 13:57
Hello @SaiprasadKrishnamurthy!!

Unfortunately we can't reproduce this issue, so it seems that described problem already fixed in current serenity version. 

Please provide example to reproduce this issue, or if you feel that issue already fixed - please close this issue. 

Thanks a lot!

**Comment by YamStranger** [comment] 2015-11-30 18:35
It seems that this issue already fixed or now it is not an issue.

**Closed by YamStranger** 2015-11-30 18:35 UTC
