### ISSUE TITLE
Encoding problem in Scenario Outline

### ISSUE THREAD

**Issue by jeromevdl** [serenity-bdd/serenity-core#793] opened 2017-05-15 13:38 UTC
Hi,

We use serenity 1.2.4 and serenity-cucumber 1.1.27. 
We use features in french language (# language: fr), with some accent.

In the generated report, in the scenario outline, accent are not correctly displayed. It is the only place where there is a problem. Everything else is correctly displayed. Even the different steps which contain the same text as scenario outline.

Hint: this is [here](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-report-resources/src/main/resources/freemarker/default.ftl):

```
<#if (testOutcome.isDataDriven())>
    <div class="story-title">
        <h3 class="story-header">Scenario Outline</h3>

        <div class="scenario">${formatter.formatWithFields(testOutcome.dataDrivenSampleScenario)}</div>
    </div>
</#if>
```

**Comment by cliviu** [comment] 2017-05-15 15:30
Hi,
try to set property `feature.file.encoding = utf8 `

**Comment by jeromevdl** [comment] 2017-05-15 15:50
I already have this. (indeed i had UTF-8 but utf8 doesnt work either). I also tried in the feature file with 
`# encoding: utf-8`, it does nothing more.

And as I said, steps are well written at the bottom of the report :
> Etant donné un document créé par un utilisateur sans droit de signature

But the same text is not correct in the scenario outline div :
> Etant donnÃ© un document crÃ©Ã© par un utilisateur sans droit de signature

So i guess it is not a problem of reading, but a problem in the output (just in outline).

**Comment by cliviu** [comment] 2017-05-15 21:42
can you please post a screenshot of your report ? maybe also the feature file ?

**Comment by jeromevdl** [comment] 2017-05-16 08:28
![encoding](https://pasteboard.co/6TzprTToc.png)

https://pasteboard.co/6TzprTToc.png

**Comment by cliviu** [comment] 2017-05-16 14:23
can you also post the feature file please  ?

**Comment by jeromevdl** [comment] 2017-05-16 14:29
Everything is on the screenshot... but here it is :

    # language: fr

    Plan du scénario: Deux utilisateurs du même groupe ou de groupe commun signent le même paiement
  
    Création d'un BVR direct par un utilisateur sans droit de signature. 
    Signature par un utilisateur du groupe <groupe1> avec un droit de signature collective puis signature avec un autre utilisateur du groupe <groupe2>.
    Une erreur s'affiche.
    
    Etant donné un BVR direct créé par un utilisateur sans droit de signature
    Et un utilisateur du groupe <groupe1> avec droit de signature collective qui a signé ce même BVR
    Quand un deuxième utilisateur du groupe <groupe2> tente de signer une seconde fois le même BVR
    Alors la signature du BVR échoue (même groupe)
  
    Exemples:
    | groupe1 | groupe2 |
    | A       | A       |
    | B       | B       |

**Comment by cliviu** [comment] 2017-05-16 14:35
Ok, I will try to integrate it in a small example, to see if i can reproduce it. Can you please give me your pom.xml /gradle.build ?

**Comment by jeromevdl** [comment] 2017-05-16 14:58
A partial pom:
    
     <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<selenium.version>2.53.1</selenium.version>
		<serenity.version>1.2.4</serenity.version>
		<serenity.cucumber.version>1.1.27</serenity.cucumber.version>
		<serenity.maven.version>1.2.4</serenity.maven.version>
		<webdriver.driver>phantomjs</webdriver.driver>
	</properties>

	<dependencies>
              <dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
                       <artifactId>serenity-cucumber</artifactId>
                      <version>${serenity.cucumber.version}</version>
                </dependency>
               <dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>1.7.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

       <build>
		<plugins>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.18</version>
				<configuration>
					<systemPropertyVariables>
						<phantomjs.binary.path>${env.PHANTOMJS_BINARY_PATH}</phantomjs.binary.path>
						<phantomjs.cli.args>--ignore-ssl-errors=true --web-security=false</phantomjs.cli.args>
					</systemPropertyVariables>
					<systemProperties>
						<webdriver.driver>${webdriver.driver}</webdriver.driver>
						<feature.file.language>fr</feature.file.language>
                        <feature.file.encoding>UTF-8</feature.file.encoding>
                        <serenity.take.screenshots>AFTER_EACH_STEP</serenity.take.screenshots>
                        <serenity.browser.width>1024</serenity.browser.width>
                        <serenity.browser.height>768</serenity.browser.height>
						<surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
					</systemProperties>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.maven.version}</version>
				<dependencies>
					<dependency>
						<groupId>net.serenity-bdd</groupId>
						<artifactId>serenity-core</artifactId>
						<version>${serenity.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		<plugins>
       <build>

**Comment by cliviu** [comment] 2017-05-16 21:58
I'm not sure where the problem is. I will post my pom.xml 
[pom.zip](https://github.com/serenity-bdd/serenity-core/files/1005944/pom.zip)
and a screenshot of the report 
![scenariooutline](https://cloud.githubusercontent.com/assets/2623175/26130108/83f35612-3a93-11e7-88f6-aef78aa6be25.png)

**Comment by cliviu** [comment] 2017-05-16 22:07
#language: fr

Fonctionnalité: Cukes

Plan du scénario: Deux utilisateurs du même groupe ou de groupe commun signent le même paiement

Création d'un BVR direct par un utilisateur sans droit de signature.
Signature par un utilisateur du groupe <groupe1> avec un droit de signature collective puis signature avec un autre utilisateur du groupe <groupe2>.
Une erreur s'affiche.

Etant donné un BVR direct créé par un utilisateur sans droit de signature
Et un utilisateur du groupe <groupe1> avec droit de signature collective qui a signé ce même BVR
Quand un deuxième utilisateur du groupe <groupe2> tente de signer une seconde fois le même BVR
Alors la signature du BVR échoue (même groupe)

Exemples:
| groupe1 | groupe2 |
| A       | A       |
| B       | B       |

**Comment by jeromevdl** [comment] 2017-05-17 08:13
You changed the library version ? feature file is the same... I will try.

**Comment by cliviu** [comment] 2017-05-17 08:23
Which OS do you use  ? Can you find out what is the default encoding ?

**Comment by cliviu** [comment] 2017-05-17 22:08
Hi. I'm afraid that we have an issue here. I think that the platform default charset is used to deal with the feature file.

**Comment by jeromevdl** [comment] 2017-05-18 08:50
I tried to upgrade version of serenity as in your pom, but i have the same result.

I'm on windows (don't know the default charset).

I don't think it's a feature file reading problem: the feature file is correclty read since tests are executed and steps are well written at the bottom of the report. If there was a problem of reading, everything would be ugly (outline and steps), outline is just an addition of all steps...

**Comment by wakaleo** [comment] 2017-05-22 21:13
Fixed in 1.4.1-rc.2

**Closed by wakaleo** 2017-05-22 21:13 UTC

**Comment by jeromevdl** [comment] 2017-05-23 07:57
Sorry, it does not work. See the screenshot (version 1.4.1-rc.2 at bottom) :

![fail](https://cdn.pbrd.co/images/9EFhX1YQe.png)

**Comment by wakaleo** [comment] 2017-05-23 08:03
Can you provide a sample project? We have been unable to reproduce the issue, so it may be an environment-specific issue that you will need to debug to figure out how to get it working.

**Comment by cliviu** [comment] 2017-05-23 10:31
I think you need the latest cucumber version, there is a fix also there : https://github.com/cliviu/serenity-cucumber/commit/3ca10bdfea4ee2204954fe5c681cc7549c713078

**Comment by jeromevdl** [comment] 2017-05-23 10:37
@cliviu Ok, but it has not been released yet. I already have the 1.1.34... 
@wakaleo I'll try if the cucumber fix doesnt help.

**Comment by jeromevdl** [comment] 2017-05-23 12:08
@cliviu I cannot build the serenity-cucumber module, it even does not compile. Moreover, I've just seen that it is only on your clone, not merged in main one...

**Comment by cliviu** [comment] 2017-05-23 12:20
hi @jeromevdl , The change is merged https://github.com/serenity-bdd/serenity-cucumber/pull/84
Either you build serenity-cucumber on your own (it's compilable, try "gradle build -x test" , then "gradle install") or you wait until a new serenity-cucumber product will be published.

**Comment by jeromevdl** [comment] 2017-05-23 13:24
It works with your modifications! However, i had to change from cucumber.jvm.version=1.1.8 to 1.2.5.

Now I'm waiting the release... any idea of the date ?

Thanks !

**Comment by wakaleo** [comment] 2017-05-23 13:28
Version 1.1.35 should be on maven central within 24 hours

**Comment by jeromevdl** [comment] 2017-05-24 07:27
Version 1.1.35 works well. Thanks for your efficiency !
