### ISSUE TITLE
RequirementsTagProvider - Failed to load requirements: null java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by kutzi** [serenity-bdd/serenity-core#1291] opened 2018-07-03 08:50 UTC
Getting this seldomly, but still:

```
 [pool-2-thread-8] WARN RequirementsTagProvider - Failed to load requirements: null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at net.thucydides.core.requirements.AllRequirements.in(AllRequirements.java:17)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getRequirementFor(FileSystemRequirementsTagProvider.java:426)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.mostSpecificTagRequirementFor(FileSystemRequirementsTagProvider.java:360)
	at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getParentRequirementOf(FileSystemRequirementsTagProvider.java:339)
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26)
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:143)
	at net.thucydides.core.requirements.BaseRequirementsService.getAncestorRequirementsFor(BaseRequirementsService.java:90)
	at net.thucydides.core.tags.BreadcrumbTagFilter.getRequirementBreadcrumbsFrom(BreadcrumbTagFilter.java:50)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addBreadcrumbs(HtmlAcceptanceTestReporter.java:198)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:186)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:225)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:109)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239)
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kutzi** [comment] 2018-07-03 08:50
using Serenity-model 1.9.17

**Comment by kutzi** [comment] 2018-07-03 09:04
Looking at the code in FileSystemRequirementsTagProvider.getRequirements I'm not exactly sure how this can happen.
But I guess that the single lock inside if (requirements == null) might not be enough and a double-checked lock is needed.
Also, returning a defensive copy of requirements instead of the actual reference might help.

**Comment by wakaleo** [comment] 2018-07-03 11:15
Happy to consider a PR for this. Try it out to see if it helps locally. You might want to check if you have duplicate requirement names as well.

**Comment by kutzi** [comment] 2018-07-04 07:07
Can prepare a PR and try to test it locally.

BTW: would be good if you could have a look at the build process and especially how one can change the version number to build.
Last time I had tp spend a lot of time trying to find out which file I have to patch to change the version number

**Comment by kutzi** [comment] 2018-07-04 07:58
See https://github.com/serenity-bdd/serenity-core/pull/1294

**Comment by wakaleo** [comment] 2018-07-12 12:20
Fixed in 1.9.30

**Closed by wakaleo** 2018-07-12 12:20 UTC

**Comment by greatanuragg** [comment] 2020-04-17 08:28
I am facing this issue in 2.0.67, could you please help why this error comes when we have large requirements which are not duplicated.

[pool-2-thread-1] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033

**Comment by wakaleo** [comment] 2020-04-17 08:29
Can you reproduce in 2.2.1?

**Comment by greatanuragg** [comment] 2020-04-17 10:11
I have reproduced this issue in 2.2.1, below is the stack trace, could you please guide the fix ?

[main] ERROR org.apache.maven.plugin.failsafe.IntegrationTestMojo - Tests run: 2244, Failures: 4, Errors: 0, Skipped: 0
[main] INFO org.apache.maven.plugin.failsafe.IntegrationTestMojo - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- serenity-maven-


[main] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)

**Comment by wakaleo** [comment] 2020-04-17 10:12
Thanks. Do you have the top of the stack? This looks like an issue in the Collections class.

**Comment by wakaleo** [comment] 2020-04-17 10:13
It might also be a memory issue.

**Comment by greatanuragg** [comment] 2020-04-17 10:20
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-resources-plugin:2.6:resources (default-resources) @ trading-compliance-serenity ---
[main] INFO org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering - Using 'UTF-8' encoding to copy filtered resources.
[main] INFO org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering - skip non existing resourceDirectory /var/lib/jenkins/workspace/mp-automation_anurag_development/src/main/resources
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-compiler-plugin:3.2:compile (default-compile) @ trading-compliance-serenity ---
[main] INFO org.apache.maven.plugin.compiler.CompilerMojo - Changes detected - recompiling the module!
[main] INFO org.codehaus.plexus.compiler.javac.JavacCompiler - Compiling 8 source files to /var/lib/jenkins/workspace/mp-automation_anurag_development/target/classes
[main] INFO org.apache.maven.plugin.compiler.CompilerMojo - /var/lib/jenkins/workspace/mp-automation_anurag_development/src/main/java/com/tradingcompliance/common/dto/AOResultDTO.java: Some input files use unchecked or unsafe operations.
[main] INFO org.apache.maven.plugin.compiler.CompilerMojo - /var/lib/jenkins/workspace/mp-automation_anurag_development/src/main/java/com/tradingcompliance/common/dto/AOResultDTO.java: Recompile with -Xlint:unchecked for details.
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-resources-plugin:2.6:testResources (default-testResources) @ trading-compliance-serenity ---
[main] INFO org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering - Using 'UTF-8' encoding to copy filtered resources.
[main] INFO org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering - Copying 2 resources
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ trading-compliance-serenity ---
[main] INFO org.apache.maven.plugin.compiler.TestCompilerMojo - Changes detected - recompiling the module!
[main] INFO org.codehaus.plexus.compiler.javac.JavacCompiler - Compiling 2255 source files to /var/lib/jenkins/workspace/mp-automation_anurag_development/target/test-classes
[main] INFO org.apache.maven.plugin.compiler.TestCompilerMojo - /var/lib/jenkins/workspace/mp-automation_anurag_development/src/test/java/com/tradingcompliance/junit/firmwide/FirmwideSerenitySteps.java: Some input files use unchecked or unsafe operations.
[main] INFO org.apache.maven.plugin.compiler.TestCompilerMojo - /var/lib/jenkins/workspace/mp-automation_anurag_development/src/test/java/com/tradingcompliance/junit/firmwide/FirmwideSerenitySteps.java: Recompile with -Xlint:unchecked for details.
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ trading-compliance-serenity ---
[main] INFO org.apache.maven.plugin.surefire.SurefirePlugin - Tests are skipped.
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-jar-plugin:2.4:jar (default-jar) @ trading-compliance-serenity ---
[main] INFO org.codehaus.plexus.archiver.jar.JarArchiver - Building jar: /var/lib/jenkins/workspace/mp-automation_anurag_development/target/trading-compliance-serenity-1.0.0-SNAPSHOT.jar
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-assembly-plugin:2.2-beta-5:single (default) @ trading-compliance-serenity ---
[main] INFO org.apache.maven.plugin.assembly.io.DefaultAssemblyReader - Reading assembly descriptor: src/main/assembly/assembly.xml
[main] INFO org.codehaus.plexus.archiver.dir.DirectoryArchiver - Copying files to /var/lib/jenkins/workspace/mp-automation_anurag_development/target/trading-compliance-serenity-1.0.0-SNAPSHOT-122
[main] WARNING org.apache.maven.plugin.assembly.mojos.SingleAssemblyMojo - Assembly file: /var/lib/jenkins/workspace/mp-automation_anurag_development/target/trading-compliance-serenity-1.0.0-SNAPSHOT-122 is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - 
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- maven-failsafe-plugin:3.0.0-M4:integration-test (default) @ trading-compliance-serenity ---
[main] INFO org.apache.maven.plugin.failsafe.IntegrationTestMojo - 
[main] INFO org.apache.maven.plugin.failsafe.IntegrationTestMojo - -------------------------------------------------------
[main] INFO org.apache.maven.plugin.failsafe.IntegrationTestMojo -  T E S T S
[main] INFO org.apache.maven.plugin.failsafe.IntegrationTestMojo - -------------------------------------------------------
[ThreadedStreamConsumer] INFO org.apache.maven.plugin.failsafe.IntegrationTestMojo - Running com.tradingcompliance.junit.firmwide.commodity.cmdty_manager.CMDTY_TC_44D_Test
1325 [main] INFO  - 

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____ 
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   / 
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /  
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/   
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |     
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|

**Comment by greatanuragg** [comment] 2020-04-17 10:23
Memory issue as in JVM process (heap space ) or you mean about the disk space where tests are running, below is maven-failsafe-plugin config with argLine memory settings:

 <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.0.0-M4</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <includes>
                    <include>**/tradingcompliance/**/*.java</include>
                     <include>**/tradingcompliance/*.java</include>
                     </includes>
               <argLine>-Xmx2048m -XX:MaxPermSize=1024m -Xss16m</argLine>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by wakaleo** [comment] 2020-04-17 10:24
Do you have any more logging for the java.lang.StackOverflowError?

**Comment by greatanuragg** [comment] 2020-04-17 10:27
Build is still running in with below error in infinite loop:

[main] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)

[main] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)

   at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
[main] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)

**Comment by wakaleo** [comment] 2020-04-17 10:28
Have you tried putting a breakpoint on that line and seeing where it is called? Without any more information it will be hard to reproduce.

**Comment by greatanuragg** [comment] 2020-04-17 10:31
Hi John - its getting called as soon all test are executed, it tries to load the requirements for reports. this is 100 % reproducible :(

**Comment by greatanuragg** [comment] 2020-04-17 10:31
Just to add on, I am getting these report generation while running build on jenkins docker agent, on local i am getting timeout exception but still report is getting generated.

**Comment by wakaleo** [comment] 2020-04-17 10:40
Have you tried running with the -e and -X options to see if there is any more information? I'm sure it is reproducible in your environment but if I can't reproduce it, it will be hard to identify what is going on. It could be related to a large number of things.

**Comment by cliviu** [comment] 2020-04-17 10:44
try to change the jdk :-)  https://bugs.openjdk.java.net/browse/JDK-8177031

**Comment by greatanuragg** [comment] 2020-04-17 10:55
JDK version used is 11, and not sure if this is because of jdk.

**Comment by cliviu** [comment] 2020-04-17 11:04
can you try to use, at least for a test the Oracle JDK  ? We have the huge advantage that you can reproduce the issue

**Comment by greatanuragg** [comment] 2020-04-17 11:06
Hi John, below more information from test project:
Project has 11 requirements, 11 features, 2245 stories (2245 test java files, and 2245 json) files and each test java files has multiple tags for reporting purpose (like below), too many tags in each files , will that be causing an issue in getting the RequirementsTagProvider - Failed to load requirements: null exception ???


@RunWith(SerenityRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class IEL_NWARR_TC_01_Test extends BaseIELDatabaseTest
{

@WithTags(
		{   @WithTag("elnclnwar:Product Type=WAR"),
			@WithTag("elnclnwar:SEC_TYP1=TAR"),
			@WithTag("elnclnwar:SEC_TYP2=FI"),
			@WithTag("elnclnwar:SEC_TYP3=SOCGE"),
			@WithTag("elnclnwar:SEC_TYP4=ALL"),
			@WithTag("elnclnwar:EXCH_CD="),
			@WithTag("elnclnwar:IN_ID_TYP="),
			@WithTag("elnclnwar:Test Case No=1"),
			@WithTag("elnclnwar:AGMTExists=Yes"),
			@WithTag("elnclnwar:Account Match=Yes"),
			@WithTag("elnclnwar:Executing Match=Yes"),
			@WithTag("elnclnwar:Multiple=No"),
			@WithTag("elnclnwar:Multiple and Different IEL IDs=No")
	    }
)
@Title("Test case 1 Account Match")
@Test
public void validate() throws Exception
{
    super.validate();
}

**Comment by wakaleo** [comment] 2020-04-17 11:08
It looks like some sort of serialisation issue; the number of tags shouldn't be a problem, other than that the tag reporting could take more time.

**Comment by greatanuragg** [comment] 2020-04-17 11:17
tag reporting taking more time is fine as we need it, what could be the possible fix for serialisation issue ?

**Comment by wakaleo** [comment] 2020-04-17 11:19
With the information at hand it is very hard to say.

**Comment by greatanuragg** [comment] 2020-04-17 11:22
Stacktrace with little more information

[main] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Generating test results for 60 tests
[main] INFO net.thucydides.core.requirements.reports.MultipleSourceRequirmentsOutcomeFactory - Loading requirements from tag providers :[net.thucydides.core.requirements.FileSystemRequirementsTagProvider@6bfb7597, net.thucydides.core.requirements.PackageRequirementsTagProvider@7a3bba35, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@185c5eb4]
[main] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: com.tradingcompliance.junit
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.832 sec - in com.tradingcompliance.junit.firmwide.nobuynosell.nbns_manager.noncrossingzero.NBNS_TC_38_Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.257 sec - in com.tradingcompliance.junit.firmwide.nobuynosell.nbns_manager.noncrossingzero.NBNS_TC_15_Test

Results :

Tests run: 60, Failures: 0, Errors: 0, Skipped: 0

[main] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)

**Comment by wakaleo** [comment] 2020-04-17 11:25
Collections.java is a JDK class, I need to see where it is being called to be able to understand what is happening.

**Comment by greatanuragg** [comment] 2020-04-17 12:29
Just one more observation from yesterday's build which might help in getting the root cause of above errors:

Yesterday's build run with success with test cases, requirement (below stack trace) through it gave lots of  Report generation timed out exceptions
but build was success, only difference in today's build number of new tests added today.

[main] ERROR org.apache.maven.plugin.failsafe.IntegrationTestMojo - Tests run: 2204, Failures: 2, Errors: 5, Skipped: 0

[main] ERROR org.apache.maven.plugin.failsafe.IntegrationTestMojo - Tests run: 2244, Failures: 4, Errors: 0, Skipped: 0




Success build trace:

[main] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - 2291 requirements loaded after 565.4 secs
[main] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - 2291 related requirements found after 607.7 secs
[main] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Generating test outcome reports: false
[main] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Starting generating reports after 3,172.5 secs
[main] INFO net.thucydides.core.reports.NumberOfThreads - Configured report threads: 10
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for Test Summary Report - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for net.thucydides.core.reports.html.AggregateReportingTask@2d118fe5 - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for TagReportingTask for TestTag{name='Firmwide', type='capability'} - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for ResultReportingTask{reportName='01f5288b80adbd3af52a8ed68a4a616d3164f750229f80da1ef344382d948835.html'} - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for ResultReportingTask{reportName='f89aaab6f2e79d36eb3e6fe7fba69f678a4706af4ea008e342bc7b17f9886a80.html'} - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for Requirements report 4aa2483c279e7e47809991c9709a3055121b1fbf03ad5e685d4894ae78f86567.html - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for net.thucydides.core.reports.html.RequirementsTypeReportingTask@10a2c15e - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for Requirements report 514b426738c22721cce9a4f05429a297441714a4c8971b09e58cc9a62c1fa4c8.html - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for Requirements report capabilities.html - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for net.thucydides.core.reports.html.RequirementsTypeReportingTask@46bf13a0 - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Report generation timed out for net.thucydides.core.reports.html.RequirementsTypeReportingTask@deb85899 - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
[main] WARNING net.thucydides.core.reports.html.HtmlAggregateStoryReporter - SOME REPORT PAGES COULD NOT BE GENERATED
 * Report generation timed out for Test Summary Report - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for net.thucydides.core.reports.html.AggregateReportingTask@2d118fe5 - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for TagReportingTask for TestTag{name='Firmwide', type='capability'} - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for ResultReportingTask{reportName='01f5288b80adbd3af52a8ed68a4a616d3164f750229f80da1ef344382d948835.html'} - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for ResultReportingTask{reportName='f89aaab6f2e79d36eb3e6fe7fba69f678a4706af4ea008e342bc7b17f9886a80.html'} - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for Requirements report 4aa2483c279e7e47809991c9709a3055121b1fbf03ad5e685d4894ae78f86567.html - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for net.thucydides.core.reports.html.RequirementsTypeReportingTask@10a2c15e - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for Requirements report 514b426738c22721cce9a4f05429a297441714a4c8971b09e58cc9a62c1fa4c8.html - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for Requirements report capabilities.html - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for net.thucydides.core.reports.html.RequirementsTypeReportingTask@46bf13a0 - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)

 * Report generation timed out for net.thucydides.core.reports.html.RequirementsTypeReportingTask@deb85899 - java.util.concurrent.TimeoutException
java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)


[main] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Test results for 2204 tests generated in 4,751.5 secs
[main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: Saving Build Info to '/var/lib/jenkins/workspace/TRDCMPL_comp-automation_develop/target/build-info.json'
[main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: publish build info set to false, build info will not be published...
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - BUILD SUCCESS
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Total time:  02:41 h
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2020-04-16T10:31:25Z

**Comment by greatanuragg** [comment] 2020-04-20 11:00
More stacktrace from failed build:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/var/lib/jenkins/workspace/TR_co-automation_develop/%3F/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] INFO net.serenitybdd.maven.plugins.SerenityAggregatorMojo - current_project.base.dir: /var/lib/jenkins/workspace/TRDCMPL_comp-automation_develop
[main] INFO net.thucydides.core.reports.html.HtmlAggregateStoryReporter - Generating test results for 2204 tests
[main] INFO net.thucydides.core.requirements.reports.MultipleSourceRequirmentsOutcomeFactory - Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@54b112f6, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@5197cb1, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@39428923]
[main] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: com.tr_co.junit
[main] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
    at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)

**Comment by DeshmNP** [comment] 2020-04-30 07:22
Hi John, 

I am also facing this similar issue in my project, I have approx 2500+ test cases (test java classes as well) in multiple suites.

Reproduced this issue in 2.2.x, I have observed that after running 2500+ test cases, when it tries to load the requirements (I dont know how it works, does it match 1 java class per requirement in serenity report?)
below error is coming-

below is the stack trace, ccan you please help debugging this issue? \
Or how can I resolve this? or can it be resolved by reducing the number of test classes and putting the multiple Junit tests
in a single/few test classes(grouping test casses) 


[main] ERROR org.apache.maven.plugin.failsafe.IntegrationTestMojo - Tests run: 2513, Failures: 6, Errors: 0, Skipped: 0
[main] INFO org.apache.maven.plugin.failsafe.IntegrationTestMojo -
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger -
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - --- serenity-maven-

[main] WARNING net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements: null
java.lang.StackOverflowError
at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)
at java.util.Collections$UnmodifiableCollection.isEmpty (Collections.java:1033)

Thanks!!

**Comment by DeshmNP** [comment] 2020-04-30 07:31
Below is my machine configuration -
Dual core 2.4 Ghz processor
8 GB RAM

My maven failsafe plugin configuration for memory
<forkCount>4<forkCount/>
<reuseFork>true<reuseFork/>
<argLine>-Xmx2048m -XX:MaxPermSize=512m -Xss16m<argLine/>

Can you tell us if this failsafe config is fine to execute 2500+ test java classes using 4 JVM forked processes?
Or how can we know how much memeory is required for serenity to execute the test classes?

As we know by default serenity runs 2 threads per CPU core.

Thanks!! Your help is much appreciated.

**Comment by wakaleo** [comment] 2020-04-30 07:42
Try running on different machines and with different JDK versions - the class in question is a JDK class so it looks like a JDK issue.

**Comment by grtangs** [comment] 2020-05-08 17:37
Tried in different machines with jdk 1.8, 11 and serenity version 2.2.1 and 2.2.2, not getting rid of this issue. Is there a way to stop gathering requirements in reports as these are just name of packages under requirements tab in report ?? I have tried to stop tags in dashboard using below property but this also did not help.

dashboard.excluded.tag.list=requirements
dashboard.excluded.tag.list=Tags
serenity.report.show.tags=false
show.related.tags=false

**Comment by wakaleo** [comment] 2020-05-08 17:39
No, you cannot not generate the requirements reports

**Comment by grtangs** [comment] 2020-05-09 08:01
Could it because of tag requirement timeout issue while reading the package requirement for 2400+ tc's ? Is there a way to put timeout wait for RequirementsTagProvider while it loads the requirements ???

**Comment by wakaleo** [comment] 2020-05-09 08:06
I would really need to see your actual project in action - would you be able to raise a commercial support request for this?

**Comment by ForeverMonica** [comment] 2020-05-09 15:50
Hi John,

I am also experiencing the above issue.

During this i have observed one thing that, when the tests are being executed, requirements are loaded in file \target\site\serenity\requirements\com.projectname.junit-package-requirements.json,
but as soon as we get the error- net.thucydides.core.requirements.RequirementsTagProvider - Failed to load requirements, the contents from the file com.projectname.junit-package-requirements.json, are deleted. This is tested on version 2.2.4.

Any idea why is this happening?

Thanks!!
