### ISSUE TITLE
Three or more uppercase letters in a row duplicate class name in reports

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#215] opened 2015-12-04 17:10 UTC
If class has three or more uppercase letters in a row

![](http://take.ms/ThLRf)

It will be duplicated in reports

![](http://take.ms/ftf9j)

It would also be nice to parse class names like **PatchingCSVDataTest** 
to Patching **CSV** Data Test, 
not to Patching **Csv** Data  Test

**Comment by YamStranger** [comment] 2016-03-02 15:20
Hello @dsmt, thanks for this issue. 

I updated one of test projects, and add some additional classes: 
```
@RunWith(SerenityRunner.class)
public class AAAddAPetToThePetStoreTest {

    @Steps
    ATodoUser jane;

    @Test
    public void do_some_action_with_something () {
        jane.perform("some action for " + this.getClass().getName());
        jane.checkResult("some action" + this.getClass().getName(), "some action" + this.getClass().getName());
    }
}
```
and 

```
@RunWith(SerenityRunner.class)
public class UUUUserCanPerformSimpleActionNumber {

    @Steps
    ATodoUser jane;

    @Test
    public void do_some_action_number () {
        jane.perform("some action for " + this.getClass().getName());
        jane.checkResult("some action" + this.getClass().getName(), "some action" + this.getClass().getName());
    }
}
```
They are in same package
![package](https://cloud.githubusercontent.com/assets/1667699/13459979/44ceee56-e080-11e5-8f10-b9c6a0bd6f94.png)

and run such test with latest serenity modules using gradle. 

My report looks like correct report: 

![class_in_reports](https://cloud.githubusercontent.com/assets/1667699/13459980/44f5012c-e080-11e5-8cf7-5e210d9f3ac6.png)

I can not reproduce your issue - so please provide sample or close this ticket if all already solved for you ) 

 >It would also be nice to parse class names like PatchingCSVDataTest
to Patching CSV Data Test,
not to Patching Csv Data Test

For now it is ready only for test method names, will be updated in future.

**Comment by dsmt** [comment] 2016-03-06 14:08
I can reproduce this issue using `serenity-demos/junit-webtests`. Serenity version is 1.1.28
I renamed class `APetToThePetStoreTest` to `AAAAPetToThePetStoreTest` and it duplicated in `Stories` section

![](http://take.ms/jDVxL)

**Comment by YamStranger** [comment] 2016-03-10 10:01
Hello @dsmt, I tried it with serenity-demos/junit-webtests. 
After cloning it from github I updated build.gradle to 
```
repositories {
    mavenLocal()
    jcenter()
}

ext{
    serenity_version = "1.1.29-rc.1"
}

buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("net.serenity-bdd:serenity-gradle-plugin:1.1.29-rc.1")
    }
}

apply plugin: "java"
apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "net.serenity-bdd.aggregator"

dependencies {
    compile localGroovy()
    compile "net.serenity-bdd:serenity-core:$serenity_version"
    compile "net.serenity-bdd:serenity-junit:$serenity_version"
    compile("net.serenity-bdd:serenity-rest-assured:$serenity_version")
    compile 'org.slf4j:slf4j-simple:1.7.12'
    compile 'org.codehaus.groovy:groovy-all:2.3.10'
    compile 'junit:junit:4.12'
    compile 'com.googlecode.lambdaj:lambdaj:2.3.3'
    compile 'org.assertj:assertj-core:3.1.0'
}



test {
    testLogging {
        showStandardStreams = true
    }
    /* Pass all system properties: */
    systemProperties System.getProperties()
}

gradle.startParameter.continueOnFailure = true
```

and updated pom: 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.serenitybdd.showcase</groupId>
    <artifactId>serenity-junit-webtests</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Serenity JUnit project</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.29-rc.1</serenity.version>
        <serenity.maven.version>1.1.29-rc.1</serenity.maven.version>
        <tags></tags>
    </properties>

    <!-- Define the Bintray repos for convenience -->
    <repositories>
        <repository>
            <id>serenity</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>serenity</id>
            <name>bintray-plugins</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.12</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.3</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.1.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <parallel>classes</parallel>
                    <threadCount>5</threadCount>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                    <parallel>methods</parallel>     
                    <threadCount>2</threadCount>
                    <reuseForks>true</reuseForks>
                    <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                    <systemPropertyVariables>
                        <tags>${tags}</tags>
                    </systemPropertyVariables>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>1.1.29-rc.1</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

after that I navigated to folder junit-webtests and executed command (gradle 2.5 installed on my linux): 
```
gradlew clean test aggregate
```
result: 
![before](https://cloud.githubusercontent.com/assets/1667699/13665596/ef9272a0-e6b5-11e5-910e-8ba2fc68003a.png)

After that I updated class AddAPetToThePetStoreTest : 
```
...
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(SerenityRunner.class)
public class AAAAPetToThePetStoreTest {

    @Steps
    PetStoreSteps petStore;

    @Test
    public void shouldBeAbleToAddPetsToAStore() {
...
```
and executed command
```
gradlew clean test aggregate
```

Here is result screen shot: 

![after](https://cloud.githubusercontent.com/assets/1667699/13665656/36d7fdec-e6b6-11e5-9183-2d57abb9b6d3.png)

same result for `mvn clean verify`

@dsmt I can not reproduce your issue even with same project. 
Lets check: 
1) I use gradle, and grade version is 2.5
2) I cloned demos project and updated only gradle.build and class name (and class file as well)
3) I executed clean before each test (clean test aggregate for gradle and mvn clean verify for mvn)

Please check that you used project without any updates (so right after git cone) and all versions in gradle.build /pom.xml was updated (plugin, core, etc)

Thanks!!

**Comment by YamStranger** [comment] 2016-03-16 08:20
Close this issue because of no activity. It seems that it is already fixed

**Closed by YamStranger** 2016-03-16 08:20 UTC
Labels: bug
