### ISSUE TITLE
After updating to serenity 1.7.4 from 1.5.3, tagging broken

### ISSUE THREAD

**Issue by dgracehmh** [serenity-bdd/serenity-core#1030] opened 2017-11-17 12:15 UTC
Hi, 
I updated serenity 1.5.3 -> 1.7.5 and serenity-cucumber 1.6.4 and my tagging is broken.
I have numerous feature files all tagged with some Scenarios also tagged.

I run via maven
```mvn clean verify -P int -P docker-parallel -Dcucumber.options="--tags @TeacherDashboardResources"```

This all worked fine before the update, it ran what i wanted and omitted what i didn't want to run. 
After the updated it still runs @TeacherDashboardResources but i get these errors for everything not matching @TeacherDashboardResources
```XXX Created runtime cucumber.runtime.RuntimeOptions@5a1de7fb
[2017-11-17 12:08:02:847] [main] INFO Serenity - Test Suite Started: Teacher Generate Reports
[INFO] Running com.hmhco.hmof.testsuites.TeacherGenerateReportsTestSuite
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in com.hmhco.hmof.testsuites.TeacherGenerateReportsTestSuite
[ERROR] com.hmhco.hmof.testsuites.TeacherGenerateReportsTestSuite  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
```

Serenity reports looks fine. Maven build fails though with the errors above.

**Comment by wakaleo** [comment] 2017-11-17 12:23
Thanks for raising this. It sounds like it could be related to the Cucumber 2.x upgrade. I will take a look.

**Comment by wakaleo** [comment] 2017-11-17 12:36
I can't reproduce this, could you provide a sample project?

**Comment by dgracehmh** [comment] 2017-11-17 12:50
Sure, here you go - https://github.com/dgracehmh/serenitysample
To repro run ```mvn clean verify -P int -P local -Dcucumber.options="--tags @Sample1"```

**Comment by wakaleo** [comment] 2017-11-17 13:56
Thanks for that. It is actually an issue with the serenity-cucumber library - should be fixed in the next release.

**Comment by wakaleo** [comment] 2017-11-20 11:18
Fixed in serenity-cucumber 1.6.5

**Closed by wakaleo** 2017-11-20 11:18 UTC

**Comment by dgracehmh** [comment] 2017-11-21 11:37
Thanks for fixing that @wakaleo. I see a release has been done for serenity cucumber - https://github.com/serenity-bdd/serenity-cucumber/releases/tag/v1.6.5 but it is not on maven yet - https://mvnrepository.com/artifact/net.serenity-bdd/serenity-cucumber - How long does it normally take?

**Comment by wakaleo** [comment] 2017-11-21 12:06
It should be available on central within 24 hours.

**Comment by dgracehmh** [comment] 2017-11-21 13:55
Thanks, just wanted to let you know as that release looks like it was made 4 days ago - https://github.com/serenity-bdd/serenity-cucumber/releases/tag/v1.6.5 - thought something might be up. Cheers!
